Repository elastic/cloudbeat, pull requests merged in 2022-12, with the labels that each got.

#564 Resolve panic on race between data and beater
  resources/fetchersManager/data.go
  resources/fetchersManager/data_test.go
Labels: backport-v8.6.0

#571 Fix Packaging
  scripts/make/generate_notice.py
  tests/pylintrc
Labels: backport-skip

#555 [Release] Update version to 8.5.4
  cmd/version.go
Labels: team:automation, release

#573 Fixing Packaging workflow using chatGPT
  scripts/make/generate_notice.py
Labels: backport-skip

#576 docs: update terraform
  deploy/cloud/README.md
  deploy/cloud/outputs.tf
Labels: backport-skip

#577 Add eks deployment to terraform
  bin/.aws-iam-authenticator-0.5.12.pkg
  bin/aws-iam-authenticator
  deploy/cloud/.gitignore
  deploy/cloud/README.md
  deploy/cloud/main.tf
  deploy/cloud/modules/provision-eks-cluster/README.md
  deploy/cloud/modules/provision-eks-cluster/eks-cluster.tf
  deploy/cloud/modules/provision-eks-cluster/main.tf
  deploy/cloud/modules/provision-eks-cluster/outputs.tf
  deploy/cloud/modules/provision-eks-cluster/security-groups.tf
  deploy/cloud/modules/provision-eks-cluster/variables.tf
  deploy/cloud/modules/provision-eks-cluster/vpc.tf
  deploy/cloud/outputs.tf
  deploy/cloud/terraform.tf
  deploy/cloud/variables.tf
Labels: backport-skip

#581 Extend the IAM provider to fetch user data
  deploy/aws/cloudbeat-aws.yml
  resources/fetchers/iam_fetcher.go
  resources/fetchers/iam_fetcher_test.go
  resources/fetching/fetcher.go
  resources/providers/awslib/iam/aws_client_mock.go
  resources/providers/awslib/iam/iam.go
  resources/providers/awslib/iam/password_policy.go
  resources/providers/awslib/iam/provider_mock.go
  resources/providers/awslib/iam/test_data.go
  resources/providers/awslib/iam/user.go
  resources/providers/awslib/iam/user_test.go
Labels: backport-skip

#585 Fixing EKS cluster name
  dataprovider/k8s_data_provider.go
  resources/providers/cluster_provider.go
  resources/providers/cluster_provider_test.go
Labels: backport-skip

#594 Fix OPA package build
  go.mod
  go.sum
  include/include.go
  magefile.go
  version/policy.go
Labels: backport-skip

#582 Add tf run agent on eks
  deploy/cloud/README.md
  deploy/cloud/data/agent_policy.json
  deploy/cloud/data/package_policy.json
  deploy/cloud/main.tf
  deploy/cloud/modules/api/main.tf
  deploy/cloud/modules/api/outputs.tf
  deploy/cloud/modules/api/terraform.tf
  deploy/cloud/modules/api/variables.tf
  deploy/cloud/modules/provision-eks-cluster/eks-cluster.tf
  deploy/cloud/modules/provision-eks-cluster/oidc.tf
  deploy/cloud/outputs.tf
  deploy/cloud/terraform.tf
  deploy/cloud/variables.tf
Labels: backport-skip

#599 Update beats lib
  go.mod
  go.sum
Labels: backport-v8.6.0

#603 fix packaging script
  NOTICE.txt
  deploy/cloud/modules/api/outputs.tf
  scripts/common.sh
  scripts/make/generate_notice.py
Labels: backport-skip

#597 Remove runtime config logic
  _meta/config/cloudbeat.common.yml.tmpl
  beater/validator.go
  beater/validator_test.go
  cloudbeat.reference.yml
  cloudbeat.yml
  config/config.go
  config/config_test.go
  deploy/aws/cloudbeat-aws.yml
  deploy/kustomize/overlays/cloudbeat-eks/cloudbeat.yml
  deploy/kustomize/overlays/cloudbeat-vanilla/cloudbeat.yml
  evaluator/opa.go
  resources/fetchersManager/factory_aws_test.go
  tests/deploy/cloudbeat-eks-pytest.yaml
  tests/deploy/cloudbeat-pytest.yml
  tests/deploy/k8s-cloudbeat-tests/templates/cloudbeat-ds.yml
  tests/deploy/sa-agent-pytest.yml
  version/policy.go
Labels: backport-skip

#598 IAM fetcher - retrieve root account data
  go.mod
  go.sum
  resources/fetchers/iam_fetcher_test.go
  resources/providers/awslib/iam/aws_client_mock.go
  resources/providers/awslib/iam/iam.go
  resources/providers/awslib/iam/provider_mock.go
  resources/providers/awslib/iam/root_account.go
  resources/providers/awslib/iam/test_data.go
  resources/providers/awslib/iam/user.go
  resources/providers/awslib/iam/user_test.go
Labels: backport-skip

#614 Add jq to hermit
  bin/.jq-1.6.pkg
  bin/jq
Labels: backport-skip

#606 terraform update EKS workers count, add ebs_csi driver, and nginx deployment
  deploy/cloud/README.md
  deploy/cloud/main.tf
  deploy/cloud/modules/provision-apps/aws-ebs-csi-driver.tf
  deploy/cloud/modules/provision-apps/nginx-ingress.tf
  deploy/cloud/modules/provision-apps/terraform.tf
  deploy/cloud/modules/provision-apps/variables.tf
  deploy/cloud/modules/provision-eks-cluster/eks-cluster.tf
  deploy/cloud/terraform.tf
  tests/commonlib/kubernetes.py
Labels: backport-skip

#578 Eks CI build push ecr
  .ci/scripts/ecr-images.sh
  .github/workflows/eks-ci.yml
  Makefile
  tests/deploy/sa-agent-pytest.yml
Labels: backport-skip
