Repository elastic/cloudbeat, pull requests merged in 2022-08, with the labels that each got.

#295 Add leader election mechanism to cloudbeat
  beater/cloudbeat.go
  deploy/k8s/cloudbeat-ds-debug.yml
  deploy/k8s/kustomize/base/cloudbeat-ds.yml
  leaderelection/const.go
  leaderelection/leaderelection.go
  leaderelection/leaderelection_test.go
  resources/conditions/kube_lease.go
  resources/conditions/kube_lease_test.go
  resources/conditions/lease_fetcher_condition.go
  resources/fetchersManager/factory.go
  resources/fetchersManager/registry.go
  tests/deploy/cloudbeat-pytest.yml
  tests/deploy/k8s-cloudbeat-tests/templates/cloudbeat-ds.yml
Labels: backport-v8.4.0

#318 Launcher recovery on beater panic
  launcher/launcher.go
  launcher/launcher_test.go
Labels: backport-v8.4.0

#325 Bugfix: update agent-system-metrics lib
  go.mod
  go.sum
Labels: backport-v8.4.0

#314 Eks-setup-guide
  deploy/k8s/eks/Readme.md
  deploy/k8s/eks/cluster-fargate.yml
  deploy/k8s/eks/simple-cluster.yml
Labels: backport-skip

#323 Enable fixed process_api_server_rules tests.
  tests/product/tests/data/process/process_test_cases.py
Labels: backport-v8.4.0

#322 Pass activated rules as an input to OPA
  beater/validator.go
  config/config.go
  config/config_test.go
  evaluator/bundle.go
  evaluator/bundle_test.go
  evaluator/opa.go
  go.mod
  go.sum
  resources/fetchersManager/factory_aws_test.go
Labels: backport-skip

#331 Update CSP integration input types
  _meta/config/cloudbeat.common.yml.tmpl
  beater/validator_test.go
  cloudbeat.reference.yml
  cloudbeat.yml
  config/config.go
  config/config_test.go
  evaluator/bundle_test.go
  resources/fetchersManager/factory_test.go
Labels: backport-skip, 8.5 candidate

#340 Bug fix - init kube watchers upon reconfiguration
  resources/fetchers/kube_factory.go
  resources/fetchers/kube_fetcher.go
  resources/fetchers/kube_fetcher_test.go
Labels: bug, Team:Cloud Security Posture, backport-v8.4.0

#335 DRA job to produce both snapshot & staging artifact by default
  .ci/scripts/rm-docker.sh
  Jenkinsfile
Labels: backport-v8.3.0, backport-v8.4.0

#324 Add integration test for leader election
  tests/commonlib/elastic_wrapper.py
  tests/commonlib/kubernetes.py
  tests/commonlib/utils.py
  tests/integration/tests/conftest.py
  tests/integration/tests/test_cloudbeat_integration.py
Labels: backport-skip

#337 Remote config editing fixes
  README.md
  beater/cloudbeat.go
  scripts/remote_edit_config.sh
Labels: backport-skip

#334 Fixing-customize
  .gitignore
  JUSTFILE
  README.md
  deploy/eks/Readme.md
  deploy/eks/cluster-fargate.yml
  deploy/eks/simple-cluster.yml
  deploy/k8s/cloudbeat-ds-debug.yml
  deploy/k8s/kustomize/base/cloudbeat-ds.yml
  deploy/k8s/kustomize/base/kustomization.yml
  deploy/k8s/kustomize/base/role.yml
  deploy/k8s/kustomize/components/cb_configmap/cloudbeat.yml
  deploy/k8s/kustomize/components/cb_configmap/daemonset_patch.yml
  deploy/k8s/kustomize/components/cb_configmap/kustomization.yml
  deploy/k8s/kustomize/components/cb_leader_lease/kustomization.yml
  deploy/k8s/kustomize/components/cb_leader_lease/leader_lease.yml
  deploy/k8s/kustomize/overlays/cloudbeat-eks/kustomization.yml
  deploy/kustomize/base/config-map.yml
  deploy/kustomize/base/daemonset.yml
  deploy/kustomize/base/kustomization.yml
  deploy/kustomize/base/role-binding.yml
  deploy/kustomize/base/role.yml
  deploy/kustomize/base/service-account.yml
  deploy/kustomize/overlays/cloudbeat-eks/aws.creds
  deploy/kustomize/overlays/cloudbeat-eks/daemonset.yml
  deploy/kustomize/overlays/cloudbeat-eks/kustomization.yml
  deploy/kustomize/overlays/cloudbeat-vanilla/kustomization.yml
  deploy/kustomize/overlays/test/cloudbeat-ds.yml
  deploy/kustomize/overlays/test/kustomization.yml
Labels: backport-skip

#329 Fix flaky file_system_rules tests with better resource-matching.
  _meta/config/cloudbeat.common.yml.tmpl
  cloudbeat.reference.yml
  cloudbeat.yml
  deploy/kustomize/base/config-map.yml
  tests/deploy/cloudbeat-pytest.yml
  tests/deploy/k8s-cloudbeat-tests/templates/cloudbeat-ds.yml
  tests/product/tests/data/file_system/file_system_test_cases.py
  tests/product/tests/test_file_system_rules.py
Labels: backport-skip

#320 Fix broken file_system_rules tests.
  tests/commonlib/io_utils.py
  tests/deploy/k8s-cloudbeat-tests/templates/tests/cloudbeat-test-pod.yml
  tests/product/tests/data/file_system/file_system_test_cases.py
  tests/product/tests/test_file_system_rules.py
Labels: backport-v8.4.0

#354 Fixing_default_cloudbeat_value
  deploy/kustomize/base/config-map.yml
Labels: backport-skip

#355 Run tests on push to version branches + pre-commit settings
  .editorconfig
  .github/workflows/cloudbeat-ci.yml
  .pre-commit-config.yaml
  README.md
Labels: backport-v8.4.0

#351 fixing ci issues
  .github/workflows/Periodic-CI.yml
  .github/workflows/cloudbeat-ci.yml
  .github/workflows/coverage.yml
  .github/workflows/unit-test.yml
  deploy/eks/cluster-fargate.yml
  deploy/eks/simple-cluster.yml
  deploy/k8s/fleet-managed-agent.yml
  deploy/k8s/standalone-agent.yml
  deploy/kustomize/base/daemonset.yml
  deploy/kustomize/base/kustomization.yml
  deploy/kustomize/overlays/cloudbeat-eks/daemonset.yml
  deploy/kustomize/overlays/test/cloudbeat-ds.yml
Labels: backport-skip

#360 Fix OPA logging structure and target
  _meta/config/cloudbeat.common.yml.tmpl
  cloudbeat.reference.yml
  cloudbeat.yml
  config/config.go
  config/config_test.go
  deploy/kustomize/base/config-map.yml
  evaluator/opa.go
  tests/deploy/cloudbeat-pytest.yml
  tests/deploy/k8s-cloudbeat-tests/templates/cloudbeat-ds.yml
Labels: backport-skip

#346 feat: ecs event spec
  evaluator/evaluator.go
  evaluator/opa.go
  evaluator/opa_test.go
  resources/fetchersManager/data.go
  resources/fetching/fetcher.go
  tests/commonlib/utils.py
  transformer/events_creator.go
  transformer/events_creator_test.go
Labels: backport-skip

#369 Update pywin32 version
  .github/workflows/publish-test-results.yml
  tests/Dockerfile
  tests/poetry.lock
  tests/pyproject.toml
Labels: backport-skip
