Repository elastic/cloudbeat, pull requests merged in 2022-11, with the labels that each got.

#483 Map concurrent access panic for events metadata
  transformer/events_creator.go
Labels: backport-skip

#495 Update csp-security-policies to v1.2.2
  go.mod
  go.sum
Labels: backport-v8.5.0

#423 Opa debug logger
  .github/workflows/coverage.yml
  .github/workflows/unit-test.yml
  evaluator/debug_logger/factory.go
  evaluator/debug_logger/factory_test.go
  evaluator/debug_logger/plugin.go
  evaluator/logger.go
  evaluator/logger_test.go
  evaluator/opa.go
  evaluator/opa_test.go
Labels: backport-skip

#486 Standalone-agent-ci-v2
  .ci/scripts/kind-images.sh
  .github/workflows/cloudbeat-ci.yml
  Makefile
  bin/hermit
  bin/hermit.hcl
  dev-tools/packaging/docker/elastic-agent/Dockerfile
  dev-tools/packaging/docker/elastic-agent/build.sh
  justfile
  tests/deploy/sa-agent-pytest.yml
  tests/integration/tests/test_standalone_agent_integration.py
Labels: backport-skip

#458 Agent v2
  beater/cloudbeat.go
  beater/validator.go
  beater/validator_test.go
  cmd/root.go
  config/config.go
  config/config_test.go
  deploy/kustomize/base/daemonset.yml
  go.mod
  go.sum
  launcher/launcher_test.go
  resources/fetchersManager/factory_aws_test.go
  resources/fetchersManager/factory_test.go
  scripts/common.sh
  scripts/remote_replace_cloudbeat.sh
Labels: backport-skip

#490 Fix launcher stop
  beater/cloudbeat.go
  launcher/launcher.go
  launcher/launcher_test.go
  launcher/listener.go
  launcher/listener_test.go
Labels: backport-skip

#508 fix: use latest beats for agent v2
  go.mod
  go.sum
  scripts/remote_replace_cloudbeat.sh
Labels: backport-skip

#472 Fix cloudbeat's testing configuration - adding runtime_cfg to default config
  README.md
  _meta/config/cloudbeat.common.yml.tmpl
  cloudbeat.reference.yml
  cloudbeat.yml
  deploy/kustomize/overlays/cloudbeat-eks/cloudbeat.yml
  deploy/kustomize/overlays/cloudbeat-vanilla/cloudbeat.yml
  scripts/mage/update.go
  tests/deploy/cloudbeat-eks-pytest.yaml
  tests/deploy/cloudbeat-pytest.yml
  tests/deploy/k8s-cloudbeat-tests/templates/cloudbeat-ds.yml
Labels: backport-skip, Team:Cloud Security Posture

#509 Enable decision logs on debug mode
  _meta/config/cloudbeat.common.yml.tmpl
  cloudbeat.reference.yml
  cloudbeat.yml
  config/config.go
  config/config_test.go
  deploy/kustomize/overlays/cloudbeat-eks/cloudbeat.yml
  deploy/kustomize/overlays/cloudbeat-vanilla/cloudbeat.yml
  evaluator/opa.go
  evaluator/opa_test.go
  tests/deploy/cloudbeat-eks-pytest.yaml
  tests/deploy/cloudbeat-pytest.yml
  tests/deploy/k8s-cloudbeat-tests/templates/cloudbeat-ds.yml
Labels: backport-skip

#513 Bump 8.7
  .mergify.yml
  Makefile
  version/version.go
Labels: backport-skip

#510 fix CI false positive functional tests
  .github/workflows/cloudbeat-ci.yml
  justfile
  tests/product/tests/data/process/process_test_cases.py
Labels: backport-v8.6.0

#518 [Release] Update version to 8.5.3
  cmd/version.go
Labels: team:automation, release

#511 Fix v2 bundle path
  .github/workflows/unit-test.yml
  config/config.go
  evaluator/opa.go
  evaluator/opa_test.go
  go.mod
  go.sum
  justfile
  scripts/common.sh
  scripts/remote_replace_bundle.sh
  scripts/remote_replace_cloudbeat.sh
Labels: backport-v8.6.0

#507 add configuration required for EKS clusters
  tests/README.md
  tests/deploy/aws/eks_config/test-eks-config-1-node-1-10-kubelet-args.conf
  tests/deploy/aws/eks_config/test-eks-config-1-node-1-kubelet-config.json
  tests/deploy/aws/eks_config/test-eks-config-1-node-2-10-kubelet-args.conf
  tests/deploy/aws/eks_config/test-eks-config-1-node-2-kubelet-config.json
  tests/deploy/aws/eks_config/test-eks-config-2-node-1-10-kubelet-args.conf
  tests/deploy/aws/eks_config/test-eks-config-2-node-1-kubelet-config.json
  tests/deploy/aws/eks_config/test-eks-config-2-node-2-10-kubelet-args.conf
  tests/deploy/aws/eks_config/test-eks-config-2-node-2-kubelet-config.json
Labels: backport-skip

#523 Remove streams struct
  _meta/config/cloudbeat.common.yml.tmpl
  beater/cloudbeat.go
  cloudbeat.reference.yml
  cloudbeat.yml
  config/config.go
  config/config_test.go
  deploy/kustomize/overlays/cloudbeat-eks/cloudbeat.yml
  deploy/kustomize/overlays/cloudbeat-vanilla/cloudbeat.yml
  evaluator/opa.go
  evaluator/opa_test.go
  justfile
  leaderelection/leaderelection.go
  resources/fetchersManager/factory.go
  resources/fetchersManager/factory_aws_test.go
  resources/fetchersManager/factory_test.go
  tests/deploy/cloudbeat-eks-pytest.yaml
  tests/deploy/cloudbeat-pytest.yml
  tests/deploy/k8s-cloudbeat-tests/templates/cloudbeat-ds.yml
  transformer/common_data_provider.go
  transformer/common_data_provider_test.go
  transformer/transformer.go
Labels: backport-skip

#529 skip mock files in coverage report
  .github/workflows/unit-test.yml
Labels: backport-skip

#548 Pin GH workers ubuntu image to 20.04
  .github/workflows/Periodic-CI.yml
  .github/workflows/cloudbeat-ci.yml
  .github/workflows/packaging.yml
  .github/workflows/publish-test-results.yml
  .github/workflows/unit-test.yml
  Makefile
  go.mod
Labels: backport-v8.6.0

#544 fix ci for stand-alone agent
  .github/workflows/cloudbeat-ci.yml
  justfile
Labels: backport-skip

#545 Fix sa agent tests
  tests/commonlib/io_utils.py
  tests/deploy/sa-agent-pytest.yml
  tests/integration/tests/test_standalone_agent_integration.py
  tests/pyproject.toml
Labels: backport-skip

#554 Updated elastic-agent-client to v7.0.2-0.20221129150247-15881a8e64ef
  go.mod
  go.sum
Labels: backport-v8.6.0

#558 actions: use go-version-file: .go-version
  .github/workflows/Periodic-CI.yml
  .github/workflows/unit-test.yml
Labels: backport-v8.5.0, backport-v8.6.0

#517 Cloudbeat README refactor
  CONTRIBUTING.md
  README.md
  bin/README.hermit.md
  deploy/kustomize/overlays/cloudbeat-vanilla-agent/README.md
  dev-docs/Architecture.md
  dev-docs/Development.md
  dev-docs/Release.md
  tests/README.md
Labels: backport-skip
