Repository elastic/cloudbeat, pull requests merged in 2022-10, with the labels that each got.

#425 Event sequence mismatch between fetchers of same cycle
  resources/fetchersManager/data.go
Labels: backport-v8.5.0

#408 Refactor build code aka "The one in which we remove utils/go.mod"
  .ci/bump-go-release-version.sh
  .ci/bump-stack-version.sh
  .ci/packer_cache.sh
  .ci/scripts/bench.sh
  .ci/scripts/build-darwin.sh
  .ci/scripts/check-changelogs.sh
  .ci/scripts/docker-get-logs.sh
  .ci/scripts/gh-cache.sh
  .ci/scripts/kind-images.sh
  .ci/scripts/linux-test.sh
  .ci/scripts/package-docker-snapshot.sh
  .ci/scripts/run-tests.sh
  .ci/scripts/test-darwin.sh
  .ci/scripts/update-beats.sh
  .github/workflows/cloudbeat-ci.yml
  .pre-commit-config.yaml
  Jenkinsfile
  Makefile
  make.bat
  scripts/make/check_docker_compose.sh
  scripts/make/generate_notice.py
  scripts/make/latest_snapshot_version.py
  scripts/make/run_with_go_ver
  setup.cfg
  utils/go.mod
  utils/go.sum
  utils/tools.go
Labels: backport-v8.5.0

#433 Add Concurrency queue to all workflows
  .github/workflows/cloudbeat-ci.yml
  .github/workflows/coverage.yml
  .github/workflows/packaging.yml
  .github/workflows/publish-ecr.yml
  .github/workflows/unit-test.yml
Labels: 8.5 candidate, backport-v8.5.0

#437 remove trigger type "assigned" on pr
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/workflows/coverage.yml
  .github/workflows/packaging.yml
  .github/workflows/unit-test.yml
Labels: backport-v8.5.0

#439 More checks in `process_kubelet_rules` test resource matching.
  tests/product/tests/test_process_kubelet_rules.py
Labels: backport-skip

#441 feat: add cluster name to elb resource
  transformer/common_data_provider.go
  transformer/common_data_provider_test.go
Labels: backport-skip

#449 Optimize test stack resources & cloudbeat cycle duration
  justfile
  tests/deploy/cloudbeat-pytest.yml
  tests/deploy/k8s-cloudbeat-tests/values.yaml
Labels: backport-v8.5.0

#450 update code owners file
  .github/CODEOWNERS
Labels: backport-skip

#452 Add hermit to ci
  .github/workflows/cloudbeat-ci.yml
  .github/workflows/coverage.yml
  .github/workflows/packaging.yml
  .github/workflows/unit-test.yml
  bin/.mage-1.14.0.pkg
  bin/mage
Labels: backport-v8.5.0

#400 Eks basic integration tests for cloudbeat
  .pre-commit-config.yaml
  justfile
  tests/commonlib/elastic_wrapper.py
  tests/commonlib/io_utils.py
  tests/commonlib/utils.py
  tests/configuration.py
  tests/deploy/cloudbeat-eks-pytest.yaml
  tests/deploy/k8s-cloudbeat-tests/templates/cloudbeat-test-configmap.yml
  tests/deploy/k8s-cloudbeat-tests/templates/tests/cloudbeat-test-pod.yml
  tests/deploy/values/ci-sa-agent.yml
  tests/deploy/values/ci.yml
  tests/deploy/values/local-host.yml
  tests/integration/tests/conftest.py
  tests/integration/tests/test_cloudbeat_integration.py
  tests/product/tests/data/file_system/eks_test_cases.py
  tests/product/tests/data/process/process_test_cases.py
  tests/pylintrc
  tests/setup.cfg
Labels: backport-skip

#454 Fix Cloudbeat debug setup
  Dockerfile.debug
  README.md
  justfile
Labels: backport-skip, 8.6 candidate, Team:Cloud Security Posture

#448 Add just build-replace-cloudbeat command
  justfile
  scripts/common.sh
  scripts/remote_edit_config.sh
  scripts/remote_replace_cloudbeat.sh
Labels: backport-skip

#456 feat: connect kind to elk network
  justfile
Labels: backport-skip

#422 feat: run pre-merge in multi node
  .ci/scripts/kind-images.sh
  .github/workflows/Periodic-CI.yml
  .github/workflows/cloudbeat-ci.yml
  deploy/k8s/kind/kind-mono.yml
  justfile
  tests/configuration.py
  tests/deploy/cloudbeat-pytest.yml
  tests/deploy/k8s-cloudbeat-tests/templates/tests/cloudbeat-test-pod.yml
  tests/integration/tests/conftest.py
  tests/product/tests/conftest.py
Labels: backport-skip

#455 Add cluster name processor
  processor/add_cluster_id/add_cluster_id.go
  processor/add_cluster_id/add_cluster_id_test.go
  processor/add_cluster_id/cluster_metadata_provider.go
  processor/add_cluster_id/cluster_metadata_provider_test.go
  processor/add_cluster_id/config.go
  processor/add_cluster_id/errors.go
  processor/cluster_helper_test.go
  processor/processors.go
  resources/fetchers/file_system_fetcher_test.go
  transformer/events_creator_test.go
Labels: backport-skip

#464 Add catf & elk logs
  .ci/scripts/integration-tests.sh
  .ci/scripts/run-tests.sh
  .github/workflows/cloudbeat-ci.yml
  .gitignore
  .pre-commit-config.yaml
  deploy/k8s/kind/kind-mono.yml
  deploy/k8s/kind/kind-multi.yml
  justfile
  test-logs/.gitkeep
  tests/deploy/cloudbeat-pytest.yml
Labels: backport-skip

#457 feat: crash cloudbeat when update configuration is failed
  beater/cloudbeat.go
  launcher/launcher.go
  launcher/launcher_test.go
Labels: backport-skip

#463 fix: connect all kind containers to elastic-packge network
  .ci/scripts/connect_kind.sh
  justfile
Labels: backport-skip

#470 hermit add to readme
  README.md
  justfile
Labels: backport-skip

#474 Added elastic-package to hermit
  bin/.elastic-package-0.66.1.pkg
  bin/elastic-package
Labels: backport-skip, Team:Cloud Security Posture
