Repository elastic/cloudbeat, pull requests merged in 2022-09, with the labels that each got.

#367 feat: support latest elastic-packge stack deployment with ssl
  .github/workflows/unit-test.yml
  JUSTFILE
  deploy/kustomize/overlays/cloudbeat-vanilla/kustomization.yml
  deploy/kustomize/overlays/cloudbeat-vanilla/patches/patch-add-ssl-certs.yaml
Labels: backport-skip

#373 hermit depedency management
  Makefile
  bin/.go-1.18.4.pkg
  bin/.helm-3.9.4.pkg
  bin/.just@1.pkg
  bin/.kind-0.12.0.pkg
  bin/.kubectl@1.24.pkg
  bin/README.hermit.md
  bin/activate-hermit
  bin/go
  bin/gofmt
  bin/helm
  bin/hermit
  bin/hermit.hcl
  bin/just
  bin/kind
  bin/kubectl
Labels: backport-v8.4.0

#370 Dependency review workflow
  .github/workflows/unit-test.yml
Labels: backport-skip

#338 Modify leader election mechanism block timeout
  beater/cloudbeat.go
  deploy/kustomize/base/daemonset.yml
  leaderelection/const.go
  leaderelection/leaderelection.go
  leaderelection/leaderelection_test.go
  resources/conditions/lease_fetcher_condition.go
  resources/fetchersManager/factory_aws_test.go
  resources/fetchersManager/factory_test.go
  resources/fetchersManager/registry.go
Labels: backport-skip, 8.5 candidate, Team:Cloud Security Posture

#368 automate golang version bump
  .ci/bump-go-release-version.sh
  .github/workflows/Periodic-CI.yml
  .github/workflows/cloudbeat-ci.yml
  .github/workflows/coverage.yml
  .github/workflows/packaging.yml
  .github/workflows/publish-ecr.yml
  .github/workflows/unit-test.yml
Labels: backport-skip

#382 Patch pytest dockerfile
  tests/Dockerfile
Labels: backport-skip

#376 fix: connect kind cluster to elastic-package network
  JUSTFILE
Labels: backport-skip

#379 chore: add test
  config/config_test.go
Labels: backport-skip

#374 Make tests more concurrent.
  .github/workflows/cloudbeat-ci.yml
  JUSTFILE
  tests/conftest.py
  tests/deploy/k8s-cloudbeat-tests/templates/cloudbeat-test-configmap.yml
  tests/deploy/k8s-cloudbeat-tests/templates/tests/cloudbeat-test-pod.yml
  tests/product/tests/conftest.py
  tests/product/tests/parameters.py
  tests/product/tests/test_file_system_rules.py
  tests/product/tests/test_k8s_objects_rules.py
  tests/product/tests/test_process_api_server_rules.py
  tests/product/tests/test_process_controller_manager_rules.py
  tests/product/tests/test_process_etcd_rules.py
  tests/product/tests/test_process_kubelet_rules.py
  tests/product/tests/test_process_scheduler_rules.py
Labels: backport-skip

#385 [automation] Update go release version 1.18.6
  .go-version
  docs/version.asciidoc
Labels: backport-skip, automation, dependency

#392 Update description
  README.md
  justfile
Labels: backport-skip

#380 Load OPA bundle from FS
  .github/workflows/Periodic-CI.yml
  .github/workflows/cloudbeat-ci.yml
  .github/workflows/packaging.yml
  .gitignore
  Dockerfile
  Dockerfile.debug
  evaluator/bundle.go
  evaluator/bundle_test.go
  evaluator/opa.go
  justfile
  magefile.go
  scripts/mage/package.go
  tests/product/tests/data/process/process_test_cases.py
Labels: backport-skip, 8.5 candidate, Team:Cloud Security Posture

#398 Use GitHub token in setup-just action
  .github/workflows/Periodic-CI.yml
  .github/workflows/cloudbeat-ci.yml
Labels: backport-skip

#399 fix depedency scanner on push event
  .github/workflows/unit-test.yml
Labels: backport-skip

#381 new Issue / PR templates
  .github/ISSUE_TEMPLATE/csp_task.md
  .github/templates/bug_report.md
  .github/templates/feature_request.md
  .github/templates/issue_template.md
  .github/templates/pull_request_template.md
Labels: backport-skip

#401 Fix release ci #5003
  .ci/scripts/build.sh
  .ci/scripts/intake.sh
  .ci/scripts/package.sh
  Jenkinsfile
  Makefile
  bin/.go-1.18.6.pkg
  bin/.opa-0.43.0.pkg
  bin/go
  bin/gofmt
  bin/opa
  docs/fields.asciidoc
  magefile.go
Labels: backport-skip

#406 Update csp-security-policies to v1.2.0
  go.mod
  go.sum
Labels: backport-skip

#386 feat: deploy agent on kind cluster
  .gitignore
  deploy/kustomize/overlays/cloudbeat-vanilla-agent/.fleet-token.env
  deploy/kustomize/overlays/cloudbeat-vanilla-agent/README.md
  deploy/kustomize/overlays/cloudbeat-vanilla-agent/kustomization.yml
  deploy/kustomize/overlays/cloudbeat-vanilla-agent/manifests.yaml
  deploy/kustomize/overlays/cloudbeat-vanilla-agent/patches/patchs.yaml
Labels: backport-skip

#390 Delegate opa logger to logp lib
  evaluator/logger.go
  evaluator/logger_test.go
  evaluator/opa.go
  go.mod
Labels: backport-skip

#407 support new templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: backport-skip

#404 Unwrap errors
  .golangci.yaml
  launcher/launcher.go
  resources/fetchers/ecr_fetcher.go
  resources/fetchers/process_fetcher.go
  resources/fetchersManager/factory.go
Labels: backport-skip

#413 Bump main to 8.6
  .mergify.yml
  cmd/version.go
  justfile
Labels: backport-skip

#415 Mend CI with resource identifiers, increased timeout.
  .github/workflows/cloudbeat-ci.yml
  go.mod
  go.sum
  tests/commonlib/utils.py
  tests/configuration.py
  tests/product/tests/data/process/process_test_cases.py
  tests/product/tests/test_process_api_server_rules.py
  tests/product/tests/test_process_controller_manager_rules.py
  tests/product/tests/test_process_etcd_rules.py
  tests/product/tests/test_process_kubelet_rules.py
  tests/product/tests/test_process_scheduler_rules.py
Labels: backport-v8.5.0
