Repository elastic/cloudbeat, pull requests merged in 2022-06, with the labels that each got.

#195 Fix snapshot ci build on main
  .ci/scripts/package.sh
Labels: backport-v8.3.0

#164 Adding metadata to EKS
  resources/fetchers/ecr_fetcher.go
  resources/fetchers/eks_fetcher.go
  resources/fetchers/elb_fetcher.go
  resources/fetchers/iam_fetcher.go
Labels: backport-skip

#200 Add component tests for new rules
  go.mod
  go.sum
  tests/product/tests/test_rules.py
  tests/product/tests/tests/file_system/file_system_test_cases.py
  tests/product/tests/tests/process/process_test_cases.py
Labels: 8.4 candidate, backport-skip

#172 Update readme on beta
  README.md
Labels: backport-v8.3.0

#202 More logs
  beater/cloudbeat.go
Labels: backport-v8.3.0

#192 3932-ECRPublicFetcher
  resources/fetchers/ecr_factory.go
  resources/fetchers/ecr_factory_test.go
  resources/fetchers/ecr_fetcher.go
  resources/fetchers/ecr_fetcher_test.go
  resources/fetchers/elb_fetcher_test.go
  resources/providers/awslib/ecr_public_provider.go
Labels: backport-skip

#208 Update automation CODEOWNERS
  .github/CODEOWNERS
Labels: backport-skip

#210 Remote editing of cloudbeat.yml
  scripts/remote_edit_config.sh
Labels: backport-skip

#211 Instructions for remote_edit_config script
  README.md
Labels: backport-skip

#169 Kube api rules atuomated tests
  tests/commonlib/io_utils.py
  tests/commonlib/kubernetes.py
  tests/commonlib/utils.py
  tests/deploy/mock-pod.yml
  tests/product/tests/conftest.py
  tests/product/tests/kube_rules.py
  tests/product/tests/test_kube_api_rules.py
Labels: backport-skip

#212 Transformer support multithread requests
  transformer/events_creator.go
  transformer/events_creator_test.go
Labels: backport-skip

#207 Cloudbeat to support processing of k8s cert files
  _meta/config/cloudbeat.common.yml.tmpl
  cloudbeat.reference.yml
  deploy/k8s/cloudbeat-ds-debug.yml
  deploy/k8s/kustomize/base/cloudbeat-ds.yml
  go.mod
  go.sum
  tests/commonlib/io_utils.py
  tests/deploy/cloudbeat-pytest.yml
  tests/deploy/k8s-cloudbeat-tests/templates/cloudbeat-ds.yml
  tests/product/tests/test_rules.py
  tests/product/tests/tests/file_system/file_system_test_cases.py
Labels: backport-skip

#221 Pre merge cloudbeat integration
  .github/workflows/cloudbeat-ci.yml
  tests/commonlib/elastic_wrapper.py
  tests/commonlib/kubernetes.py
  tests/configuration.py
  tests/conftest.py
  tests/deploy/values/ci.yml
  tests/deploy/values/local-host.yml
  tests/integration/tests/conftest.py
  tests/integration/tests/test_cloudbeat_integration.py
  tests/integration/tests/test_output_to_elasticsearch.py
  tests/poetry.lock
  tests/product/tests/conftest.py
  tests/product/tests/test_cloudbeat.py
  tests/product/tests/test_kube_api_rules.py
  tests/product/tests/test_process_api_server_rules.py
  tests/product/tests/test_process_controller_manager_rules.py
  tests/product/tests/test_process_etcd_rules.py
  tests/product/tests/test_process_kubelet_rules.py
  tests/product/tests/test_process_scheduler_rules.py
  tests/product/tests/test_rules.py
  tests/pyproject.toml
Labels: backport-v8.3.0

#225 Test add cluster id processor
  processor/add_cluster_id.go
  processor/add_cluster_id_test.go
  processor/cluster_helper.go
  processor/cluster_helper_test.go
Labels: backport-skip

#222 Added mage target allowing to construct agent with cloudbeat bundled in
  Makefile
  cloudbeat.yml
  go.mod
  go.sum
  magefile.go
Labels: backport-skip

#232 Opa logger rename fields
  beater/bundle/bundle.go
  evaluator/opa.go
  transformer/events_creator.go
Labels: backport-skip

#217 Modify FS resource fields
  go.mod
  go.sum
  resources/fetchers/file_system_factory.go
  resources/fetchers/file_system_fetcher.go
  resources/fetchers/file_system_fetcher_test.go
  resources/utils/mock_os_user.go
  resources/utils/user.go
  resources/utils/user_test.go
  transformer/events_creator_test.go
Labels: backport-skip

#236 Feature 3893/update cloudbeat dependencies
  beater/bundle/bundle.go
  beater/cloudbeat.go
  beater/cloudbeat_test.go
  config/config.go
  config/config_test.go
  config/updates.go
  evaluator/opa.go
  go.mod
  go.sum
  magefile.go
  processor/add_cluster_id.go
  processor/add_cluster_id_test.go
  processor/cluster_helper_test.go
  resources/conditions/lease_fetcher_condition.go
  resources/fetchers/ecr_factory.go
  resources/fetchers/ecr_factory_test.go
  resources/fetchers/ecr_fetcher.go
  resources/fetchers/ecr_fetcher_test.go
  resources/fetchers/eks_factory.go
  resources/fetchers/eks_factory_test.go
  resources/fetchers/eks_fetcher.go
  resources/fetchers/eks_fetcher_test.go
  resources/fetchers/elb_factory.go
  resources/fetchers/elb_factory_test.go
  resources/fetchers/elb_fetcher.go
  resources/fetchers/elb_fetcher_test.go
  resources/fetchers/file_system_factory.go
  resources/fetchers/file_system_factory_test.go
  resources/fetchers/file_system_fetcher.go
  resources/fetchers/file_system_fetcher_test.go
  resources/fetchers/iam_factory.go
  resources/fetchers/iam_factory_test.go
  resources/fetchers/iam_fetcher.go
  resources/fetchers/iam_fetcher_test.go
  resources/fetchers/kube_factory.go
  resources/fetchers/kube_factory_test.go
  resources/fetchers/kube_fetcher.go
  resources/fetchers/kube_provider.go
  resources/fetchers/process_factory.go
  resources/fetchers/process_factory_test.go
  resources/fetchers/process_fetcher.go
  resources/fetchers/process_fetcher_test.go
  resources/fetching/fetcher.go
  resources/manager/data.go
  resources/manager/data_test.go
  resources/manager/factory.go
  resources/manager/factory_test.go
  resources/manager/registry.go
  resources/manager/registry_test.go
  resources/providers/awslib/iam_provider.go
  resources/providers/kubernetes_provider.go
  resources/providers/kubernetes_provider_mock.go
  transformer/common_data_provider.go
  transformer/common_data_provider_test.go
  transformer/events_creator.go
  transformer/events_creator_test.go
  transformer/transformer.go
Labels: backport-skip

#233 Send resources one by one
  JUSTFILE
  go.mod
  go.sum
  resources/fetchers/ecr_fetcher.go
  resources/fetchers/ecr_fetcher_test.go
  resources/fetchers/elb_fetcher.go
  resources/fetchers/elb_fetcher_test.go
Labels: backport-skip

#167 Upgrade go verison to 1.18
  .github/workflows/cloudbeat-ci.yml
  .github/workflows/packaging.yml
  .github/workflows/publish-ecr.yml
  .github/workflows/unit-test.yml
  .go-version
  docs/version.asciidoc
  go.mod
  utils/go.mod
  utils/go.sum
Labels: 8.4 candidate, backport-skip

#240 Disable OPA decision logs
  evaluator/bundle.go
  evaluator/bundle_test.go
  evaluator/opa.go
Labels: backport-skip

#32 Add kube fetcher tests
  resources/fetchers/kube_factory.go
  resources/fetchers/kube_fetcher.go
  resources/fetchers/kube_fetcher_test.go
Labels: backport-skip

#245 Integrate skaffold & kustomize
  .gitignore
  Makefile
  README.md
  cloudbeat_minikube.yml.patch
  deploy/k8s/kustomize/base/daemonset.yml
  deploy/k8s/kustomize/base/kustomization.yml
  deploy/k8s/kustomize/base/role-binding.yml
  deploy/k8s/kustomize/base/role.yml
  deploy/k8s/kustomize/base/service-account.yml
  deploy/k8s/kustomize/components/cb_configmap/cloudbeat.yml
  deploy/k8s/kustomize/components/cb_configmap/daemonset_patch.yml
  deploy/k8s/kustomize/components/cb_configmap/kustomization.yml
  deploy/k8s/kustomize/components/cb_leader_lease/kustomization.yml
  deploy/k8s/kustomize/components/cb_leader_lease/leader_lease.yml
  deploy/k8s/kustomize/overlays/cloudbeat-eks/configmap_patch.yml
  deploy/k8s/kustomize/overlays/cloudbeat-eks/kustomization.yml
  deploy/k8s/kustomize/overlays/cloudbeat-vanilla/kustomization.yml
  deploy/k8s/kustomize/overlays/test/cloudbeat-ds.yml
  deploy/k8s/kustomize/overlays/test/kustomization.yml
  evaluator/evaluator_mock.go
  fix-tests.patch
  pod.yml
  scripts/make/aws_creds_env.sh
  skaffold.yml
Labels: backport-skip

#247 Fix Debug deployment file
  deploy/k8s/cloudbeat-ds-debug.yml
Labels: backport-skip

#209 Refactor bundle building
  beater/cloudbeat.go
  evaluator/bundle.go
  evaluator/bundle_test.go
  evaluator/opa.go
  go.mod
  go.sum
Labels: backport-skip

#250 Rerun beater interface on reconfiguration
  beater/cloudbeat.go
  beater/cloudbeat_test.go
  beater/validator.go
  beater/validator_test.go
  config/config.go
  evaluator/bundle.go
  evaluator/bundle_test.go
  evaluator/opa.go
  go.mod
  go.sum
  launcher/launcher.go
  launcher/launcher_test.go
  launcher/listener.go
  launcher/listener_test.go
Labels: backport-skip
