Repository elastic/cloudbeat, pull requests merged in 2023-08, with the labels that each got.

#1172 Make gcp benchmark dependencies mockable
  flavors/benchmark/benchmark.go
  flavors/benchmark/gcp.go
  flavors/benchmark/gcp_test.go
  resources/fetching/factory/gcp_factory.go
  resources/fetching/fetchers/gcp/assets_fetcher.go
  resources/fetching/fetchers/gcp/assets_fetcher_test.go
  resources/providers/gcplib/auth/credentials.go
  resources/providers/gcplib/auth/credentials_test.go
  resources/providers/gcplib/auth/mock_config_provider_api.go
  resources/providers/gcplib/identity/identity_provider.go
  resources/providers/gcplib/identity/identity_provider_test.go
  resources/providers/gcplib/identity/mock_provider_getter.go
  resources/providers/gcplib/inventory/mock_inventory_service.go
  resources/providers/gcplib/inventory/mock_provider_initializer_api.go
  resources/providers/gcplib/inventory/mock_service_api.go
  resources/providers/gcplib/inventory/provider.go
Labels: backport-skip

#1178 Update GCP's ECS fields
  dataprovider/providers/cloud/data_provider.go
  dataprovider/providers/cloud/data_provider_test.go
  dataprovider/providers/cloud/option.go
  flavors/benchmark/gcp_test.go
  resources/providers/gcplib/identity/identity_provider.go
  resources/providers/gcplib/identity/identity_provider_test.go
Labels: backport-skip

#1147 Add CNVM premerge test
  .github/workflows/cnvm-ci.yml
  deploy/vulnerability/cloudbeat-vuln-mgmt.yml
  resources/providers/awslib/multi_region.go
  resources/providers/awslib/multi_region_test.go
Labels: backport-skip

#1189 Switching trigger for the CNVM workflow
  .github/workflows/cnvm-ci.yml
  .github/workflows/destroy-environment.yml
  .github/workflows/eks-ci.yml
  .github/workflows/publish-cloudformation.yml
  .github/workflows/publish-test-results.yml
  .github/workflows/test-environment.yml
Labels: backport-skip

#1180 Posture use publisher component
  flavors/client.go
  flavors/posture.go
Labels: backport-skip

#1130 Deployment manager manifest
  .github/workflows/unit-test.yml
  deploy/deployment-manager/README.md
  deploy/deployment-manager/compute_engine.py
  deploy/deployment-manager/compute_engine.py.schema
  deploy/deployment-manager/deploy.sh
  justfile
  resources/providers/gcplib/inventory/provider.go
  version/policy.go
Labels: backport-skip

#1191 [CIS GCP] Add compute instance to fetched resources
  resources/fetching/fetcher.go
  resources/fetching/fetchers/aws/network_fetcher.go
  resources/fetching/fetchers/gcp/assets_fetcher.go
Labels: backport-skip

#1194 [CIS GCP] Get Project id from attached SA
  flavors/benchmark/benchmark.go
  flavors/benchmark/gcp.go
  flavors/benchmark/gcp_test.go
  resources/providers/gcplib/auth/auth_provider.go
  resources/providers/gcplib/auth/credentials.go
  resources/providers/gcplib/auth/credentials_test.go
  resources/providers/gcplib/auth/mock_config_provider_api.go
  resources/providers/gcplib/auth/mock_google_auth_provider_api.go
  resources/providers/gcplib/auth/mock_google_provider_api.go
Labels: backport-skip

#1196 [CIS GCP] Add managed zones type to asset fetcher resources
  resources/fetching/fetcher.go
  resources/fetching/fetchers/gcp/assets_fetcher.go
Labels: backport-skip

#1199 chore: update golang.org/x/net
  go.mod
  go.sum
Labels: backport-skip

#1198 Tag elastic-agent created with CloudFormation
  .github/workflows/publish-cloudformation.yml
  deploy/cloudformation/elastic-agent-ec2-cnvm.yml
  deploy/cloudformation/elastic-agent-ec2-cspm-organization.yml
  deploy/cloudformation/elastic-agent-ec2-cspm.yml
  scripts/publish_cft.sh
Labels: backport-skip

#1183 [GCP] Add project management type
  resources/fetching/fetcher.go
  resources/fetching/fetchers/gcp/assets_fetcher.go
Labels: backport-skip, gcp

#1203 [CloudFormation] Fix replacement of CFT_VERSION on CI
  scripts/publish_cft.sh
Labels: backport-skip

#1204 chore: github.com/elazarl/goproxy/ext
  go.mod
  go.sum
Labels: backport-v8.9.0

#1202 Test CloudFormation agents tags
  deploy/test-environments/fleet_api/src/agents_enrolled.py
  deploy/test-environments/fleet_api/src/install_cnvm_integration.py
  deploy/test-environments/fleet_api/src/install_cspm_integration.py
  deploy/test-environments/fleet_api/src/install_kspm_eks_integration.py
  deploy/test-environments/fleet_api/src/install_kspm_unmanaged_integration.py
  deploy/test-environments/fleet_api/src/state_file_manager.py
Labels: backport-skip

#1206 Add data processing type
  resources/fetching/fetcher.go
  resources/fetching/fetchers/gcp/assets_fetcher.go
Labels: backport-skip, gcp

#1190 AWS functional tests migration
  .github/workflows/k8s-ci.yml
  deploy/kustomize/overlays/cloudbeat-aws/cloudbeat.yml
  justfile
  tests/deploy/k8s-cloudbeat-tests/templates/cloudbeat-test-configmap.yml
  tests/deploy/k8s-cloudbeat-tests/templates/tests/cloudbeat-test-pod.yml
  tests/product/tests/data/aws/aws_ec2_test_cases.py
  tests/product/tests/data/aws/aws_iam_test_cases.py
  tests/product/tests/data/aws/aws_logging_test_cases.py
  tests/product/tests/data/aws/aws_monitoring_test_cases.py
  tests/product/tests/data/aws/aws_rds_test_cases.py
  tests/product/tests/data/aws/aws_s3_test_cases.py
  tests/product/tests/data/aws/aws_vpc_test_cases.py
Labels: backport-skip

#1211 CloudFormation templates have identical signature
  .github/workflows/publish-cloudformation.yml
  scripts/publish_cft.sh
Labels: backport-skip

#1209 Add SQL instance asset type
  resources/fetching/fetchers/gcp/assets_fetcher.go
Labels: backport-skip

#1216 Fix golangci-lint 1.54 breaking changes
  .golangci.yaml
  bin/.golangci-lint-1.54.0.pkg
  bin/golangci-lint
  resources/fetching/factory/k8s_factory.go
  resources/fetching/fetchers/aws/rds_fetcher_test.go
Labels: backport-skip

#1212 [CIS GCP] Add firewall and compute disks asset types
  resources/fetching/fetchers/gcp/assets_fetcher.go
Labels: backport-skip

#1219 Upgrade elastic package binary
  bin/.elastic-package-0.85.0.pkg
  bin/elastic-package
Labels: backport-skip

#1221 comment scheduler
  .github/workflows/periodic-ci.yml
Labels: backport-skip

#1223 chore: update github.com/elazarl/goproxy
  go.mod
  go.sum
Labels: backport-v8.9.0

#1224 [CIS GCP] Add assets to fetcher
  resources/fetching/fetchers/gcp/assets_fetcher.go
Labels: backport-skip

#1217 [AWS Orgs] Tag managment account resources
  flavors/benchmark/aws_org.go
  flavors/benchmark/aws_org_test.go
Labels: backport-skip

#1215 CI: Generate mocks and validate diff
  justfile
  resources/providers/gcplib/auth/credentials_test.go
  resources/providers/gcplib/auth/mock_google_provider_api.go
  scripts/validate-mocks.sh
Labels: backport-skip

#1229 Bump csp policies version
  resources/fetching/fetchers/gcp/assets_fetcher.go
  version/policy.go
Labels: backport-skip

#1176 [CNVM] Index updates
  vulnerability/events_creator.go
Labels: backport-skip

#1230 Update Beats dependency and elastic-agent-client
  go.mod
  go.sum
Labels: backport-skip

#1233 CloudFormation Integration Test
  .github/workflows/cloudformation-ci.yml
Labels: backport-skip

#1244 skip agent test
  .github/workflows/k8s-ci.yml
Labels: backport-skip

#1235 [Release] Update version to 8.9.2
  version/version.go
Labels: team:automation, release

#1234 Extract resource id
  resources/fetching/fetchers/gcp/assets_fetcher.go
Labels: backport-skip, gcp

#1246 unskip agent tests
  .github/workflows/cloudbeat-ci.yml
  .github/workflows/k8s-ci.yml
  tests/commonlib/utils.py
  tests/deploy/sa-agent-pytest.yml
Labels: backport-skip, automation

#1268 chore: update dpes
  go.mod
  go.sum
Labels: backport-skip

#1261 Update hermit env var version to 8.11.0
  bin/hermit.hcl
Labels: backport-skip

#1271 [Create Environment] Add role to EKS cluster for post-provisioning access
  .github/workflows/test-environment.yml
  deploy/cloud/README.md
  deploy/cloud/modules/provision-eks-cluster/eks-cluster.tf
  deploy/cloud/modules/provision-eks-cluster/main.tf
  deploy/test-environments/delete_env.sh
  dev-docs/Cloud-Env-Testing.md
Labels: backport-skip

#1285 [AWS Orgs] CloudFormation: Validate OrganizationalUnitIds
  deploy/cloudformation/elastic-agent-ec2-cspm-organization.yml
Labels: backport-v8.10.0

#1272 Use gotestsum in CI
  .github/workflows/unit-test.yml
  go.mod
  go.sum
Labels: backport-skip

#1274 ECS common data mapping
  dataprovider/enrich.go
  dataprovider/enrich_test.go
  dataprovider/mock_elastic_common_data_provider.go
  evaluator/opa_test.go
  resources/fetching/factory/aws_factory.go
  resources/fetching/factory/aws_factory_test.go
  resources/fetching/fetcher.go
  resources/fetching/fetchers/aws/ecr_fetcher.go
  resources/fetching/fetchers/aws/elb_fetcher.go
  resources/fetching/fetchers/aws/iam_fetcher.go
  resources/fetching/fetchers/aws/kms_fetcher.go
  resources/fetching/fetchers/aws/logging_fetcher.go
  resources/fetching/fetchers/aws/logging_fetcher_test.go
  resources/fetching/fetchers/aws/monitoring_fetcher.go
  resources/fetching/fetchers/aws/network_fetcher.go
  resources/fetching/fetchers/aws/network_fetcher_test.go
  resources/fetching/fetchers/aws/rds_fetcher.go
  resources/fetching/fetchers/aws/s3_fetcher.go
  resources/fetching/fetchers/gcp/assets_fetcher.go
  resources/fetching/fetchers/gcp/monitoring_fetcher.go
  resources/fetching/fetchers/k8s/file_system_fetcher.go
  resources/fetching/fetchers/k8s/file_system_fetcher_test.go
  resources/fetching/fetchers/k8s/kube_provider.go
  resources/fetching/fetchers/k8s/process_fetcher.go
  resources/fetching/fetchers/k8s/process_fetcher_test.go
  resources/fetching/mock_resource.go
  resources/fetching/registry/registry_test.go
  transformer/events_creator.go
Labels: backport-skip
