Repository elastic/cloudbeat, pull requests merged in 2023-10, with the labels that each got.

#1355 [GCP] Add project policies fetcher
  resources/fetching/fetcher.go
  resources/fetching/fetchers/gcp/assets_fetcher.go
  resources/fetching/fetchers/gcp/policies_fetcher.go
  resources/fetching/fetchers/gcp/policies_fetcher_test.go
  resources/fetching/preset/gcp_preset.go
  resources/providers/gcplib/inventory/asset.go
  resources/providers/gcplib/inventory/mock_service_api.go
  resources/providers/gcplib/inventory/provider.go
  resources/providers/gcplib/inventory/provider_test.go
Labels: backport-skip, gcp

#1373 [GCP] skip gcp ci
  .github/workflows/gcp-ci.yml
Labels: backport-skip

#1368 Azure: ARM: Deploy Role Assignment in subscription level
  deploy/azure/README.md
  deploy/azure/azureARMTemplate.json
Labels: backport-skip

#1370 Azure: Fetch disk type
  resources/fetching/fetcher.go
  resources/fetching/fetchers/azure/assets_fetcher.go
  resources/fetching/fetchers/azure/assets_fetcher_test.go
  resources/providers/azurelib/inventory/asset.go
Labels: backport-skip

#1372 Support Azure activity logs
  flavors/benchmark/azure_test.go
  resources/fetching/fetcher.go
  resources/fetching/fetchers/azure/activity_log_alerts_fetcher.go
  resources/fetching/fetchers/azure/activity_log_alerts_fetcher_test.go
  resources/fetching/preset/azure_factory.go
  resources/providers/azurelib/inventory/asset.go
  resources/providers/azurelib/inventory/provider.go
Labels: backport-skip

#1376 [Azure] Add websites asset type
  resources/fetching/fetcher.go
  resources/fetching/fetchers/azure/assets_fetcher.go
  resources/fetching/fetchers/azure/assets_fetcher_test.go
  resources/providers/azurelib/inventory/asset.go
Labels: backport-skip, CIS Azure

#1374 [Azure] Add resource types to the assets fetcher
  resources/fetching/fetcher.go
  resources/fetching/fetchers/azure/assets_fetcher.go
  resources/fetching/fetchers/azure/assets_fetcher_test.go
  resources/providers/azurelib/inventory/asset.go
Labels: backport-skip

#1382 Azure: Fix map
  resources/fetching/fetcher.go
  resources/fetching/fetchers/azure/assets_fetcher.go
  resources/providers/azurelib/inventory/asset.go
Labels: backport-skip

#1385 Azure: Fetch bastions
  flavors/benchmark/azure_test.go
  resources/fetching/fetcher.go
  resources/fetching/fetchers/azure/activity_log_alerts_fetcher.go
  resources/fetching/fetchers/azure/activity_log_alerts_fetcher_test.go
  resources/fetching/fetchers/azure/assets_fetcher.go
  resources/fetching/fetchers/azure/batch_fetcher.go
  resources/fetching/fetchers/azure/batch_fetcher_test.go
  resources/fetching/preset/azure_factory.go
  resources/providers/azurelib/inventory/asset.go
Labels: backport-skip

#1379 Support additional Azure resources
  resources/fetching/fetcher.go
  resources/fetching/fetchers/azure/assets_fetcher.go
  resources/fetching/fetchers/azure/assets_fetcher_test.go
  resources/providers/azurelib/inventory/asset.go
Labels: backport-skip

#1386 Support vault resource
  resources/fetching/fetcher.go
  resources/fetching/fetchers/azure/assets_fetcher.go
  resources/fetching/fetchers/azure/assets_fetcher_test.go
  resources/providers/azurelib/inventory/asset.go
Labels: backport-skip

#1387 Bump version to 8.12
  .mergify.yml
  version/version.go
Labels: backport-skip

#1392 CIS Azure: Fix Type and SubType fields
  resources/fetching/fetcher.go
  resources/fetching/fetchers/azure/assets_fetcher.go
  resources/fetching/fetchers/azure/assets_fetcher_test.go
  resources/fetching/fetchers/azure/batch_fetcher.go
  resources/fetching/fetchers/azure/batch_fetcher_test.go
  resources/providers/azurelib/inventory/asset.go
Labels: backport-v8.11.0

#1397 Azure: ARM: Link to fixed 8.11 install script
  deploy/azure/azureARMTemplate.json
Labels: backport-skip

#1396 Azure: Populate cloud.account.name with DisplayName
  resources/fetching/fetchers/azure/assets_fetcher.go
  resources/fetching/fetchers/azure/assets_fetcher_test.go
  resources/fetching/fetchers/azure/batch_fetcher.go
  resources/fetching/fetchers/azure/batch_fetcher_test.go
  resources/providers/azurelib/inventory/provider.go
Labels: backport-v8.11.0

#1400 Azure: Batch Fetcher: Group resources by subscription IDs and types
  resources/fetching/fetchers/azure/batch_fetcher.go
  resources/fetching/fetchers/azure/batch_fetcher_test.go
Labels: backport-skip

#1402 [Release] Update version to 8.10.4
  version/version.go
Labels: team:automation, release

#1408 go.mod: Bump cloud.google.com deps
  go.mod
  go.sum
Labels: backport-v8.11.0

#1407 CODEOWNERS: Remove csp-ops/automation ownership
  .github/CODEOWNERS
Labels: backport-skip

#1388 Bump cloudbeat version in hermit
  bin/hermit.hcl
Labels: backport-skip

#1425 Dependabot: Run for all go modules
  .github/dependabot.yml
Labels: backport-skip, automation, technical debt

#1434 Dependabot: Create groups
  .github/dependabot.yml
Labels: backport-skip, automation, technical debt

#1435 Dependabot: Fix group syntax, add label, bump limit
  .github/dependabot.yml
Labels: backport-skip, automation, dependency, technical debt

#1422 Add elastic resource tags in terraform/actions for testing env
  .github/workflows/test-environment.yml
  deploy/test-environments/main.tf
  deploy/test-environments/variables.tf
Labels: backport-skip

#1399 Remove context from structs
  .golangci.yaml
  flavors/flavors.go
  resources/fetching/fetchers/azure/assets_fetcher.go
  resources/fetching/fetchers/azure/assets_fetcher_test.go
  resources/fetching/fetchers/azure/batch_fetcher.go
  resources/fetching/fetchers/azure/batch_fetcher_test.go
  resources/fetching/fetchers/gcp/assets_fetcher.go
  resources/fetching/fetchers/gcp/assets_fetcher_test.go
  resources/fetching/fetchers/gcp/log_sink_fetcher.go
  resources/fetching/fetchers/gcp/monitoring_fetcher.go
  resources/fetching/fetchers/gcp/monitoring_fetcher_test.go
  resources/fetching/fetchers/gcp/policies_fetcher.go
  resources/fetching/fetchers/gcp/service_usage_fetcher.go
  resources/fetching/manager/manager.go
  resources/fetching/manager/manager_test.go
  resources/providers/awslib/ec2/provider_test.go
  resources/providers/azurelib/inventory/mock_service_api.go
  resources/providers/azurelib/inventory/provider.go
  resources/providers/azurelib/inventory/provider_test.go
  resources/providers/gcplib/inventory/mock_service_api.go
  resources/providers/gcplib/inventory/provider.go
  resources/providers/gcplib/inventory/provider_test.go
Labels: backport-skip, technical debt

#1438 go.mod: Update beats and elastic libraries
  .github/dependabot.yml
  go.mod
  go.sum
Labels: backport-v8.11.0

#1436 Remove preview version from GCP
  deploy/cloud/data/package_policy_cspm_gcp.json
Labels: backport-v8.11.0

#1427 CloudFormation: Upload to link parametrized only by version
  .github/workflows/publish-cloudformation.yml
  .pre-commit-config.yaml
  scripts/publish_cft.sh
Labels: backport-v8.11.0

#1450 CloudFormation CI: Fix script path typo
  .github/workflows/publish-cloudformation.yml
Labels: backport-skip

#1409 launcher: Clean up package
  beater/beater.go
  launcher/launcher.go
  launcher/launcher_test.go
Labels: backport-skip, technical debt

#1456 Bump open-policy-agent/opa to v0.57.1
  go.mod
  go.sum
Labels: backport-skip

#1447 Fix QA Environment GCP Deployment
  deploy/cloud/data/package_policy_cspm_gcp.json
Labels: backport-v8.11.0

#1468 Azure add mapping for SKU property
  resources/providers/azurelib/inventory/provider.go
  resources/providers/azurelib/inventory/provider_test.go
Labels: 8.11 candidate, backport-v8.11.0

#1476 Azure remove activity logs from single fetcher
  resources/fetching/fetchers/azure/assets_fetcher.go
  resources/fetching/fetchers/azure/assets_fetcher_test.go
Labels: 8.11 candidate, backport-v8.11.0

#1495 Fix bump-golang pipeline
  .ci/bump-golang.yml
  .github/workflows/bump-golang.yml
  .go-version
  bin/.go-1.20.10.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: backport-skip

#1501 Dependabot: Run only on Mondays
  .github/dependabot.yml
Labels: backport-skip, dependency
