Repository elastic/cloudbeat, pull requests merged in 2023-06, with the labels that each got.

#1020 Remove makefile
  .buildkite/scripts/generate_notice.py
  .buildkite/scripts/package.sh
  .github/workflows/cloudbeat-ci.yml
  .github/workflows/eks-ci.yml
  .github/workflows/k8s-ci.yml
  .github/workflows/periodic-ci.yml
  .pre-commit-config.yaml
  Makefile
  dev-tools/packaging/docker/elastic-agent/build.sh
  docs/fields.asciidoc
Labels: backport-skip

#1024 Implement CIS AWS functional tests for rules 2.1.5, 2.3.3
  tests/product/tests/data/aws/aws_rds_test_cases.py
  tests/product/tests/data/aws/aws_s3_test_cases.py
Labels: backport-skip

#1023 Fix makefile leftovers
  .buildkite/scripts/package.sh
  .ci/scripts/ecr-images.sh
  .github/workflows/eks-ci.yml
Labels: backport-skip

#1027 Allure report summary comment
  .ci/scripts/allure-report-summary.sh
  .github/workflows/publish-test-results.yml
Labels: backport-skip

#1029 Format pipeline branch filter the buildkite way
  catalog-info.yaml
Labels: backport-skip

#1025 Generating manifests using Fleet API
  .pre-commit-config.yaml
  deploy/cloud/data/agent_policy_cspm_aws.json
  deploy/cloud/data/package_policy_cspm_aws.json
  deploy/test-environments/fleet_api/README.md
  deploy/test-environments/fleet_api/pyproject.toml
  deploy/test-environments/fleet_api/src/api/agent_policy_api.py
  deploy/test-environments/fleet_api/src/api/base_call_api.py
  deploy/test-environments/fleet_api/src/api/common_api.py
  deploy/test-environments/fleet_api/src/api/package_policy_api.py
  deploy/test-environments/fleet_api/src/configuration_fleet.py
  deploy/test-environments/fleet_api/src/install_cspm_integration.py
  deploy/test-environments/fleet_api/src/install_kspm_eks_integration.py
  deploy/test-environments/fleet_api/src/install_kspm_unmanaged_integration.py
  deploy/test-environments/fleet_api/src/purge_integrations.py
  deploy/test-environments/fleet_api/src/utils.py
Labels: backport-skip

#1007 CNVM: Adding unit tests
  vulnerability/fetcher.go
  vulnerability/fetcher_test.go
  vulnerability/mock_replicator_provider.go
  vulnerability/mock_runner_interface.go
  vulnerability/mock_snapshot_provider.go
  vulnerability/mock_worker_provider.go
  vulnerability/replicator.go
  vulnerability/replicator_test.go
  vulnerability/runner_test.go
  vulnerability/scanner.go
  vulnerability/scanner_test.go
  vulnerability/verifier.go
  vulnerability/verifier_test.go
  vulnerability/worker.go
  vulnerability/worker_test.go
Labels: backport-skip

#1032 Fix data.go unit test race
  resources/fetchersManager/data_test.go
Labels: backport-skip

#1035 Bump trivy 0.42.1
  go.mod
  go.sum
Labels: backport-skip

#949 Move shutdown grace period to Launcher
  flavors/flavors.go
  flavors/posture.go
  launcher/launcher.go
  launcher/launcher_test.go
  pipeline/pipeline.go
  pipeline/pipeline_test.go
  resources/fetchersManager/data.go
  resources/fetchersManager/data_test.go
Labels: backport-skip

#1046 update runner image version
  .github/workflows/k8s-ci.yml
Labels: backport-skip

#1043 Move docker files to deploy folder
  .github/workflows/cloudbeat-ci.yml
  .github/workflows/eks-ci.yml
  .github/workflows/k8s-ci.yml
  .github/workflows/periodic-ci.yml
  deploy/Dockerfile
  deploy/Dockerfile.debug
  justfile
Labels: backport-skip

#1041 Override vulnerability management scanner logger
  flavors/vulnerability.go
Labels: backport-skip

#1044 add sanity check test suite
  tests/commonlib/elastic_wrapper.py
  tests/commonlib/utils.py
  tests/configuration.py
  tests/conftest.py
  tests/integration/tests/test_cloudbeat_integration.py
  tests/integration/tests/test_sanity_checks.py
  tests/integration/tests/test_standalone_agent_integration.py
  tests/pyproject.toml
Labels: backport-skip

#1054 update unit-tests ci timeout
  .github/workflows/cloudbeat-ci.yml
  .github/workflows/eks-ci.yml
  .github/workflows/k8s-ci.yml
  .github/workflows/packaging.yml
  .github/workflows/periodic-ci.yml
  .github/workflows/publish-artifacts.yml
  .github/workflows/publish-test-results.yml
  .github/workflows/unit-test.yml
Labels: backport-v8.8.0

#1052 Fix justfile build-cloudbeat
  justfile
Labels: backport-skip

#1056 Improve allure report summary
  .ci/scripts/allure-report-summary.sh
  .github/workflows/publish-cloudformation.yml
  .github/workflows/publish-test-results.yml
Labels: backport-skip

#1060 Update cloudbeat to version 8.10.0
  .mergify.yml
  version/version.go
Labels: backport-skip

#1058 add sanity checks action and update mask value
  .github/workflows/test-environment.yml
  dev-docs/sanity-workflow.md
  tests/integration/tests/test_sanity_checks.py
Labels: backport-skip

#1062 opa_test: Make sure bundle.tar.gz exists before running tests
  evaluator/opa_test.go
  go.mod
  go.sum
Labels: backport-skip

#1061 Re-organize fetcher directory structure
  dataprovider/providers/k8s/data_provider.go
  dataprovider/providers/k8s/data_provider_test.go
  flavors/posture.go
  include/include.go
  resources/fetchersManager/registry/mock_fetchers_registry.go
  resources/fetching/condition/is_leader.go
  resources/fetching/factory/aws_factory.go
  resources/fetching/factory/eks_factory.go
  resources/fetching/factory/factory.go
  resources/fetching/factory/factory_test.go
  resources/fetching/factory/k8s_factory.go
  resources/fetching/fetcher.go
  resources/fetching/fetchers/ecr_fetcher.go
  resources/fetching/fetchers/ecr_fetcher_test.go
  resources/fetching/fetchers/elb_fetcher.go
  resources/fetching/fetchers/elb_fetcher_test.go
  resources/fetching/fetchers/file_system_fetcher.go
  resources/fetching/fetchers/file_system_fetcher_test.go
  resources/fetching/fetchers/glob_matching.go
  resources/fetching/fetchers/glob_matching_test.go
  resources/fetching/fetchers/iam_fetcher.go
  resources/fetching/fetchers/iam_fetcher_test.go
  resources/fetching/fetchers/kms_fetcher.go
  resources/fetching/fetchers/kms_fetcher_test.go
  resources/fetching/fetchers/kube_fetcher.go
  resources/fetching/fetchers/kube_fetcher_test.go
  resources/fetching/fetchers/kube_provider.go
  resources/fetching/fetchers/logging_fetcher.go
  resources/fetching/fetchers/logging_fetcher_test.go
  resources/fetching/fetchers/monitoring_fetcher.go
  resources/fetching/fetchers/monitoring_fetcher_test.go
  resources/fetching/fetchers/network_fetcher.go
  resources/fetching/fetchers/network_fetcher_test.go
  resources/fetching/fetchers/process_fetcher.go
  resources/fetching/fetchers/process_fetcher_test.go
  resources/fetching/fetchers/rds_fetcher.go
  resources/fetching/fetchers/rds_fetcher_test.go
  resources/fetching/fetchers/s3_fetcher.go
  resources/fetching/fetchers/s3_fetcher_test.go
  resources/fetching/manager/manager.go
  resources/fetching/manager/manager_test.go
  resources/fetching/registry/mock_registry.go
  resources/fetching/registry/registry.go
  resources/fetching/registry/registry_test.go
  transformer/events_creator_test.go
  vulnerability/fetcher_test.go
  vulnerability/replicator_test.go
  vulnerability/worker_test.go
Labels: backport-skip

#1045 [AWS Orgs] Add CloudFormation for IAM roles
  .github/workflows/publish-cloudformation.yml
  .pre-commit-config.yaml
  deploy/cloudformation/ec2-types.yml
  deploy/cloudformation/organization.yml
Labels: backport-skip

#1068 Update hermit env var version to 8.10.0
  bin/hermit.hcl
Labels: backport-skip

#1084 Skip AWS post-merge tests
  .github/workflows/k8s-ci.yml
Labels: backport-skip

#1070 [CNVM] Use amazon linux 2023 ami in CloudFormation
  deploy/cloudformation/elastic-agent-ec2.yml
Labels: backport-skip

#1082 [CI] Update golangci linter step to avoid timeout
  .github/workflows/unit-test.yml
Labels: backport-skip

#1091 golangci-lint: Enable more linters
  .golangci.yaml
  bin/.golangci-lint-1.53.3.pkg
  bin/golangci-lint
  dataprovider/providers/aws/data_provider_test.go
  deploy/cloudformation/gomain.go
  launcher/errors.go
  main_test.go
  resources/fetching/factory/factory_test.go
  resources/fetching/fetchers/ecr_fetcher.go
  resources/fetching/fetchers/ecr_fetcher_test.go
  resources/fetching/fetchers/elb_fetcher.go
  resources/fetching/fetchers/elb_fetcher_test.go
  resources/fetching/fetchers/file_system_fetcher.go
  resources/fetching/fetchers/iam_fetcher_test.go
  resources/fetching/fetchers/kms_fetcher.go
  resources/fetching/fetchers/kms_fetcher_test.go
  resources/fetching/fetchers/logging_fetcher_test.go
  resources/fetching/fetchers/network_fetcher.go
  resources/fetching/fetchers/process_fetcher.go
  resources/fetching/fetchers/process_fetcher_test.go
  resources/fetching/manager/manager.go
  resources/providers/aws_cis/logging/logging.go
  resources/providers/aws_cis/monitoring/monitoring.go
  resources/providers/awslib/aws.go
  resources/providers/awslib/config_provider_test.go
  resources/providers/awslib/configservice/provider.go
  resources/providers/awslib/iam/account_alias_test.go
  resources/providers/awslib/iam/root_account.go
  resources/providers/awslib/iam/server_cerfiticates.go
  resources/providers/awslib/iam/server_certificates_test.go
  resources/providers/awslib/kms/provider.go
  resources/providers/awslib/rds/provider.go
  vulnerability/events_creator.go
  vulnerability/verifier.go
Labels: backport-skip

#1087 Use beat.Beater interface to avoid warning
  flavors/posture.go
  flavors/vulnerability.go
Labels: backport-skip

#1080 [Sanity Job] Update package policy templates to 1.2.13 and adding install integration package to the latest version.
  deploy/cloud/data/package_policy_cspm_aws.json
  deploy/cloud/data/package_policy_eks.json
  deploy/cloud/data/package_policy_vanilla.json
  deploy/test-environments/fleet_api/src/api/common_api.py
  deploy/test-environments/fleet_api/src/install_cspm_integration.py
  deploy/test-environments/fleet_api/src/install_kspm_eks_integration.py
  deploy/test-environments/fleet_api/src/install_kspm_unmanaged_integration.py
Labels: backport-skip

#1092 Simplify identity provider
  .pre-commit-config.yaml
  flavors/common.go
  flavors/posture.go
  resources/fetching/factory/factory.go
  resources/fetching/factory/factory_test.go
  resources/fetching/fetchers/elb_fetcher_test.go
  resources/fetching/fetchers/logging_fetcher_test.go
  resources/providers/awslib/identity_provider.go
  resources/providers/awslib/mock_identity_provider_getter.go
Labels: backport-skip

#1094 Upgrade OPA version
  bin/.opa-0.53.1.pkg
  bin/opa
  go.mod
  go.sum
Labels: backport-skip

#1076 [CNVM] Sanity test
  .github/workflows/test-environment.yml
  deploy/cloud/data/agent_policy_cnvm_aws.json
  deploy/cloud/data/package_policy_cnvm_aws.json
  deploy/cloud/modules/provision-eks-cluster/eks-cluster.tf
  deploy/cloudformation/.gitignore
  deploy/cloudformation/README.md
  deploy/cloudformation/config.go
  deploy/test-environments/fleet_api/README.md
  deploy/test-environments/fleet_api/src/api/common_api.py
  deploy/test-environments/fleet_api/src/api/package_policy_api.py
  deploy/test-environments/fleet_api/src/configuration_fleet.py
  deploy/test-environments/fleet_api/src/data/cspm-linux.j2
  deploy/test-environments/fleet_api/src/install_cnvm_integration.py
  deploy/test-environments/fleet_api/src/install_cspm_integration.py
Labels: backport-skip

#1093 Refactor benchmarks
  flavors/benchmark/aws.go
  flavors/benchmark/benchmark.go
  flavors/benchmark/benchmark_test.go
  flavors/benchmark/eks.go
  flavors/benchmark/k8s.go
  flavors/benchmark/mock_benchmark.go
  flavors/common.go
  flavors/posture.go
  go.mod
  go.sum
  resources/fetching/factory/aws_factory.go
  resources/fetching/factory/factory.go
  resources/fetching/fetchers/ecr_fetcher_test.go
  resources/fetching/fetchers/elb_fetcher_test.go
  resources/providers/awslib/config_provider.go
  resources/providers/awslib/identity_provider.go
  resources/providers/kubernetes_provider.go
  resources/providers/mock_kubernetes_client_getter_api.go
Labels: backport-skip

#1064 [Release] Update version to 8.8.3
  version/version.go
Labels: team:automation, release

#1095 Delete terraform environment script
  deploy/test-environments/delete_env.sh
Labels: backport-skip
