Repository elastic/cloudbeat, pull requests merged in 2023-07, with the labels that each got.

#1100 [Sanity Jobs] Added tags support for eks cluster
  deploy/cloud/modules/provision-eks-cluster/eks-cluster.tf
  deploy/cloud/modules/provision-eks-cluster/variables.tf
  deploy/test-environments/main.tf
Labels: backport-skip

#1101 Benchmarks: add some missing tests
  flavors/benchmark/aws.go
  flavors/benchmark/benchmark.go
  flavors/benchmark/benchmark_test.go
  flavors/benchmark/eks.go
  flavors/benchmark/k8s.go
  resources/fetching/factory/aws_factory.go
  resources/fetching/factory/eks_factory.go
  resources/fetching/factory/k8s_factory.go
Labels: backport-skip

#1078 [CIS GCP] Add auth methods and new input type
  beater/validator_test.go
  config/benchmark.go
  config/config.go
  config/config_test.go
  deploy/gcp/cloudbeat-gcp.yml
  go.mod
  go.sum
  resources/providers/gcplib/auth/credentials.go
  resources/providers/gcplib/auth/credentials_test.go
Labels: backport-skip

#1103 events_creator_test: Fix JSON parse error
  transformer/events_creator_test.go
  transformer/opa_results.json
Labels: backport-skip

#1104 Enable logging for all tests
  beater/beater_test.go
  beater/validator_test.go
  config/config_test.go
  dataprovider/providers/aws/data_provider_test.go
  dataprovider/providers/k8s/data_provider_test.go
  evaluator/opa_test.go
  flavors/benchmark/benchmark_test.go
  launcher/launcher_test.go
  launcher/listener_test.go
  pipeline/pipeline_test.go
  processor/add_cluster_id/add_cluster_id_test.go
  processor/add_cluster_id/cluster_helper_test.go
  resources/fetching/fetchers/ecr_fetcher_test.go
  resources/fetching/fetchers/elb_fetcher_test.go
  resources/fetching/fetchers/file_system_fetcher_test.go
  resources/fetching/fetchers/iam_fetcher_test.go
  resources/fetching/fetchers/kms_fetcher_test.go
  resources/fetching/fetchers/kube_fetcher_test.go
  resources/fetching/fetchers/monitoring_fetcher_test.go
  resources/fetching/fetchers/process_fetcher_test.go
  resources/fetching/fetchers/rds_fetcher_test.go
  resources/fetching/fetchers/s3_fetcher_test.go
  resources/fetching/manager/manager_test.go
  resources/fetching/registry/registry_test.go
  resources/providers/aws_cis/logging/provider_test.go
  resources/providers/aws_cis/monitoring/monitoring_test.go
  resources/providers/awslib/cloudtrail/provider_test.go
  resources/providers/awslib/cloudwatch/logs/provider_test.go
  resources/providers/awslib/cloudwatch/provider_test.go
  resources/providers/awslib/config_provider_test.go
  resources/providers/awslib/configservice/provider_test.go
  resources/providers/awslib/iam/access_analyzer_test.go
  resources/providers/awslib/iam/account_alias_test.go
  resources/providers/awslib/iam/policy_test.go
  resources/providers/awslib/iam/server_certificates_test.go
  resources/providers/awslib/iam/user_test.go
  resources/providers/awslib/kms/provider_test.go
  resources/providers/awslib/multi_region_test.go
  resources/providers/awslib/rds/provider_test.go
  resources/providers/awslib/s3/provider_test.go
  resources/providers/awslib/securityhub/provider_test.go
  resources/providers/awslib/sns/provider_test.go
  resources/providers/cluster_provider_test.go
  resources/providers/kubernetes_cluster_name_provider_test.go
  resources/utils/testhelper/helper.go
  transformer/events_creator_test.go
  uniqueness/leaderelection_test.go
  vulnerability/cleaner_test.go
  vulnerability/events_creator_test.go
  vulnerability/fetcher_test.go
  vulnerability/replicator_test.go
  vulnerability/runner_test.go
  vulnerability/scanner_test.go
  vulnerability/verifier_test.go
  vulnerability/worker_test.go
Labels: backport-skip

#1072 [AWS Orgs] Add config option
  config/config.go
  config/config_test.go
  flavors/benchmark/aws.go
  flavors/benchmark/benchmark_test.go
  flavors/benchmark/eks.go
  flavors/common.go
  resources/providers/cluster_provider.go
  resources/providers/cluster_provider_test.go
  resources/providers/gcplib/auth/credentials.go
  resources/providers/gcplib/auth/credentials_test.go
  vulnerability/worker.go
Labels: backport-skip

#1106 add AWS tags for CNVM deployment
  .github/workflows/test-environment.yml
  deploy/test-environments/fleet_api/README.md
  justfile
  scripts/add_cnvm_tags.sh
Labels: backport-skip

#1099 Vuln mgmt async providers ctx fix
  vulnerability/events_creator.go
  vulnerability/events_creator_test.go
  vulnerability/fetcher.go
  vulnerability/fetcher_test.go
  vulnerability/replicator.go
  vulnerability/replicator_test.go
  vulnerability/scanner.go
  vulnerability/verifier.go
  vulnerability/verifier_test.go
  vulnerability/worker.go
Labels: backport-v8.9.0

#1107 Add CNVM to our Readme
  README.md
  bin/README.hermit.md
  tests/README.md
Labels: backport-skip

#1113 Remove unused folder
  data/meta.json
  skaffold.yml
Labels: backport-skip

#1049 CloudFormation instance type support for all regions
  deploy/cloudformation/elastic-agent-ec2.yml
Labels: backport-skip

#1119 [Sanity] Assert that all agents are enrolled
  .github/workflows/test-environment.yml
  deploy/test-environments/fleet_api/src/agents_enrolled.py
  deploy/test-environments/fleet_api/src/api/agent_policy_api.py
  deploy/test-environments/fleet_api/src/api/package_policy_api.py
  deploy/test-environments/fleet_api/src/configuration_fleet.py
  deploy/test-environments/fleet_api/src/install_cnvm_integration.py
  deploy/test-environments/fleet_api/src/install_cspm_integration.py
  deploy/test-environments/fleet_api/src/install_kspm_eks_integration.py
  deploy/test-environments/fleet_api/src/install_kspm_unmanaged_integration.py
  deploy/test-environments/fleet_api/src/purge_integrations.py
  deploy/test-environments/fleet_api/src/state_file_manager.py
  deploy/test-environments/fleet_api/src/utils.py
Labels: backport-skip

#1123 Pre-commit hook cfn-python-lint to scan all templates
  .pre-commit-config.yaml
  deploy/cloudformation/ec2-types.yml
Labels: backport-skip

#1127 Convert to test suites
  vulnerability/fetcher_test.go
  vulnerability/replicator_test.go
  vulnerability/verifier_test.go
Labels: backport-skip

#1126 Conditionally run sanity tests
  .github/workflows/test-environment.yml
  dev-docs/sanity-workflow.md
Labels: backport-skip, automation

#1110 Find vulnerabilities sanity test
  tests/commonlib/elastic_wrapper.py
  tests/commonlib/io_utils.py
  tests/commonlib/utils.py
  tests/configuration.py
  tests/conftest.py
  tests/integration/tests/test_cloudbeat_integration.py
  tests/integration/tests/test_sanity_checks.py
  tests/integration/tests/test_standalone_agent_integration.py
  tests/product/tests/test_aws_ec2_rules.py
  tests/product/tests/test_aws_iam_management_rules.py
  tests/product/tests/test_aws_logging_rules.py
  tests/product/tests/test_aws_monitoring_rules.py
  tests/product/tests/test_aws_rds_rules.py
  tests/product/tests/test_aws_s3_service_rules.py
  tests/product/tests/test_aws_vpc_rules.py
  tests/product/tests/test_eks_file_system_rules.py
  tests/product/tests/test_eks_k8s_objects_rules.py
  tests/product/tests/test_eks_managed_services_rules.py
  tests/product/tests/test_eks_process_kubelet_rules.py
  tests/product/tests/test_file_system_rules.py
  tests/product/tests/test_k8s_objects_rules.py
  tests/product/tests/test_process_api_server_rules.py
  tests/product/tests/test_process_controller_manager_rules.py
  tests/product/tests/test_process_etcd_rules.py
  tests/product/tests/test_process_kubelet_rules.py
  tests/product/tests/test_process_scheduler_rules.py
Labels: backport-skip

#1135 Update ec-API-Key bullet in sanity workflow doc
  dev-docs/sanity-workflow.md
Labels: backport-skip, Team:Cloud Security

#1134 Improving Cloud Deployment test env docs
  .github/workflows/test-environment.yml
  README.md
  deploy/test-environments/delete_env.sh
  deploy/test-environments/variables.tf
  dev-docs/Cloud-Env-Testing.md
  dev-docs/sanity-workflow.md
  justfile
  tests/README.md
Labels: backport-skip, Team:Cloud Security, technical debt

#1081 Enhance CNVM index
  resources/providers/awslib/ec2/ec2_instance.go
  vulnerability/events_creator.go
Labels: backport-skip

#1112 Move fetchers to folders
  .golangci.yaml
  dataprovider/providers/k8s/data_provider.go
  dataprovider/providers/k8s/data_provider_test.go
  resources/fetching/factory/aws_factory.go
  resources/fetching/factory/eks_factory.go
  resources/fetching/factory/k8s_factory.go
  resources/fetching/fetchers/aws/ecr_fetcher.go
  resources/fetching/fetchers/aws/ecr_fetcher_test.go
  resources/fetching/fetchers/aws/elb_fetcher.go
  resources/fetching/fetchers/aws/elb_fetcher_test.go
  resources/fetching/fetchers/aws/iam_fetcher.go
  resources/fetching/fetchers/aws/iam_fetcher_test.go
  resources/fetching/fetchers/aws/kms_fetcher.go
  resources/fetching/fetchers/aws/kms_fetcher_test.go
  resources/fetching/fetchers/aws/logging_fetcher.go
  resources/fetching/fetchers/aws/logging_fetcher_test.go
  resources/fetching/fetchers/aws/monitoring_fetcher.go
  resources/fetching/fetchers/aws/monitoring_fetcher_test.go
  resources/fetching/fetchers/aws/network_fetcher.go
  resources/fetching/fetchers/aws/network_fetcher_test.go
  resources/fetching/fetchers/aws/rds_fetcher.go
  resources/fetching/fetchers/aws/rds_fetcher_test.go
  resources/fetching/fetchers/aws/s3_fetcher.go
  resources/fetching/fetchers/aws/s3_fetcher_test.go
  resources/fetching/fetchers/k8s/file_system_fetcher.go
  resources/fetching/fetchers/k8s/file_system_fetcher_test.go
  resources/fetching/fetchers/k8s/glob_matching.go
  resources/fetching/fetchers/k8s/glob_matching_test.go
  resources/fetching/fetchers/k8s/kube_fetcher.go
  resources/fetching/fetchers/k8s/kube_fetcher_test.go
  resources/fetching/fetchers/k8s/kube_provider.go
  resources/fetching/fetchers/k8s/process_fetcher.go
  resources/fetching/fetchers/k8s/process_fetcher_test.go
  transformer/events_creator_test.go
Labels: backport-skip

#1096 Add GCP cloud assets api utility
  dataprovider/providers/gcp/data_provider.go
  dataprovider/providers/gcp/mock_option.go
  dataprovider/providers/gcp/option.go
  deploy/gcp/cloudbeat-gcp.yml
  flavors/benchmark/benchmark.go
  flavors/benchmark/benchmark_test.go
  flavors/benchmark/gcp.go
  go.mod
  go.sum
  resources/fetching/factory/gcp_factory.go
  resources/fetching/fetchers/gcp/assets_fetcher.go
  resources/fetching/fetchers/gcp/assets_fetcher_test.go
  resources/providers/gcplib/auth/credentials.go
  resources/providers/gcplib/inventory/mock_inventory_service.go
  resources/providers/gcplib/inventory/mock_iterator.go
  resources/providers/gcplib/inventory/provider.go
  resources/providers/gcplib/inventory/provider_test.go
Labels: backport-skip

#1086 [AWS Orgs] Implement running fetchers for each account
  .golangci.yaml
  config/config.go
  config/config_test.go
  dataprovider/providers/aws/data_provider.go
  dataprovider/providers/aws/data_provider_test.go
  flavors/benchmark/aws_org.go
  flavors/benchmark/aws_org_test.go
  flavors/benchmark/benchmark.go
  flavors/benchmark/benchmark_test.go
  flavors/benchmark/eks.go
  flavors/posture.go
  go.mod
  go.sum
  resources/fetching/factory/aws_factory.go
  resources/fetching/factory/aws_factory_test.go
  resources/fetching/factory/mock_aws_factory.go
  resources/fetching/fetcher.go
  resources/providers/awslib/account_provider.go
  resources/providers/awslib/account_provider_test.go
  resources/providers/awslib/iam/policy.go
  resources/providers/awslib/mock_account_provider_api.go
  resources/utils/strings/strings.go
  resources/utils/strings/strings_test.go
  resources/utils/testhelper/helper.go
  resources/utils/testhelper/helper_test.go
Labels: backport-skip

#1125 Create different templates for CSPM and CNVM
  .github/workflows/publish-cloudformation.yml
  .pre-commit-config.yaml
  deploy/cloudformation/.gitignore
  deploy/cloudformation/README.md
  deploy/cloudformation/config.go
  deploy/cloudformation/elastic-agent-ec2-cnvm.yml
  deploy/cloudformation/elastic-agent-ec2-cspm.yml
  deploy/cloudformation/gomain.go
Labels: backport-skip

#1148 Fix CloudFormation deployment config file
  deploy/cloudformation/README.md
  deploy/cloudformation/config.go
Labels: backport-skip

#1143 Bump libbeat version
  .github/workflows/k8s-ci.yml
  cloudbeat.reference.yml
  cloudbeat.yml
  go.mod
  go.sum
  launcher/launcher_test.go
  processor/add_cluster_id/add_cluster_id.go
Labels: backport-skip

#1150 Format CloudFormation with rain
  .pre-commit-config.yaml
  bin/.rain-1.4.3.pkg
  bin/rain
  deploy/cloudformation/ec2-types.yml
  deploy/cloudformation/elastic-agent-ec2-cnvm.yml
  deploy/cloudformation/elastic-agent-ec2-cspm.yml
  deploy/cloudformation/organization.yml
Labels: backport-skip

#1145 Derive GCP sub types from asset type
  resources/fetching/fetchers/gcp/assets_fetcher.go
  resources/fetching/fetchers/gcp/assets_fetcher_test.go
Labels: backport-skip, gcp

#1133 [CNVM] Sort EC2 instances by volume size
  deploy/cloudformation/elastic-agent-ec2-cnvm.yml
  resources/providers/awslib/ec2/ec2_instance.go
  resources/providers/awslib/ec2/mock_client.go
  resources/providers/awslib/ec2/provider.go
  resources/providers/awslib/ec2/provider_test.go
  resources/providers/awslib/ec2/volume.go
  vulnerability/fetcher.go
  vulnerability/fetcher_test.go
  vulnerability/mock_instances_provider.go
  vulnerability/mock_replicator_provider.go
  vulnerability/mock_worker_provider.go
  vulnerability/replicator.go
  vulnerability/replicator_test.go
  vulnerability/worker.go
  vulnerability/worker_test.go
Labels: backport-skip

#1067 [Release] Update version to 8.9.1
  version/version.go
Labels: team:automation, release

#1154 golangci-lint: Make order of imports deterministic
  .golangci.yaml
  .pre-commit-config.yaml
  flavors/benchmark/gcp.go
  resources/fetching/fetchers/gcp/assets_fetcher.go
  resources/providers/gcplib/inventory/provider.go
  resources/providers/gcplib/inventory/provider_test.go
  vulnerability/events_creator_test.go
Labels: backport-skip

#1146 Destroy environment workflow
  .github/workflows/destroy-environment.yml
  deploy/test-environments/delete_env.sh
  dev-docs/Cloud-Env-Testing.md
Labels: backport-skip

#1156 worker disk space cleanup
  .github/workflows/cloudbeat-ci.yml
  .github/workflows/eks-ci.yml
  .github/workflows/k8s-ci.yml
Labels: backport-skip

#1162 fix inputs params
  .github/workflows/destroy-environment.yml
Labels: backport-skip

#1164 adding disk cleanup step to post merge K8s test
  .github/workflows/k8s-ci.yml
Labels: backport-skip

#1139 eks clusters migration
  .github/workflows/eks-ci.yml
  tests/deploy/aws/eks_config/test-eks-config-1-node-1-10-kubelet-args.conf
  tests/deploy/aws/eks_config/test-eks-config-1-node-1-kubelet-config.json
  tests/deploy/aws/eks_config/test-eks-config-1-node-2-10-kubelet-args.conf
  tests/deploy/aws/eks_config/test-eks-config-1-node-2-kubelet-config.json
  tests/deploy/aws/eks_config/test-eks-config-2-node-1-10-kubelet-args.conf
  tests/deploy/aws/eks_config/test-eks-config-2-node-1-kubelet-config.json
  tests/deploy/aws/eks_config/test-eks-config-2-node-2-10-kubelet-args.conf
  tests/deploy/aws/eks_config/test-eks-config-2-node-2-kubelet-config.json
  tests/deploy/k8s-cloudbeat-tests/templates/_eks-psp-failures-pod.yaml
  tests/deploy/k8s-cloudbeat-tests/templates/_eks-psp-pass-pod.yaml
  tests/deploy/k8s-cloudbeat-tests/templates/cloudbeat-eks-pytest.yaml
  tests/deploy/k8s-cloudbeat-tests/templates/cloudbeat-test-configmap.yml
  tests/deploy/k8s-cloudbeat-tests/templates/eks-results.yml
  tests/deploy/k8s-cloudbeat-tests/values.yaml
  tests/deploy/values/ci-eks-config-1.yml
  tests/deploy/values/ci-eks-config-2.yml
Labels: backport-skip

#1165 Make CollectResourcesWithTimeout less flaky
  resources/fetching/factory/aws_factory_test.go
  resources/utils/testhelper/helper.go
  resources/utils/testhelper/helper_test.go
Labels: backport-skip

#1167 [AWS Orgs] Replace underscore in configuration with hyphen
  config/config.go
  config/config_test.go
  flavors/benchmark/benchmark_test.go
Labels: backport-skip

#1075 [CNVM] Limit permissions for CloudFormation
  deploy/cloudformation/elastic-agent-ec2-cnvm.yml
  resources/providers/awslib/ec2/provider.go
Labels: backport-skip

#1161 gcp: NewProvider: Avoid returning nil
  .github/workflows/unit-test.yml
  flavors/benchmark/gcp.go
  flavors/posture.go
  resources/providers/gcplib/auth/credentials.go
  resources/providers/gcplib/auth/credentials_test.go
  resources/providers/gcplib/identity/identity_provider.go
Labels: backport-skip, gcp

#1170 Use testhelper.NewLogger in remaining tests
  resources/fetching/fetchers/aws/logging_fetcher_test.go
  resources/fetching/fetchers/aws/network_fetcher_test.go
  resources/providers/awslib/ec2/provider_test.go
  vulnerability/events_creator_test.go
Labels: backport-skip

#1169 Refactor benchmark.go to remove `Dependencies` struct
  .golangci.yaml
  flavors/benchmark/aws.go
  flavors/benchmark/aws_org.go
  flavors/benchmark/aws_org_test.go
  flavors/benchmark/aws_test.go
  flavors/benchmark/benchmark.go
  flavors/benchmark/benchmark_test.go
  flavors/benchmark/eks.go
  flavors/benchmark/eks_test.go
  flavors/benchmark/gcp.go
  flavors/benchmark/gcp_test.go
  flavors/benchmark/k8s.go
  flavors/benchmark/k8s_test.go
  flavors/benchmark/mock_benchmark.go
  flavors/posture.go
  go.mod
  resources/providers/gcplib/identity/identity_provider.go
  resources/providers/gcplib/identity/identity_provider_test.go
  resources/providers/gcplib/identity/mock_identity_provider_getter.go
  resources/providers/gcplib/identity/mock_provider_getter.go
Labels: backport-skip

#1171 Update golang-ci-lint settings
  .github/workflows/unit-test.yml
  .golangci.yaml
  processor/add_cluster_id/add_cluster_id.go
  resources/fetching/fetchers/gcp/assets_fetcher_test.go
  resources/providers/awslib/iam/test_data.go
  resources/providers/awslib/iam/user.go
  resources/providers/awslib/iam/user_test.go
  vulnerability/worker_test.go
Labels: backport-skip

#1163 CloudFormation: Rollback deployment if agent installation fails
  deploy/cloudformation/README.md
  deploy/cloudformation/elastic-agent-ec2-cnvm.yml
  deploy/cloudformation/elastic-agent-ec2-cspm.yml
Labels: backport-skip

#1166 fix agent tests
  .github/workflows/k8s-ci.yml
  tests/commonlib/elastic_wrapper.py
  tests/deploy/sa-agent-pytest.yml
  tests/integration/tests/test_standalone_agent_integration.py
Labels: backport-skip

#1168 [AWS Orgs] Add EC2 instance to CloudFormation
  .github/workflows/publish-cloudformation.yml
  deploy/cloudformation/elastic-agent-ec2-cspm-organization.yml
  deploy/cloudformation/organization.yml
  flavors/posture.go
  launcher/launcher.go
Labels: backport-skip
