Repository elastic/cloudbeat, pull requests merged in 2023-09, with the labels that each got.

#1193 [AWS Orgs] Add cloud organization fields
  dataprovider/providers/cloud/data_provider.go
  flavors/benchmark/aws_org.go
  flavors/benchmark/aws_org_test.go
  resources/fetching/factory/aws_factory.go
  resources/fetching/fetcher.go
  resources/providers/awslib/account_provider.go
  resources/providers/awslib/account_provider_test.go
  resources/providers/awslib/mock_account_provider_api.go
  resources/providers/awslib/mock_organizations_api.go
Labels: backport-skip

#1304 bump CIS bundle version
  version/policy.go
Labels: backport-v8.10.0

#1295 implement cspm gcp integration
  .github/workflows/destroy-environment.yml
  .github/workflows/test-environment.yml
  bin/.gcloud-444.0.0.pkg
  bin/bq
  bin/docker-credential-gcloud
  bin/gcloud
  bin/git-credential-gcloud.sh
  bin/gsutil
  deploy/cloud/data/agent_policy_cspm_gcp.json
  deploy/cloud/data/package_policy_cspm_gcp.json
  deploy/deployment-manager/deploy.sh
  deploy/deployment-manager/set_env.sh
  deploy/test-environments/delete_env.sh
  deploy/test-environments/fleet_api/README.md
  deploy/test-environments/fleet_api/src/configuration_fleet.py
  deploy/test-environments/fleet_api/src/install_cspm_gcp_integration.py
  justfile
  tests/integration/tests/test_sanity_checks.py
Labels: backport-skip

#1269 [CIS GCP] Improve onboarding script
  deploy/deployment-manager/compute_engine.py
  deploy/deployment-manager/deploy.sh
Labels: backport-skip

#1316 Update to actions/checkout@v4
  .github/workflows/bump-golang.yml
  .github/workflows/cloudbeat-ci.yml
  .github/workflows/cloudformation-ci.yml
  .github/workflows/cnvm-ci.yml
  .github/workflows/destroy-environment.yml
  .github/workflows/eks-ci.yml
  .github/workflows/k8s-ci.yml
  .github/workflows/packaging.yml
  .github/workflows/periodic-ci.yml
  .github/workflows/publish-cloudformation.yml
  .github/workflows/publish-test-results.yml
  .github/workflows/test-environment.yml
  .github/workflows/unit-test.yml
  .github/workflows/weekly-enviroment.yml
Labels: backport-skip

#1318 skip post-merge eks tests
  .github/workflows/eks-ci.yml
Labels: backport-skip

#1288 [Release] Update version to 8.9.3
  version/version.go
Labels: team:automation, release

#1262 [GCP] Add support for fetching organization resources
  config/config.go
  flavors/benchmark/benchmark.go
  flavors/benchmark/gcp.go
  flavors/benchmark/gcp_test.go
  resources/fetching/fetcher.go
  resources/fetching/fetchers/gcp/assets_fetcher.go
  resources/fetching/fetchers/gcp/assets_fetcher_test.go
  resources/fetching/fetchers/gcp/monitoring_fetcher.go
  resources/fetching/fetchers/gcp/monitoring_fetcher_test.go
  resources/providers/gcplib/auth/credentials.go
  resources/providers/gcplib/auth/credentials_test.go
  resources/providers/gcplib/identity/identity_provider.go
  resources/providers/gcplib/identity/identity_provider_test.go
  resources/providers/gcplib/identity/mock_provider_getter.go
  resources/providers/gcplib/identity/mock_resource_manager.go
  resources/providers/gcplib/inventory/mock_service_api.go
  resources/providers/gcplib/inventory/provider.go
  resources/providers/gcplib/inventory/provider_test.go
Labels: backport-skip, gcp

#1314 [CIS GCP] Support cloud native organization deployment
  deploy/deployment-manager/README.md
  deploy/deployment-manager/compute_engine.py
  deploy/deployment-manager/deploy.sh
Labels: backport-skip

#1329 [CIS GCP] Make resource name more friendly
  resources/fetching/fetchers/gcp/assets_fetcher.go
Labels: backport-skip

#1307 Addition of CIS Azure benchmark type
  config/benchmark.go
  config/config_test.go
  deploy/azure/cloudbeat-azure.yml
Labels: backport-skip

#1313 [AWS Orgs] Update fetchers in each cycle to detect changes in accounts
  flavors/benchmark/aws.go
  flavors/benchmark/aws_org.go
  flavors/benchmark/aws_org_test.go
  flavors/benchmark/benchmark_test.go
  flavors/benchmark/eks.go
  flavors/benchmark/gcp.go
  flavors/benchmark/gcp_test.go
  flavors/benchmark/k8s.go
  flavors/posture.go
  resources/fetching/factory/aws_factory.go
  resources/fetching/factory/aws_factory_test.go
  resources/fetching/manager/manager.go
  resources/fetching/manager/manager_test.go
  resources/fetching/registry/mock_option.go
  resources/fetching/registry/mock_registry.go
  resources/fetching/registry/mock_updater_func.go
  resources/fetching/registry/registry.go
  resources/fetching/registry/registry_test.go
Labels: backport-skip

#1328 [CloudFormation] Verify installation of cfn-signal
  deploy/cloudformation/elastic-agent-ec2-cnvm.yml
  deploy/cloudformation/elastic-agent-ec2-cspm-organization.yml
  deploy/cloudformation/elastic-agent-ec2-cspm.yml
Labels: backport-skip

#1330 go.mod: Organize require blocks and update SDKs
  go.mod
  go.sum
  resources/providers/awslib/ec2/provider.go
Labels: backport-skip

#1327 [CIS GCP] Add log bucket type to asset fetcher
  resources/fetching/fetchers/gcp/assets_fetcher.go
  version/policy.go
Labels: backport-skip

#1334 Rename factory package to preset
  flavors/benchmark/aws.go
  flavors/benchmark/aws_org.go
  flavors/benchmark/eks.go
  flavors/benchmark/gcp.go
  flavors/benchmark/k8s.go
  resources/fetching/preset/aws_preset.go
  resources/fetching/preset/aws_preset_test.go
  resources/fetching/preset/eks_preset.go
  resources/fetching/preset/gcp_preset.go
  resources/fetching/preset/k8s_preset.go
  resources/fetching/preset/mock_aws_factory.go
  resources/fetching/registry/fetchers.go
  resources/fetching/registry/mock_updater_func.go
  resources/fetching/registry/registry.go
  resources/fetching/registry/registry_test.go
Labels: backport-skip

#1336 pre-commit: golangci-lint: Auto fix supported failures
  .pre-commit-config.yaml
Labels: backport-skip

#1337 Remove extra build step
  .github/workflows/cloudbeat-ci.yml
  .github/workflows/eks-ci.yml
  .github/workflows/k8s-ci.yml
Labels: backport-skip

#1312 AWS CSPM Resources add ECS data
  dataprovider/enrich.go
  dataprovider/providers/common/data_provider.go
  evaluator/opa_test.go
  resources/fetching/fetcher.go
  resources/fetching/fetchers/aws/ecr_fetcher.go
  resources/fetching/fetchers/aws/ecr_fetcher_test.go
  resources/fetching/fetchers/aws/elb_fetcher.go
  resources/fetching/fetchers/aws/elb_fetcher_test.go
  resources/fetching/fetchers/aws/iam_fetcher.go
  resources/fetching/fetchers/aws/iam_fetcher_test.go
  resources/fetching/fetchers/aws/kms_fetcher.go
  resources/fetching/fetchers/aws/kms_fetcher_test.go
  resources/fetching/fetchers/aws/logging_fetcher.go
  resources/fetching/fetchers/aws/logging_fetcher_test.go
  resources/fetching/fetchers/aws/monitoring_fetcher.go
  resources/fetching/fetchers/aws/network_fetcher.go
  resources/fetching/fetchers/aws/network_fetcher_test.go
  resources/fetching/fetchers/aws/rds_fetcher.go
  resources/fetching/fetchers/aws/rds_fetcher_test.go
  resources/fetching/fetchers/aws/s3_fetcher.go
  resources/fetching/fetchers/aws/s3_fetcher_test.go
  resources/fetching/fetchers/k8s/file_system_fetcher.go
  resources/fetching/fetchers/k8s/kube_provider.go
  resources/fetching/fetchers/k8s/process_fetcher.go
  resources/fetching/preset/aws_org_preset.go
  resources/fetching/registry/registry_test.go
Labels: backport-skip

#1303 Populate vulnerability.reference with a link to NVD
  .gitignore
  vulnerability/events_creator.go
  vulnerability/events_creator_test.go
Labels: backport-skip

#1325 [Cloud Security] [Telemetry] fix package policy vars to use posture field
  deploy/cloud/data/package_policy_cnvm_aws.json
Labels: bug, backport-skip, Team:Cloud Security, 8.11 candidate

#1332 Use branches to get bundles
  flavors/posture.go
  magefile.go
  version/policy.go
Labels: backport-v8.9.0, backport-v8.10.0

#1340 [CIS GCP] Add a service-usage fetcher
  flavors/benchmark/gcp_test.go
  resources/fetching/fetcher.go
  resources/fetching/fetchers/gcp/service_usage_fetcher.go
  resources/fetching/fetchers/gcp/service_usage_fetcher_test.go
  resources/fetching/preset/gcp_preset.go
  resources/providers/gcplib/inventory/mock_service_api.go
  resources/providers/gcplib/inventory/provider.go
  resources/providers/gcplib/inventory/provider_test.go
Labels: backport-skip

#1339 [CIS GCP] Enrich vpc network with dns policy
  resources/fetching/fetchers/gcp/assets_fetcher.go
  resources/fetching/fetchers/gcp/assets_fetcher_test.go
  resources/fetching/fetchers/gcp/monitoring_fetcher.go
  resources/providers/gcplib/inventory/asset.go
  resources/providers/gcplib/inventory/provider.go
  resources/providers/gcplib/inventory/provider_test.go
Labels: backport-skip

#1348 Update Cloud Env workflow to default to our Org API key
  .github/workflows/destroy-environment.yml
  .github/workflows/test-environment.yml
  .github/workflows/weekly-enviroment.yml
  dev-docs/CSPM-Cloud-Deployment.md
  dev-docs/Cloud-Env-Testing.md
  dev-docs/Development.md
  dev-docs/ELK-Deployment.md
Labels: backport-skip

#1308 Implement automatic credentials for Azure
  go.mod
  go.sum
  resources/providers/azurelib/auth/auth_provider.go
  resources/providers/azurelib/auth/credentials.go
  resources/providers/azurelib/auth/credentials_test.go
  resources/providers/azurelib/auth/mock_azure_auth_provider_api.go
  resources/providers/azurelib/auth/mock_config_provider_api.go
Labels: backport-skip

#1309 Implementation of ARM template for Azure
  deploy/azure/README.md
  deploy/azure/azureARMTemplate.json
Labels: backport-skip

#1352 Make common data provider more efficient
  dataprovider/providers/common/data_provider.go
  dataprovider/providers/common/data_provider_test.go
  flavors/posture.go
Labels: enhancement, backport-skip

#1354 pre-commit: Add shfmt hook
  .buildkite/scripts/package.sh
  .buildkite/scripts/publish.sh
  .ci/scripts/allure-report-summary.sh
  .ci/scripts/ecr-images.sh
  .ci/scripts/kind-images.sh
  .pre-commit-config.yaml
  bin/.shfmt-3.7.0.pkg
  bin/shfmt
  deploy/deployment-manager/deploy.sh
  deploy/test-environments/delete_env.sh
  deploy/weekly-environment/scripts/benchmarks/kspm_vanilla/install-kspm-vanilla-integration.sh
  deploy/weekly-environment/scripts/utils.sh
  dev-tools/packaging/docker/elastic-agent/build.sh
  scripts/common.sh
  scripts/make/aws_creds_env.sh
  scripts/make/check_goimports.sh
  scripts/make/common.bash
  scripts/publish_cft.sh
  scripts/remote_edit_config.sh
Labels: backport-skip, technical debt

#1310 Implement Azure fetchers and asset provider
  go.mod
  go.sum
  resources/fetching/fetcher.go
  resources/fetching/fetchers/azure/assets_fetcher.go
  resources/fetching/fetchers/azure/assets_fetcher_test.go
  resources/fetching/preset/azure_factory.go
  resources/providers/azurelib/inventory/asset.go
  resources/providers/azurelib/inventory/mock_provider_initializer_api.go
  resources/providers/azurelib/inventory/mock_service_api.go
  resources/providers/azurelib/inventory/provider.go
  resources/providers/azurelib/inventory/provider_test.go
Labels: backport-skip

#1359 [Release] Update version to 8.10.3
  version/version.go
Labels: team:automation, release

#1357 Azure: Deploy Elastic Agent
  .pre-commit-config.yaml
  bin/.shellcheck-0.9.0.pkg
  bin/shellcheck
  deploy/azure/azureARMTemplate.json
  deploy/azure/install-agent.sh
Labels: backport-skip

#1360 Azure ARM: Fix Role Assignment race condition
  deploy/azure/azureARMTemplate.json
Labels: backport-skip

#1311 Implement Azure benchmark
  flavors/benchmark/azure.go
  flavors/benchmark/azure_test.go
  flavors/benchmark/strategy.go
Labels: backport-skip

#1365 Azure fetchers: Improve tests
  resources/fetching/fetchers/azure/assets_fetcher_test.go
Labels: backport-skip

#1369 Add `package_policy` fields to vulnerability and findings indexes
  cmd/root.go
  config/config.go
  config/config_test.go
  dataprovider/providers/common/data_provider.go
  dataprovider/providers/common/data_provider_test.go
  flavors/benchmark/builder/builder.go
  flavors/flavors.go
  flavors/vulnerability.go
  resources/providers/gcplib/inventory/mock_type_generator.go
  vulnerability/events_creator.go
  vulnerability/events_creator_test.go
  vulnerability/mock_enricher.go
  vulnerability/worker.go
  vulnerability/worker_test.go
Labels: backport-skip

#1363 Azure ARM: Use temporary public key and disable SSH
  deploy/azure/README.md
  deploy/azure/azureARMTemplate.json
  deploy/azure/install-agent.sh
Labels: backport-skip
