Repository elastic/cloudbeat, pull requests merged in 2023-01, with the labels that each got.

#630 [Cloud Posture] Removing UT and cloudbeat CI from post merge
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/workflows/cloudbeat-ci.yml
  .github/workflows/unit-test.yml
Labels: backport-skip, Team: Cloud Security

#628 Move launcher errors under launcher package
  config/config.go
  launcher/errors.go
  launcher/errors_test.go
  launcher/launcher.go
Labels: backport-skip

#616 Add rule number field
  README.md
  bin/.elastic-package-0.70.1.pkg
  bin/.kustomize-4.5.7.pkg
  bin/elastic-package
  bin/kustomize
  deploy/kustomize/overlays/cloudbeat-vanilla-agent/README.md
  dev-docs/Development.md
  evaluator/evaluator.go
  justfile
  tests/README.md
  version/policy.go
Labels: backport-skip

#641 fix cloudbeat commit SHA field format
  version/settings.go
Labels: backport-skip

#617 feat: add ec2
  .gitignore
  deploy/cloud/README.md
  deploy/cloud/data/agent_policy_vanilla.json
  deploy/cloud/data/package_policy_vanilla.json
  deploy/cloud/main.tf
  deploy/cloud/modules/api/main.tf
  deploy/cloud/modules/api/outputs.tf
  deploy/cloud/modules/ec2/main.tf
  deploy/cloud/modules/ec2/output.tf
  deploy/cloud/modules/ec2/terraform.tf
  deploy/cloud/modules/ec2/variables.tf
  deploy/cloud/outputs.tf
  deploy/cloud/terraform.tf
  deploy/cloud/variables.tf
Labels: backport-skip

#645 Fixing standalone agent CI
  Makefile
  bin/hermit.hcl
  cloudbeat.reference.yml
  cloudbeat.yml
  deploy/kustomize/overlays/cloudbeat-vanilla/cloudbeat.yml
  dev-tools/packaging/docker/elastic-agent/Dockerfile
  tests/deploy/sa-agent-pytest.yml
Labels: backport-skip

#642 add logger infra
  tests/README.md
  tests/commonlib/elastic_wrapper.py
  tests/commonlib/io_utils.py
  tests/commonlib/kubernetes.py
  tests/commonlib/utils.py
  tests/conftest.py
  tests/integration/tests/conftest.py
  tests/integration/tests/test_cloudbeat_integration.py
  tests/poetry.lock
  tests/product/tests/conftest.py
  tests/product/tests/test_k8s_objects_rules.py
  tests/pyproject.toml
Labels: backport-skip

#649 Modify configuration to be aligned with new structure
  config/config.go
  config/config_test.go
  deploy/aws/cloudbeat-aws.yml
  deploy/kustomize/overlays/cloudbeat-eks/cloudbeat.yml
  resources/fetchersManager/factory.go
  resources/fetchersManager/factory_aws_test.go
  resources/fetchersManager/factory_test.go
  resources/providers/cluster_provider.go
  resources/providers/cluster_provider_test.go
  tests/deploy/cloudbeat-eks-pytest.yaml
  version/policy.go
Labels: backport-skip

#655 Enrich decision log message with OPA fields
  evaluator/debug_logger/plugin.go
  evaluator/opa_test.go
Labels: backport-skip

#515 [Release] Update version to 8.6.1
  version/version.go
Labels: team:automation, release

#660 Add policy data to the IAM user [CSPM]
  resources/providers/awslib/iam/client_mock.go
  resources/providers/awslib/iam/iam.go
  resources/providers/awslib/iam/policy.go
  resources/providers/awslib/iam/root_account.go
  resources/providers/awslib/iam/user.go
  resources/providers/awslib/iam/user_test.go
  version/policy.go
Labels: backport-skip

#662 Fix OPA package build
  .github/workflows/eks-ci.yml
  magefile.go
Labels: backport-skip

#663 chore: update libbeat
  go.mod
  go.sum
Labels: backport-skip

#654 Add Multi region support for CSPM
  config/aws_config_provider_mock.go
  config/config.go
  deploy/aws/cloudbeat-aws.yml
  resources/fetchers/ecr_factory.go
  resources/fetchers/ecr_factory_test.go
  resources/fetchers/eks_factory.go
  resources/fetchers/eks_factory_test.go
  resources/fetchers/elb_factory.go
  resources/fetchers/elb_factory_test.go
  resources/fetchers/iam_factory.go
  resources/fetchers/iam_factory_test.go
  resources/fetchers/network_factory.go
  resources/fetchers/network_factory_test.go
  resources/fetchers/network_fetcher.go
  resources/fetchers/network_fetcher_test.go
  resources/fetchers/s3_factory.go
  resources/fetchers/s3_factory_test.go
  resources/providers/awslib/aws.go
  resources/providers/awslib/config_provider.go
  resources/providers/awslib/config_provider_mock.go
  resources/providers/awslib/config_provider_test.go
  resources/providers/awslib/cross_region_factory_mock.go
  resources/providers/awslib/cross_region_fetcher_mock.go
  resources/providers/awslib/describe_cloud_regions_mock.go
  resources/providers/awslib/ec2/cross.go
  resources/providers/awslib/ec2/ec2.go
  resources/providers/awslib/ec2/provider.go
  resources/providers/awslib/ec2/provider_client_mock.go
  resources/providers/awslib/ec2/provider_test.go
  resources/providers/awslib/multi_region.go
  resources/providers/awslib/multi_region_test.go
  resources/providers/awslib/s3/provider.go
  resources/providers/awslib/s3/provider_test.go
  resources/providers/awslib/s3/s3.go
  resources/providers/cluster_provider.go
  resources/providers/cluster_provider_test.go
Labels: backport-skip

#665 feat: add cloudtrail provider
  go.mod
  go.sum
  resources/fetching/fetcher.go
  resources/providers/awslib/cloudtrail/aws_client_mock.go
  resources/providers/awslib/cloudtrail/cloudtrail.go
  resources/providers/awslib/cloudtrail/provider.go
  resources/providers/awslib/cloudtrail/provider_test.go
  resources/providers/awslib/cloudtrail/trail.go
Labels: backport-skip

#666 Logs alignment
  beater/cloudbeat.go
  launcher/listener.go
  resources/fetchers/kube_fetcher.go
  resources/fetchersManager/data.go
  uniqueness/leaderelection.go
Labels: backport-skip

#659 Move `rule_number` under `benchmark` metadata
  .github/pull_request_template.md
  evaluator/evaluator.go
  version/policy.go
Labels: backport-skip

#667 Doc links fix
  README.md
Labels: backport-skip, Team:Cloud Security

#674 Launcher logging adds beater name
  beater/cloudbeat.go
  launcher/launcher.go
  launcher/launcher_test.go
  uniqueness/leaderelection.go
Labels: backport-skip

#673 [Release] Update version to 8.6.2
  version/version.go
Labels: team:automation, release

#679 chore: update beats
  go.mod
  go.sum
Labels: backport-skip

#682 Move Unit tests & Coverage report to post-merge
  .github/CODEOWNERS
  .github/workflows/cloudbeat-ci.yml
  .github/workflows/unit-test.yml
  .pre-commit-config.yaml
  _meta/config/cloudbeat.common.yml.tmpl
  _meta/config/processors.yml.tmpl
  cloudbeat.reference.yml
  cloudbeat.yml
  deploy/cloud/data/agent_policy_vanilla.json
  deploy/cloud/data/package_policy_vanilla.json
  deploy/cloud/modules/ec2/output.tf
  deploy/cloud/modules/provision-apps/terraform.tf
  deploy/cloud/modules/provision-apps/variables.tf
  deploy/cloud/variables.tf
  deploy/cloudformation/README.md
  deploy/cloudformation/elastic-agent-ec2.yml
  tests/deploy/sa-agent-pytest.yml
Labels: backport-skip

#658 Eks func tests ci
  .github/workflows/eks-ci.yml
  tests/commonlib/elastic_wrapper.py
  tests/commonlib/utils.py
  tests/configuration.py
  tests/conftest.py
  tests/deploy/k8s-cloudbeat-tests/templates/_eks-psp-failures-pod.yaml
  tests/deploy/k8s-cloudbeat-tests/templates/_eks-psp-pass-pod.yaml
  tests/deploy/k8s-cloudbeat-tests/templates/cloudbeat-eks-pytest.yaml
  tests/deploy/k8s-cloudbeat-tests/templates/cloudbeat-test-configmap.yml
  tests/deploy/k8s-cloudbeat-tests/templates/tests/cloudbeat-test-pod.yml
  tests/deploy/k8s-cloudbeat-tests/values.yaml
  tests/deploy/values/ci-eks-config-1.yml
  tests/deploy/values/ci-eks-config-2.yml
  tests/deploy/values/ci.yml
  tests/integration/tests/test_standalone_agent_integration.py
  tests/product/tests/conftest.py
  tests/product/tests/data/aws/managed_services_test_cases.py
  tests/product/tests/data/file_system/eks_file_system_test_cases.py
  tests/product/tests/data/file_system/eks_test_cases.py
  tests/product/tests/data/k8s_object/eks_k8s_object_test_cases.py
  tests/product/tests/data/process/eks_process_test_cases.py
  tests/product/tests/test_eks_aws_managed_services_rules.py
  tests/product/tests/test_eks_file_system_rules.py
  tests/product/tests/test_eks_k8s_objects_rules.py
  tests/product/tests/test_eks_process_kubelet_rules.py
Labels: backport-skip

#688 Eks post merge ci
  .github/workflows/eks-ci.yml
Labels: backport-skip

#684 feat: add securityhub provider
  deploy/aws/cloudbeat-aws.yml
  go.mod
  go.sum
  resources/fetchers/monitoring_factory.go
  resources/fetchers/monitoring_factory_test.go
  resources/fetchers/monitoring_fetcher.go
  resources/fetchers/monitoring_fetcher_test.go
  resources/fetchers/network_factory.go
  resources/fetchers/network_factory_test.go
  resources/fetchers/network_fetcher.go
  resources/fetchers/network_fetcher_test.go
  resources/fetching/fetcher.go
  resources/providers/awslib/ec2/cross.go
  resources/providers/awslib/multi_region.go
  resources/providers/awslib/multi_region_test.go
  resources/providers/awslib/securityhub/mock_client.go
  resources/providers/awslib/securityhub/mock_service.go
  resources/providers/awslib/securityhub/provider.go
  resources/providers/awslib/securityhub/provider_test.go
  resources/providers/awslib/securityhub/securityhub.go
Labels: backport-skip
