Repository elastic/cloudbeat, pull requests merged in 2023-11, with the labels that each got.

#1514 add common elastic tags to eks cluster
  deploy/eks/simple-cluster.yml
Labels: backport-skip

#1494 Add bump-beats pipeline
  .ci/bump-beats.yml
  .ci/scripts/update-beats.sh
  .github/workflows/update-beats.yml
  .pre-commit-config.yaml
Labels: backport-skip, automation, dependency, technical debt

#1504 shellcheck: Enable for all ci scripts
  .ci/scripts/ecr-images.sh
  .pre-commit-config.yaml
Labels: backport-skip, technical debt

#1517 updatecli: fix names and use values
  .ci/updatecli/updatecli.d/bump-golang.yml
  .ci/updatecli/updatecli.d/update-beats.yml
  .ci/updatecli/values.yml
  .github/workflows/bump-golang.yml
  .github/workflows/update-beats.yml
Labels: backport-skip

#1518 mage: BuildOpaBundle: Clean-up some leftover code
  magefile.go
Labels: backport-skip, technical debt

#1519 Revert "CloudFormation: Fix missing tags in cloud-security account"
  deploy/cloudformation/elastic-agent-ec2-cnvm.yml
  deploy/cloudformation/elastic-agent-ec2-cspm.yml
Labels: backport-skip

#1515 Add serverless dependencies to hermit
  bin/.cue-0.6.0.pkg
  bin/.eksctl-0.164.0.pkg
  bin/.gh-2.37.0.pkg
  bin/cue
  bin/eksctl
  bin/gh
Labels: backport-skip

#1525 update-beats: Set -x flag to print commands
  .ci/scripts/update-beats.sh
Labels: backport-skip, automation

#1528 update-beats: Use hermit for go
  .ci/scripts/update-beats.sh
  .github/workflows/update-beats.yml
Labels: backport-skip, automation

#1530 bump-beats: Re-generate mage config after update
  .ci/scripts/update-beats.sh
Labels: backport-skip, automation

#1532 [updatecli] Update to elastic/beats@475eaf5784b4
  cloudbeat.reference.yml
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#1490 Add azure manual credentials
  config/config.go
  flavors/benchmark/azure.go
  flavors/benchmark/azure_test.go
  resources/providers/azurelib/auth/auth_provider.go
  resources/providers/azurelib/auth/credentials.go
  resources/providers/azurelib/auth/credentials_test.go
  resources/providers/azurelib/auth/mock_azure_auth_provider_api.go
  resources/providers/azurelib/auth/mock_config_provider_api.go
Labels: backport-skip

#1484 Azure: Send at least one batch resource per subscription
  resources/fetching/fetchers/azure/batch_fetcher.go
  resources/fetching/fetchers/azure/batch_fetcher_test.go
  resources/providers/azurelib/inventory/mock_service_api.go
  resources/providers/azurelib/inventory/provider.go
Labels: backport-skip

#1534 Destroy Env script enhancements
  .pre-commit-config.yaml
  deploy/test-environments/delete_env.sh
Labels: backport-skip

#1503 updatecli: Re-structure pipelines, add hermit
  .ci/updatecli/scripts/hermit-bump-go.sh
  .ci/updatecli/scripts/update-beats.sh
  .ci/updatecli/scripts/update-hermit.sh
  .ci/updatecli/updatecli.d/update-beats.yml
  .ci/updatecli/updatecli.d/update-golang.yml
  .ci/updatecli/updatecli.d/update-hermit.yml
  .github/workflows/update-beats.yml
  .github/workflows/updatecli.yml
  bin/goimports
  scripts/make/check_goimports.sh
  scripts/make/goimports.sh
  tools/tools.go
Labels: backport-skip, automation, technical debt

#1543 [updatecli] Update to elastic/beats@9b932c47cec8
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#1544 Updatecli: Update pre-commit as well
  .ci/updatecli/scripts/update-hermit.sh
  .ci/updatecli/updatecli.d/update-hermit.yml
Labels: backport-skip, automation, dependency

#1539 [Release] Update version to 8.11.2
  version/version.go
Labels: team:automation, release

#1541 [updatecli] Update hermit dependencies
  .pre-commit-config.yaml
  bin/.aws-iam-authenticator-0.6.11.pkg
  bin/.awscli-2.13.26.pkg
  bin/.elastic-package-0.91.2.pkg
  bin/.gh-2.38.0.pkg
  bin/.golangci-lint-1.55.2.pkg
  bin/.jq-1.7.pkg
  bin/.kind-0.20.0.pkg
  bin/.opa-0.58.0.pkg
  bin/.regal-0.12.0.pkg
  bin/aws
  bin/aws-iam-authenticator
  bin/aws_completer
  bin/elastic-package
  bin/gh
  bin/golangci-lint
  bin/jq
  bin/kind
  bin/opa
  bin/regal
  security-policies/bundle/compliance/cis_azure/test_data.rego
  security-policies/bundle/compliance/cis_eks/test_data.rego
Labels: backport-skip, automation, dependency

#1520 Implement Azure deployment and sanity checks
  .github/workflows/destroy-environment.yml
  .github/workflows/test-environment.yml
  deploy/cloud/data/agent_policy_cspm_azure.json
  deploy/cloud/data/package_policy_cspm_azure.json
  deploy/test-environments/delete_env.sh
  deploy/test-environments/fleet_api/src/configuration_fleet.py
  deploy/test-environments/fleet_api/src/install_cspm_azure_integration.py
  tests/integration/tests/test_sanity_checks.py
Labels: backport-skip

#1542 [updatecli] Update Golang version to 1.20.11
  .go-version
  bin/.go-1.20.11.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: backport-skip, automation, dependency, go

#1549 update-hermit: Consider major versions as well
  .ci/updatecli/scripts/update-hermit.sh
Labels: backport-skip, automation, dependency

#1552 [updatecli] Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.elastic-package-0.92.0.pkg
  bin/.gcloud-454.0.0.pkg
  bin/.just-1.16.0.pkg
  bin/.pre-commit-3.5.0.pkg
  bin/.yq-4.35.2.pkg
  bin/bq
  bin/docker-credential-gcloud
  bin/elastic-package
  bin/gcloud
  bin/git-credential-gcloud.sh
  bin/gsutil
  bin/just
  bin/pre-commit
  bin/yq
Labels: backport-skip, automation, dependency

#1554 Add hermit configuration to dev docs
  dev-docs/Development.md
Labels: backport-skip

#1557 Update go to 1.21
  .github/workflows/cloudbeat-ci.yml
  .go-version
  bin/.go-1.21.4.pkg
  bin/go
  bin/gofmt
  deploy/cloudformation/config.go
  docs/version.asciidoc
  go.mod
  go.sum
  resources/fetching/fetchers/aws/iam_fetcher_test.go
  resources/fetching/fetchers/aws/kms_fetcher_test.go
  resources/fetching/fetchers/aws/s3_fetcher_test.go
  resources/providers/aws_cis/logging/provider_test.go
  resources/providers/awslib/cloudtrail/provider_test.go
Labels: backport-skip, dependency, go

#1555 Add Azure credentials type in configuration
  config/config.go
  resources/providers/azurelib/auth/credentials.go
  resources/providers/azurelib/auth/credentials_test.go
Labels: backport-skip

#1556 Update dev docs to refer to already existing hermit docs
  dev-docs/Development.md
Labels: backport-skip

#1560 hermit: Remove bootstrapping workaround
  .github/workflows/cloudbeat-ci.yml
Labels: backport-skip

#1564 Azure credentials config: Add missing type `arm_template`
  config/config.go
  resources/providers/azurelib/auth/credentials.go
  resources/providers/azurelib/auth/credentials_test.go
Labels: bug, backport-skip

#1558 IGNORE_PREFIX fix in delete_env
  deploy/test-environments/delete_env.sh
Labels: backport-skip

#1566 [updatecli] Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.gcloud-455.0.0.pkg
  bin/.gh-2.39.1.pkg
  bin/bq
  bin/docker-credential-gcloud
  bin/gcloud
  bin/gh
  bin/git-credential-gcloud.sh
  bin/gsutil
Labels: backport-skip, automation, dependency

#1561 CIS Azure 5.3.1 - Ensure Application Insights are Configured
  resources/fetching/fetcher.go
  resources/fetching/fetchers/azure/batch_fetcher.go
  resources/fetching/fetchers/azure/batch_fetcher_test.go
  resources/providers/azurelib/inventory/asset.go
  security-policies/RULES.md
  security-policies/bundle/compliance/cis_azure/rules/cis_5_3_1/data.yaml
  security-policies/bundle/compliance/cis_azure/rules/cis_5_3_1/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_5_3_1/test.rego
  security-policies/bundle/compliance/cis_azure/test_data.rego
  security-policies/bundle/compliance/policy/azure/data_adapter.rego
Labels: backport-skip

#1571 Add azure credential type: manual (backwards compatibility value)
  config/config.go
  resources/providers/azurelib/auth/credentials.go
  resources/providers/azurelib/auth/credentials_test.go
Labels: backport-skip

#1535 Support multi asset group query
  resources/fetching/fetcher.go
  resources/fetching/fetchers/azure/assets_fetcher.go
  resources/fetching/fetchers/azure/assets_fetcher_test.go
  resources/fetching/fetchers/azure/batch_fetcher.go
  resources/fetching/fetchers/azure/batch_fetcher_test.go
  resources/providers/azurelib/inventory/asset.go
  resources/providers/azurelib/inventory/mock_service_api.go
  resources/providers/azurelib/inventory/provider.go
  resources/providers/azurelib/inventory/provider_test.go
  security-policies/README.md
  security-policies/RULES.md
  security-policies/bundle/compliance/cis_azure/rules/cis_1_23/data.yaml
  security-policies/bundle/compliance/cis_azure/rules/cis_1_23/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_1_23/test.rego
  security-policies/bundle/compliance/policy/azure/data_adapter.rego
Labels: backport-skip

#1574 Update updatecli workflow to also apply changes to latest active branch
  .ci/updatecli/updatecli.d/update-beats.yml
  .ci/updatecli/updatecli.d/update-golang.yml
  .ci/updatecli/updatecli.d/update-hermit.yml
  .ci/updatecli/values.yml
  .github/workflows/updatecli.yml
Labels: backport-skip

#1577 Remove role deployment from deletion of env
  deploy/test-environments/delete_env.sh
Labels: backport-skip

#1562 [Workflow] Create a serverless project as test environment
  .github/workflows/test-environment.yml
  deploy/cloud/modules/serverless/main.tf
  deploy/cloud/modules/serverless/outputs.tf
  deploy/cloud/modules/serverless/terraform.tf
  deploy/cloud/modules/serverless/variables.tf
  deploy/test-environments/fleet_api/src/api/common_api.py
  deploy/test-environments/fleet_api/src/install_cnvm_integration.py
  deploy/test-environments/main.tf
  deploy/test-environments/output.tf
  deploy/test-environments/terraform.tf
  deploy/test-environments/variables.tf
  tests/integration/tests/test_sanity_checks.py
Labels: backport-skip

#1581 Fix updatecli run for last supported branches
  .github/workflows/updatecli.yml
Labels: backport-skip

#1375 Upgade workflow
  .ci/scripts/get-previous-version.sh
  .github/workflows/test-environment.yml
  .github/workflows/upgrade-environment.yml
  deploy/test-environments/fleet_api/pyproject.toml
  deploy/test-environments/fleet_api/src/api/agent_policy_api.py
  deploy/test-environments/fleet_api/src/api/base_call_api.py
  deploy/test-environments/fleet_api/src/api/common_api.py
  deploy/test-environments/fleet_api/src/api/package_policy_api.py
  deploy/test-environments/fleet_api/src/configuration_fleet.py
  deploy/test-environments/fleet_api/src/install_cnvm_integration.py
  deploy/test-environments/fleet_api/src/install_cspm_azure_integration.py
  deploy/test-environments/fleet_api/src/install_cspm_gcp_integration.py
  deploy/test-environments/fleet_api/src/install_cspm_integration.py
  deploy/test-environments/fleet_api/src/install_d4c_integration.py
  deploy/test-environments/fleet_api/src/install_kspm_eks_integration.py
  deploy/test-environments/fleet_api/src/install_kspm_unmanaged_integration.py
  deploy/test-environments/fleet_api/src/package_policy.py
  deploy/test-environments/fleet_api/src/state_file_manager.py
  deploy/test-environments/fleet_api/src/upgrade_agents.py
  deploy/test-environments/fleet_api/src/upgrade_cnvm.py
  deploy/test-environments/fleet_api/src/utils.py
  dev-docs/Cloud-Env-Upgrade.md
  tests/commonlib/io_utils.py
  tests/commonlib/kubernetes.py
  tests/configuration.py
  tests/integration/tests/conftest.py
  tests/integration/tests/test_sanity_checks.py
  tests/pylintrc
Labels: backport-skip

#1584 Revert Azure deletion to delete the whole resource group
  deploy/test-environments/delete_env.sh
Labels: backport-skip

#1595 [updatecli] Update hermit and pre-commit dependencies
  bin/.yq-4.40.3.pkg
  bin/yq
Labels: backport-skip, automation, dependency

#1591 Fix upgrade flow issues
  .github/workflows/test-environment.yml
  .github/workflows/upgrade-environment.yml
Labels: backport-skip

#1600 Support account type for Azure
  config/config.go
Labels: backport-skip

#1601 Azure: Add ARM for management group deployment
  deploy/azure/ARM-for-organization-account.json
  deploy/azure/ARM-for-single-account.json
Labels: backport-skip

#1607 update azure integration deployment
  deploy/test-environments/fleet_api/src/install_cspm_azure_integration.py
  deploy/test-environments/fleet_api/src/package_policy.py
Labels: backport-skip

#1583 CIS Azure rule 5.1.2
  flavors/benchmark/azure_test.go
  go.mod
  go.sum
  resources/fetching/fetcher.go
  resources/fetching/fetchers/azure/insights_batch_fetcher.go
  resources/fetching/fetchers/azure/insights_batch_fetcher_test.go
  resources/fetching/preset/azure_preset.go
  resources/providers/azurelib/inventory/asset.go
  resources/providers/azurelib/inventory/mock_provider_api.go
  resources/providers/azurelib/inventory/provider.go
  resources/providers/azurelib/inventory/provider_test.go
  resources/providers/azurelib/mock_provider_api.go
  resources/providers/azurelib/provider.go
  security-policies/README.md
  security-policies/RULES.md
  security-policies/bundle/compliance/cis_azure/rules/cis_5_1_2/data.yaml
  security-policies/bundle/compliance/cis_azure/rules/cis_5_1_2/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_5_1_2/test.rego
  security-policies/bundle/compliance/cis_azure/test_data.rego
  security-policies/bundle/compliance/policy/azure/data_adapter.rego
Labels: backport-skip
