Repository elastic/cloudbeat, pull requests merged in 2023-12, with the labels that each got.

#1614 [updatecli] Update to elastic/beats@b30a5ec82af0
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#1615 [updatecli] Update to elastic/beats@be42a3369f94
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#1616 [updatecli] Update hermit and pre-commit dependencies
  bin/.elastic-package-0.94.0.pkg
  bin/.gh-2.39.2.pkg
  bin/.opa-0.59.0.pkg
  bin/.yq-4.40.4.pkg
  bin/elastic-package
  bin/gh
  bin/opa
  bin/yq
Labels: backport-skip, automation, dependency

#1611 CIS Azure 5.1.3
  resources/fetching/cycle/cache.go
  resources/fetching/cycle/cache_test.go
  resources/fetching/fetchers/azure/assets_fetcher.go
  resources/fetching/fetchers/azure/assets_fetcher_test.go
  resources/providers/azurelib/governance/management_group.go
  resources/providers/azurelib/inventory/asset.go
  resources/providers/azurelib/inventory/provider.go
  resources/providers/azurelib/inventory/provider_test.go
  resources/utils/strings/strings_test.go
  security-policies/RULES.md
  security-policies/bundle/compliance/cis_azure/rules/cis_5_1_3/data.yaml
  security-policies/bundle/compliance/cis_azure/rules/cis_5_1_3/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_5_1_3/test.rego
  security-policies/bundle/compliance/cis_azure/test_data.rego
Labels: backport-skip

#1624 Azure ARM: Use resource group deployment schema
  .github/workflows/test-environment.yml
  deploy/azure/ARM-for-single-account.json
  deploy/test-environments/fleet_api/src/install_cspm_azure_integration.py
Labels: backport-skip

#1625 [Cloud Security] bump version of main to 8.13 (for 8.12 FF)
  .mergify.yml
  deploy/azure/ARM-for-organization-account.json
  deploy/azure/ARM-for-single-account.json
  version/version.go
Labels: backport-skip

#1628 Skipping pre-merge k8s tests
  .github/workflows/k8s-ci.yml
Labels: backport-skip, automation

#1627 [Release] Update version to 8.11.3
  version/version.go
Labels: team:automation, release

#1630 ARM-for-organization-account: Deduplicate deployment per region
  deploy/azure/ARM-for-organization-account.json
Labels: backport-v8.12.0

#1640 Azure CI: Delete old parameters
  deploy/test-environments/fleet_api/src/api/common_api.py
  deploy/test-environments/fleet_api/src/configuration_fleet.py
  deploy/test-environments/fleet_api/src/install_cspm_azure_integration.py
Labels: backport-v8.12.0

#1646 [updatecli] Update to elastic/beats@cc8f5a109744
  cloudbeat.reference.yml
  cloudbeat.yml
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#1645 [updatecli] Update Golang version to 1.21.5
  .go-version
  bin/.go-1.21.5.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: backport-skip, automation, dependency, go

#1647 [updatecli] Update to elastic/beats@07392e331b2f
  cloudbeat.reference.yml
  cloudbeat.yml
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#1644 [updatecli] Update Golang version to 1.21.5
  .go-version
  bin/.go-1.21.5.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: backport-skip, automation, dependency, go

#1653 Temporary disable Azure steps
  .github/workflows/test-environment.yml
  tests/integration/tests/test_sanity_checks.py
Labels: backport-skip

#1650 [Release] Update version to 8.11.4
  version/version.go
Labels: team:automation, release

#1649 RULES.md collapsible CIS sections
  security-policies/RULES.md
  security-policies/dev/update_rule_status.py
  security-policies/poetry.lock
Labels: backport-skip

#1655 Fixing Azure deployment
  .github/workflows/test-environment.yml
  deploy/test-environments/fleet_api/src/configuration_fleet.py
  deploy/test-environments/fleet_api/src/install_cspm_azure_integration.py
  tests/integration/tests/test_sanity_checks.py
Labels: backport-v8.12.0

#1604 Add ECS orchestrator fields
  dataprovider/providers/k8s/data_provider.go
  dataprovider/providers/k8s/data_provider_test.go
  resources/fetching/fetchers/k8s/kube_provider.go
Labels: backport-skip

#1652 Azure Assets Enricher
  resources/fetching/fetchers/azure/assets_enricher.go
  resources/fetching/fetchers/azure/assets_enricher_storage_account.go
  resources/fetching/fetchers/azure/assets_enricher_storage_account_test.go
  resources/fetching/fetchers/azure/assets_fetcher.go
  resources/fetching/fetchers/azure/assets_fetcher_test.go
Labels: backport-skip

#1657 golangci-lint: Make unused config stricter
  .golangci.yaml
  dataprovider/providers/cloud/data_provider.go
  dataprovider/providers/cloud/data_provider_test.go
  dataprovider/providers/cloud/option.go
  dataprovider/providers/k8s/data_provider.go
  dataprovider/providers/k8s/data_provider_test.go
  dataprovider/providers/k8s/option.go
  evaluator/debug_logger/factory.go
  evaluator/debug_logger/plugin.go
  flavors/benchmark/aws.go
  flavors/benchmark/aws_org.go
  flavors/benchmark/azure.go
  flavors/benchmark/gcp.go
  flavors/benchmark/k8s_helper.go
  flavors/vulnerability.go
  launcher/launcher_test.go
  processor/add_cluster_id/add_cluster_id.go
  processor/add_cluster_id/add_cluster_id_test.go
  resources/fetching/condition/is_leader.go
  resources/fetching/fetchers/aws/network_fetcher.go
  resources/fetching/fetchers/aws/network_fetcher_test.go
  resources/fetching/fetchers/azure/batch_fetcher_test.go
  resources/fetching/manager/manager_test.go
  resources/fetching/preset/aws_preset.go
  resources/fetching/preset/eks_preset.go
  resources/fetching/preset/k8s_preset.go
  resources/fetching/registry/registry_test.go
  resources/providers/awslib/cached_region_selector.go
  resources/providers/awslib/cached_region_selector_test.go
  resources/providers/awslib/cloudwatch/cloudwatch.go
  resources/providers/awslib/cloudwatch/logs/logs.go
  resources/providers/awslib/cloudwatch/logs/provider.go
  resources/providers/awslib/cloudwatch/logs/provider_test.go
  resources/providers/awslib/cloudwatch/provider.go
  resources/providers/awslib/cloudwatch/provider_test.go
  resources/providers/awslib/ec2/provider.go
  resources/providers/awslib/ec2/provider_test.go
  resources/providers/awslib/ec2/volume.go
  resources/providers/awslib/securityhub/provider.go
  resources/providers/awslib/securityhub/provider_test.go
  resources/providers/awslib/sns/provider.go
  resources/providers/awslib/sns/provider_test.go
  resources/providers/awslib/sns/sns.go
  uniqueness/leaderelection_test.go
Labels: backport-skip, technical debt

#1637 Azure CIS 6.1
  resources/fetching/fetcher.go
  resources/fetching/fetchers/azure/assets_enricher.go
  resources/fetching/fetchers/azure/assets_enrincher_vm_nsg.go
  resources/fetching/fetchers/azure/assets_enrincher_vm_nsg_test.go
  resources/fetching/fetchers/azure/assets_fetcher.go
  resources/providers/azurelib/inventory/asset.go
  security-policies/README.md
  security-policies/RULES.md
  security-policies/bundle/compliance/cis_azure/rules/cis_6_1/data.yaml
  security-policies/bundle/compliance/cis_azure/rules/cis_6_1/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_6_1/test.rego
  security-policies/bundle/compliance/cis_azure/test_data.rego
Labels: backport-skip

#1658 validate mocks: Check for untracked files as well
  justfile
  resources/fetching/fetchers/azure/mock_assets_enricher.go
Labels: backport-skip, technical debt

#1660 Clean up Azure Classical VMS
  resources/fetching/fetcher.go
  resources/fetching/fetchers/azure/assets_fetcher.go
  resources/providers/azurelib/inventory/asset.go
Labels: backport-skip

#1673 Comment out flakky test until we fix it
  flavors/publisher_test.go
Labels: backport-skip

#1674 Skip long tests when -short flag is set
  .pre-commit-config.yaml
  evaluator/opa_test.go
  flavors/benchmark/aws_org_test.go
  flavors/benchmark/aws_test.go
  flavors/benchmark/builder/benchmark_test.go
  flavors/benchmark/builder/builder_test.go
  flavors/benchmark/builder/k8s_test.go
  flavors/benchmark/eks_test.go
  flavors/benchmark/k8s_test.go
  flavors/publisher_test.go
  flavors/repeater_test.go
  launcher/launcher_test.go
  resources/fetching/cycle/cache_test.go
  resources/fetching/fetchers/k8s/kube_fetcher_test.go
  resources/fetching/manager/manager_test.go
  resources/fetching/preset/aws_org_preset_test.go
  resources/providers/awslib/cached_region_selector_test.go
  resources/providers/azurelib/governance/management_group_test.go
  resources/utils/testhelper/helper.go
  resources/utils/testhelper/helper_test.go
  uniqueness/leaderelection_test.go
  vulnerability/events_creator_test.go
  vulnerability/fetcher_test.go
  vulnerability/replicator_test.go
  vulnerability/runner_test.go
  vulnerability/verifier_test.go
  vulnerability/worker_test.go
Labels: backport-skip, technical debt

#1676 [updatecli] Update to elastic/beats@6759826fc71a
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#1677 [updatecli] Update to elastic/beats@900137649bcc
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#1662 Azure: Fix wrong usage of subscription ID
  .golangci.yaml
  resources/fetching/fetchers/azure/assets_enricher_storage_account_test.go
  resources/fetching/fetchers/azure/assets_fetcher.go
  resources/fetching/fetchers/azure/assets_fetcher_test.go
  resources/fetching/fetchers/azure/batch_fetcher.go
  resources/fetching/fetchers/azure/batch_fetcher_test.go
  resources/fetching/fetchers/azure/insights_batch_fetcher_test.go
  resources/providers/azurelib/governance/management_group.go
  resources/providers/azurelib/governance/management_group_test.go
Labels: backport-v8.12.0

#1648 [updatecli] Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.aws-iam-authenticator-0.6.14.pkg
  bin/.elastic-package-0.95.0.pkg
  bin/.gcloud-457.0.0.pkg
  bin/.gh-2.40.1.pkg
  bin/.jq-1.7.1.pkg
  bin/.pre-commit-3.6.0.pkg
  bin/.regal-0.14.0.pkg
  bin/.yq-4.40.5.pkg
  bin/aws-iam-authenticator
  bin/bq
  bin/docker-credential-gcloud
  bin/elastic-package
  bin/gcloud
  bin/gh
  bin/git-credential-gcloud.sh
  bin/gsutil
  bin/jq
  bin/pre-commit
  bin/regal
  bin/yq
  security-policies/.regal/config.yaml
  security-policies/bundle/compliance/main.rego
Labels: backport-skip, automation, dependency

#1686 updatecli: Update go mod dependencies
  .ci/updatecli/scripts/update-mods.sh
  .ci/updatecli/updatecli.d/update-mods.yml
  .github/workflows/updatecli.yml
Labels: backport-skip, automation, dependency, go, technical debt

#1694 updatecli: Run cron job earlier
  .github/workflows/updatecli.yml
Labels: backport-skip, automation

#1664 Add agentless CSPM AWS findings assertion in serverless mode
  .github/workflows/test-environment.yml
  .github/workflows/upgrade-environment.yml
  deploy/test-environments/fleet_api/src/configuration_fleet.py
  deploy/test-environments/fleet_api/src/install_agentless_integrations.py
  tests/commonlib/agents_map.py
  tests/configuration.py
  tests/conftest.py
  tests/integration/tests/test_sanity_checks.py
  tests/poetry.lock
Labels: backport-skip

#1697 update-mods.sh: Break after 5 hours
  .ci/updatecli/scripts/update-mods.sh
Labels: backport-skip, automation, dependency, technical debt

#1700 [updatecli] Update hermit and pre-commit dependencies
  bin/.gcloud-458.0.0.pkg
  bin/bq
  bin/docker-credential-gcloud
  bin/gcloud
  bin/git-credential-gcloud.sh
  bin/gsutil
Labels: backport-skip, automation, dependency

#1701 chore: Update aws-sdk-go dependencies
  go.mod
  go.sum
  resources/providers/awslib/s3/provider_test.go
Labels: backport-skip, dependency, go, technical debt

#1706 Run CNVM-CI post-merge
  .github/workflows/cnvm-ci.yml
Labels: backport-skip

#1670 golangci: Enable revive linter
  .golangci.yaml
  flavors/benchmark/azure.go
  flavors/benchmark/builder/data_provider.go
  flavors/benchmark/builder/id_provider.go
  flavors/publisher_test.go
  launcher/launcher_test.go
  resources/fetching/fetchers/aws/elb_fetcher.go
  resources/fetching/preset/aws_org_preset_test.go
  resources/providers/awslib/cached_region_selector.go
  resources/providers/awslib/ec2/nacl.go
  resources/providers/awslib/ecr/provider.go
  resources/providers/awslib/multi_region.go
  resources/providers/awslib/multi_region_test.go
Labels: backport-skip

#1704 TestLauncherStopTimeout: Increase post-grace sleep duration
  launcher/launcher_test.go
Labels: backport-skip

#1672 Dependabot: Group download/upload artifact actions
  .github/dependabot.yml
Labels: backport-skip, automation, dependency

#1712 revive: Enable unhandled-error
  .golangci.yaml
Labels: backport-skip

#1709 revive: Enable unexported-naming and unexported-return
  .golangci.yaml
  dataprovider/enrich.go
  dataprovider/providers/k8s/id_provider.go
  dataprovider/providers/k8s/id_provider_test.go
  flavors/benchmark/aws_org_test.go
  flavors/benchmark/k8s_helper.go
  resources/fetching/fetchers/k8s/file_system_fetcher_test.go
Labels: backport-skip

#1708 revive: Enable use-any rule
  .golangci.yaml
  dataprovider/enrich_test.go
  dataprovider/providers/k8s/data_provider_test.go
  deploy/cloudformation/config.go
  evaluator/debug_logger/factory.go
  evaluator/debug_logger/plugin.go
  evaluator/evaluator.go
  evaluator/logger.go
  evaluator/logger_test.go
  evaluator/opa.go
  evaluator/opa_test.go
  flavors/benchmark/builder/builder_test.go
  resources/fetching/fetcher.go
  resources/fetching/fetchers/aws/ecr_fetcher.go
  resources/fetching/fetchers/aws/elb_fetcher.go
  resources/fetching/fetchers/aws/iam_fetcher.go
  resources/fetching/fetchers/aws/iam_fetcher_test.go
  resources/fetching/fetchers/aws/kms_fetcher.go
  resources/fetching/fetchers/aws/logging_fetcher.go
  resources/fetching/fetchers/aws/network_fetcher.go
  resources/fetching/fetchers/aws/rds_fetcher.go
  resources/fetching/fetchers/aws/s3_fetcher.go
  resources/fetching/fetchers/azure/assets_fetcher_test.go
  resources/fetching/fetchers/azure/batch_fetcher_test.go
  resources/fetching/fetchers/gcp/assets_fetcher.go
  resources/fetching/fetchers/gcp/assets_fetcher_test.go
  resources/fetching/fetchers/k8s/file_system_fetcher.go
  resources/fetching/fetchers/k8s/kube_fetcher_test.go
  resources/fetching/fetchers/k8s/kube_provider.go
  resources/fetching/fetchers/k8s/process_fetcher.go
  resources/fetching/fetchers/k8s/process_fetcher_test.go
  resources/fetching/preset/aws_org_preset_test.go
  resources/fetching/registry/registry_test.go
  resources/providers/awslib/aws_test.go
  resources/providers/awslib/iam/iam.go
  resources/providers/awslib/iam/policy.go
  resources/providers/awslib/iam/policy_test.go
  resources/providers/awslib/multi_region.go
  resources/providers/azurelib/inventory/provider_test.go
  resources/utils/user/user.go
  scripts/mage/update.go
  transformer/events_creator_test.go
  vulnerability/events_creator.go
Labels: backport-skip

#1711 revive: Enable redundant-import-alias
  .golangci.yaml
  dataprovider/providers/k8s/cluster_name_provider_test.go
  flavors/benchmark/k8s_helper.go
  processor/add_cluster_id/cluster_helper_test.go
  resources/fetching/fetchers/aws/ecr_fetcher.go
  resources/fetching/fetchers/aws/ecr_fetcher_test.go
  resources/fetching/fetchers/aws/elb_fetcher_test.go
  resources/fetching/fetchers/k8s/kube_fetcher_test.go
  uniqueness/leaderelection.go
  uniqueness/leaderelection_test.go
Labels: backport-skip

#1707 update-mods.sh: Build opa bundle first
  .ci/updatecli/scripts/update-mods.sh
  .github/workflows/unit-test.yml
  evaluator/opa_test.go
Labels: backport-skip, dependency, technical debt

#1714 revive: Enable indent-error-flow rule
  .golangci.yaml
  resources/providers/awslib/iam/access_analyzer_test.go
  resources/providers/azurelib/inventory/provider_test.go
Labels: backport-skip

#1691 Add CIS Azure 6.4
  security-policies/README.md
  security-policies/RULES.md
  security-policies/bundle/compliance/cis_azure/rules/cis_6_4/data.yaml
  security-policies/bundle/compliance/cis_azure/rules/cis_6_4/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_6_4/test.rego
Labels: backport-skip

#1687 Add wait step to avoid too tight publishing period
  flavors/publisher_test.go
Labels: backport-skip

#1688 pre-commit: black: auto-reformat
  .pre-commit-config.yaml
  pyproject.toml
Labels: backport-skip

#1713 golangci: Enable gomodguard
  .golangci.yaml
  go.mod
  resources/fetching/fetchers/aws/ecr_fetcher.go
  resources/fetching/fetchers/aws/elb_fetcher.go
  resources/fetching/fetchers/aws/iam_fetcher_test.go
  resources/fetching/fetchers/aws/logging_fetcher_test.go
  resources/fetching/fetchers/aws/network_fetcher_test.go
  resources/fetching/fetchers/k8s/file_system_fetcher.go
  resources/fetching/fetchers/k8s/file_system_fetcher_test.go
  resources/providers/aws_cis/logging/provider_test.go
  resources/providers/awslib/iam/user.go
  resources/providers/awslib/iam/user_test.go
  resources/utils/user/user.go
Labels: backport-skip, dependency, go

#1719 update-mods.sh: Revert time-out hack
  .ci/updatecli/scripts/update-mods.sh
Labels: backport-skip

#1720 revive: Enable cognitive-complexity and cyclomatic
  .golangci.yaml
  resources/fetching/preset/aws_org_preset_test.go
  resources/providers/awslib/cluster_name_provider.go
  resources/providers/awslib/iam/user.go
  resources/utils/user/user.go
Labels: backport-skip

#1721 revive: Enable early-return
  .golangci.yaml
  resources/providers/azurelib/inventory/provider.go
  resources/providers/gcplib/auth/credentials.go
Labels: backport-skip

#1723 revive: Enable confusing-results and function-result-limit
  .golangci.yaml
  flavors/benchmark/aws.go
  flavors/benchmark/aws_org.go
  flavors/benchmark/azure.go
  flavors/benchmark/eks.go
  flavors/benchmark/gcp.go
  flavors/benchmark/k8s.go
  resources/providers/gcplib/inventory/provider.go
  vulnerability/fetcher_test.go
Labels: backport-skip

#1724 revive: Split rules in sections and add comments
  .golangci.yaml
Labels: backport-skip

#1702 Serverless weekly sanity test
  .github/workflows/weekly-serverless.yml
Labels: backport-skip

#1725 Comment flaky telemetry test
  .github/workflows/test-environment.yml
  deploy/test-environments/fleet_api/pyproject.toml
  tests/integration/tests/test_sanity_checks.py
  tests/integration/tests/test_sanity_telemetry.py
  tests/pyproject.toml
Labels: backport-skip

#1728 Enable prealloc linter
  .golangci.yaml
  deploy/cloudformation/gomain.go
  evaluator/logger.go
  flavors/benchmark/aws_org.go
  resources/fetching/registry/registry.go
  resources/providers/aws_cis/logging/provider.go
  resources/providers/awslib/cloudtrail/provider.go
  resources/providers/awslib/ec2/provider.go
  resources/providers/awslib/iam/policy.go
  resources/providers/awslib/iam/user.go
  resources/providers/awslib/rds/provider.go
  resources/providers/awslib/rds/provider_test.go
  resources/providers/gcplib/inventory/provider.go
  resources/utils/testhelper/helper.go
Labels: backport-skip

#1730 feat: update jwx pkg
  go.mod
  go.sum
Labels: backport-v8.11.0

#1738 [updatecli] Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#1680 [Upgrade workflow] Add input param for released version
  .github/workflows/upgrade-environment.yml
  dev-docs/Cloud-Env-Upgrade.md
Labels: backport-skip

#1599 Add slack notification
  .ci/scripts/prepare_slack_data.py
  .github/actions/slack-notification/README.md
  .github/actions/slack-notification/action.yml
  .github/actions/slack-notification/slack_payload.py
  .github/workflows/destroy-environment.yml
  .github/workflows/test-environment.yml
  .pre-commit-config.yaml
Labels: backport-skip

#1726 Fix GCP LogMetric asset
  resources/providers/gcplib/inventory/asset.go
Labels: backport-skip

#1705 fix CIS GCP 1.5
  security-policies/bundle/compliance/cis_gcp/rules/cis_1_5/rule.rego
  security-policies/bundle/compliance/cis_gcp/rules/cis_1_5/test.rego
  security-policies/bundle/compliance/policy/gcp/iam/ensure_not_admin_roles.rego
Labels: gcp, backport-v8.12.0

#1715 Azure section 9 rule fixes
  resources/fetching/fetchers/azure/assets_fetcher_test.go
  resources/fetching/fetchers/azure/batch_fetcher_test.go
  resources/providers/azurelib/inventory/asset.go
  resources/providers/azurelib/inventory/provider.go
  resources/providers/azurelib/inventory/provider_test.go
  security-policies/README.md
  security-policies/RULES.md
  security-policies/bundle/compliance/cis_azure/rules/cis_9_10/data.yaml
  security-policies/bundle/compliance/cis_azure/rules/cis_9_10/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_9_10/test.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_9_2/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_9_2/test.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_9_3/data.yaml
  security-policies/bundle/compliance/cis_azure/rules/cis_9_3/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_9_3/test.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_9_5/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_9_5/test.rego
  security-policies/bundle/compliance/cis_azure/test_data.rego
  security-policies/bundle/compliance/policy/azure/data_adapter.rego
Labels: backport-v8.12.0

#1671 [CIS] Azure 3.11
  go.mod
  go.sum
  resources/fetching/fetchers/azure/assets_enricher_storage_account.go
  resources/fetching/fetchers/azure/assets_enricher_storage_account_test.go
  resources/fetching/fetchers/azure/assets_enrincher_vm_nsg.go
  resources/fetching/fetchers/azure/assets_enrincher_vm_nsg_test.go
  resources/fetching/fetchers/azure/assets_fetcher_test.go
  resources/providers/azurelib/inventory/asset.go
  resources/providers/azurelib/inventory/mock_provider_api.go
  resources/providers/azurelib/inventory/provider.go
  resources/providers/azurelib/inventory/storage.go
  resources/providers/azurelib/inventory/storage_test.go
  resources/providers/azurelib/mock_provider_api.go
  resources/providers/azurelib/provider.go
  resources/utils/maps/maps.go
  security-policies/RULES.md
  security-policies/bundle/compliance/cis_azure/rules/cis_3_11/data.yaml
  security-policies/bundle/compliance/cis_azure/rules/cis_3_11/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_3_11/test.rego
Labels: backport-skip

#1747 add parent to error log
  resources/providers/gcplib/inventory/provider.go
Labels: backport-skip

#1755 Add path to times stat operation non permitted error
  resources/fetching/fetchers/k8s/file_system_fetcher.go
Labels: backport-skip
