Repository elastic/cloudbeat, pull requests merged in 2023-05, with the labels that each got.

#918 Add pagination in RDS provider to describe DB instances
  resources/providers/awslib/rds/provider.go
Labels: backport-skip

#917 Document ways to run vulnerability management
  deploy/cloudformation/README.md
  deploy/vulnerability/README.md
Labels: backport-skip

#891 aws functional tests documentation
  tests/README.md
Labels: backport-skip

#860 [Release] Update version to 8.7.2
  version/version.go
Labels: team:automation, release

#923 [CNVM] Update cloudformation ec2 instance type
  deploy/cloudformation/elastic-agent-ec2.yml
Labels: backport-skip

#916 access_analyzer: Use arrays instead of map
  resources/fetchers/iam_factory.go
  resources/fetchers/iam_fetcher_test.go
  resources/providers/awslib/iam/access_analyzer.go
  resources/providers/awslib/iam/access_analyzer_test.go
  resources/providers/awslib/iam/iam.go
  resources/providers/awslib/iam/mock_access_analyzer_client.go
Labels: backport-v8.8.0

#911 Trivy bump to 0.41
  go.mod
  go.sum
  vulnerability/runner.go
  vulnerability/scanner.go
Labels: backport-skip

#912 Update CNVM findings schema
  bin/.elastic-package-0.78.0.pkg
  bin/elastic-package
  vulnerability/events_creator.go
Labels: backport-skip

#939 Accept ElasticArtifactServer as a CloudFormation parameter
  deploy/cloudformation/README.md
  deploy/cloudformation/config.go
  deploy/cloudformation/dev/modifier.go
  deploy/cloudformation/elastic-agent-ec2.yml
  deploy/cloudformation/gomain.go
Labels: backport-v8.8.0

#938 Terraform version upgrade
  bin/.terraform-1.4.6.pkg
  bin/terraform
Labels: backport-skip, Team:Cloud Security

#943 Set default value to CloudFormation param ElasticArtifactServer
  deploy/cloudformation/elastic-agent-ec2.yml
Labels: backport-skip

#947 Add a catalog info file
  catalog-info.yaml
Labels: backport-skip

#901 fetchers: Correctly use sub-tests
  resources/fetchers/iam_fetcher_test.go
  resources/fetchers/kms_fetcher_test.go
  resources/fetchers/rds_fetcher_test.go
  resources/fetchers/s3_fetcher_test.go
Labels: backport-skip

#946 Enforce deployment name when using terraform
  deploy/cloud/README.md
  deploy/cloud/main.tf
  deploy/cloud/modules/provision-eks-cluster/eks-cluster.tf
  deploy/cloud/modules/provision-eks-cluster/main.tf
  deploy/cloud/modules/provision-eks-cluster/oidc.tf
  deploy/cloud/modules/provision-eks-cluster/security-groups.tf
  deploy/cloud/modules/provision-eks-cluster/variables.tf
  deploy/cloud/modules/provision-eks-cluster/vpc.tf
  deploy/cloud/variables.tf
Labels: backport-skip

#956 cloudformation: Change dev deployment script
  .github/workflows/k8s-ci.yml
  .pre-commit-config.yaml
  Makefile
  bin/.yq@4.33.pkg
  bin/yq
  deploy/cloudformation/.gitignore
  deploy/cloudformation/dev/modifier.go
  deploy/cloudformation/elastic-agent-ec2.yml
  deploy/cloudformation/godev.go
  deploy/cloudformation/gomain.go
  deploy/cloudformation/mock_dev_modifier.go
  dev-docs/cspm-on-cloud-deployment.md
  go.mod
  go.sum
Labels: backport-skip

#960 Fix eks config 1
  tests/configuration.py
  tests/deploy/aws/eks_config/test-eks-config-1-node-1-10-kubelet-args.conf
  tests/deploy/aws/eks_config/test-eks-config-1-node-2-10-kubelet-args.conf
  tests/product/tests/data/aws/managed_services_test_cases.py
Labels: backport-skip

#904 Add missing functional tests for CIS AWS 1.16, 1.17, 1.20
  tests/product/tests/data/aws/aws_iam_test_cases.py
Labels: backport-skip

#962 CloudFormation script: Fix artifact server not being optional
  deploy/cloudformation/config.go
  deploy/cloudformation/gomain.go
Labels: backport-skip

#971 S3 provider handles missing public access block config better
  resources/providers/awslib/s3/provider.go
  version/policy.go
Labels: backport-v8.8.0

#961 CloudFormation: Add CSPM integration option
  deploy/cloudformation/README.md
  deploy/cloudformation/config.go
  deploy/cloudformation/elastic-agent-ec2.yml
  deploy/cloudformation/gomain.go
Labels: backport-skip

#975 CloudFormation: Use GH actions syntax for conditional upload
  .github/workflows/publish-artifacts.yml
Labels: backport-skip

#976 CloudFormation: Upload to path without "vuln-mgmt"
  .github/workflows/publish-artifacts.yml
Labels: backport-skip

#977 Update go 1.20
  .github/workflows/cloudbeat-ci.yml
  .github/workflows/unit-test.yml
  .go-version
  bin/.go-1.20.4.pkg
  bin/.golangci-lint-1.52.2.pkg
  bin/go
  bin/gofmt
  bin/golangci-lint
  docs/version.asciidoc
  go.mod
Labels: backport-skip

#978 CloudFormation: Remove duplicate s3 upload
  .github/workflows/publish-artifacts.yml
Labels: backport-skip

#959 Vulnerabilities database cache management
  vulnerability/db.go
  vulnerability/runner.go
  vulnerability/scanner.go
  vulnerability/worker.go
Labels: backport-skip

#979 Update EKS deployment
  deploy/eks/Readme.md
  deploy/eks/simple-cluster.yml
Labels: backport-skip

#944 Buildkite migration
  .buildkite/README.md
  .buildkite/pipeline.yml
  .buildkite/scripts/package.sh
  .buildkite/scripts/publish.sh
  .ci/jobs/cloudbeat-mbp.yml
  .ci/jobs/cloudbeat.yml
  .ci/jobs/defaults.yml
  .ci/scripts/intake.sh
  .ci/scripts/integration-tests.sh
  .ci/scripts/rm-docker.sh
  .ci/scripts/unit-test.sh
  .editorconfig
  .github/CODEOWNERS
  Jenkinsfile
  Makefile
  bin/hermit.hcl
  justfile
  scripts/connect_kind.sh
  scripts/make/common.bash
  scripts/validate-mocks.sh
Labels: backport-skip

#1002 Create a branch filter for running a builkite pipeline
  README.md
  catalog-info.yaml
Labels: backport-skip

#981 k8s CIS 1.1.19: Scan pki/ folder recursively
  _meta/config/cloudbeat.common.yml.tmpl
  cloudbeat.reference.yml
  cloudbeat.yml
  deploy/kustomize/overlays/cloudbeat-vanilla-nocert/cloudbeat.yml
  tests/commonlib/io_utils.py
  tests/deploy/cloudbeat-pytest.yml
  tests/deploy/k8s-cloudbeat-tests/templates/cloudbeat-ds.yml
  tests/deploy/sa-agent-pytest.yml
  tests/product/tests/conftest.py
  tests/product/tests/data/file_system/file_system_test_cases.py
Labels: backport-skip

#899 [Release] Update version to 8.8.1
  version/version.go
Labels: team:automation, release

#984 Vulnerability management volume types matrix deployment
  deploy/cloudformation/ec2-types.yml
Labels: backport-skip

#1009 Revert "Vulnerabilities database cache management"
  vulnerability/db.go
  vulnerability/runner.go
  vulnerability/scanner.go
  vulnerability/worker.go
Labels: backport-skip

#1019 Revert "Create a branch filter for running a builkite pipeline"
  catalog-info.yaml
Labels: backport-skip

#1021 Test EC2 types CFT allow to encrypt instances
  deploy/cloudformation/ec2-types.yml
Labels: backport-skip

#1017 Add branch configuration to buildkite pipeline
  catalog-info.yaml
Labels: backport-skip
