Repository elastic/cloudbeat, pull requests merged in 2024-09, with the labels that each got.

#2473 [updatecli] Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2450 Bump armsecurity
  go.mod
  go.sum
  internal/resources/providers/azurelib/inventory/mock_security_client_wrapper.go
  internal/resources/providers/azurelib/inventory/security_provider.go
  internal/resources/providers/azurelib/inventory/security_provider_test.go
  internal/resources/providers/azurelib/provider.go
  security-policies/bundle/compliance/cis_azure/rules/cis_2_1_20/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_2_1_20/test.rego
Labels: backport-skip

#2472 [updatecli] Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.aws-iam-authenticator-0.6.26.pkg
  bin/.gcloud-490.0.0.pkg
  bin/.just-1.35.0.pkg
  bin/.opa-0.68.0.pkg
  bin/aws-iam-authenticator
  bin/bq
  bin/docker-credential-gcloud
  bin/gcloud
  bin/git-credential-gcloud.sh
  bin/gsutil
  bin/just
  bin/opa
Labels: backport-skip, automation, dependency

#2470 [updatecli] Update to elastic/beats@30320a3bfcfc
  go.mod
  go.sum
  internal/beater/beater.go
Labels: backport-skip, automation, dependency, go

#2457 Add workflow to deploy environment with CDR infrastructure
  .ci/scripts/remote_setup.sh
  .ci/scripts/set_cloud_env_params.sh
  .github/workflows/cdr-infra.yml
  .github/workflows/test-environment.yml
  deploy/cloud/modules/azure/vm/main.tf
  deploy/cloud/modules/gcp/vm/main.tf
  deploy/cloud/modules/gcp/vm/variables.tf
  deploy/test-environments/main.tf
  deploy/test-environments/output.tf
  deploy/test-environments/variables.tf
  dev-docs/Cloud-Env-Testing.md
  tests/integrations_setup/install_az_activity_logs_integration.py
  tests/integrations_setup/install_cloudtrail_integration.py
  tests/integrations_setup/install_gcp_audit_logs_integration.py
Labels: backport-skip

#2474 Fix workflow run-name
  .github/workflows/cdr-infra.yml
Labels: backport-skip, Team:Cloud Security, automation

#2476 Bumping k8s.io/kubernetes to v1.31.0
  go.mod
  go.sum
Labels: backport-skip

#2460 GCP Assets Inventory integration fetcher
  internal/flavors/assetinventory/strategy.go
  internal/inventory/ASSETS.md
  internal/inventory/asset.go
  internal/inventory/gcpfetcher/fetcher_assets.go
  internal/inventory/gcpfetcher/fetcher_assets_test.go
  internal/inventory/gcpfetcher/gcpfetchers.go
  internal/inventory/gcpfetcher/mock_inventory_provider.go
Labels: backport-skip

#2478 Add more GCP assets inventory classifications
  internal/inventory/ASSETS.md
  internal/inventory/asset.go
  internal/inventory/gcpfetcher/fetcher_assets.go
  internal/resources/providers/gcplib/inventory/asset.go
Labels: backport-skip

#2444 Bump to go 1.23
  .go-version
  bin/.go-1.23.0.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
  go.mod
  scripts/update_assets_md/go.mod
Labels: backport-skip

#2488 Update /tests dependencies and fix docker+http issue
  tests/poetry.lock
  tests/pyproject.toml
Labels: backport-skip

#2489 Update config for 8.x branch
  .buildkite/pipeline.yml
  .mergify.yml
Labels: backport-skip

#2490 Bump version 9.0.0
  deploy/azure/ARM-for-organization-account.dev.json
  deploy/azure/ARM-for-organization-account.json
  deploy/azure/ARM-for-single-account.dev.json
  deploy/azure/ARM-for-single-account.json
  version/version.go
Labels: backport-skip

#2494 [Agentless][Tests] Fix environment creation
  tests/integrations_setup/install_agentless_integrations.py
Labels: backport-v8.x

#2487 [Asset Inventory][AWS] Add integration test cases for implemented assets
  internal/inventory/awsfetcher/fetcher_lambda.go
  tests/product/tests/data/aws_asset_inventory/test_cases.py
Labels: backport-skip

#2485 [updatecli] Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.elastic-package-0.103.0.pkg
  bin/.gcloud-491.0.0.pkg
  bin/.regal-0.26.1.pkg
  bin/bq
  bin/docker-credential-gcloud
  bin/elastic-package
  bin/gcloud
  bin/git-credential-gcloud.sh
  bin/gsutil
  bin/regal
Labels: automation, dependency, backport-v8.x

#2503 Change from backport-skip to backport-v8.x labels on updatecli and dependabot
  .ci/updatecli/updatecli.d/update-golang.yml
  .ci/updatecli/updatecli.d/update-hermit.yml
  .ci/updatecli/updatecli.d/update-mods.yml
  .github/dependabot.yml
Labels: backport-v8.x

#2484 [updatecli] Update to elastic/beats@9f2f7445453b
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2486 [updatecli] Update golang mod dependencies
  go.mod
  go.sum
Labels: automation, dependency, go, backport-v8.x

#2526 Add missing workflows in 8.x
  .github/workflows/arm-template-lint.yml
  .github/workflows/ci-pull_request.yml
  .github/workflows/ci.yml
  .github/workflows/cloudformation-ci.yml
  .github/workflows/eks-ci.yml
  .github/workflows/packaging.yml
  .github/workflows/unit-test.yml
Labels: backport-v8.x

#2528 Fix GCP asset inventory CI
  .github/actions/gcp-asset-inventory-ci/action.yml
  .github/actions/wait-for-es-data/action.yml
Labels: backport-v8.x

#2536 [updatecli] Update golang mod dependencies
  go.mod
  go.sum
Labels: automation, dependency, go, backport-v8.x

#2535 [updatecli] Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.awscli-2.17.51.pkg
  bin/.elastic-package-0.104.0.pkg
  bin/.gcloud-492.0.0.pkg
  bin/.gh-2.56.0.pkg
  bin/.golangci-lint-1.61.0.pkg
  bin/.regal-0.26.2.pkg
  bin/aws
  bin/aws_completer
  bin/bq
  bin/docker-credential-gcloud
  bin/elastic-package
  bin/gcloud
  bin/gh
  bin/git-credential-gcloud.sh
  bin/golangci-lint
  bin/gsutil
  bin/regal
Labels: automation, dependency, backport-v8.x

#2534 [updatecli] Update to elastic/beats@6ab7467ce404
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2540 Handle password policy not found error
  internal/resources/providers/awslib/iam/password_policy.go
  internal/resources/providers/awslib/iam/password_policy_test.go
Labels: backport-v8.x

#2531 [updatecli] Update Golang version to 1.23.1
  .go-version
  bin/.go-1.23.1.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: automation, dependency, go, backport-v8.x

#2553 Fix `too-many-positional-arguments` error
  tests/pylintrc
Labels: backport-v8.x

#2550 [updatecli] Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.aws-iam-authenticator-0.6.27.pkg
  bin/.gcloud-493.0.0.pkg
  bin/.gh-2.57.0.pkg
  bin/.regal-0.27.0.pkg
  bin/aws-iam-authenticator
  bin/bq
  bin/docker-credential-gcloud
  bin/gcloud
  bin/gh
  bin/git-credential-gcloud.sh
  bin/gsutil
  bin/regal
Labels: automation, dependency, backport-v8.x

#2549 [updatecli] Update to elastic/beats@7720c900f893
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2557 fix buildkite settings to include 8.x branch
  catalog-info.yaml
Labels: backport-v8.x

#2543 bump hermit to 9.0.0
  bin/hermit.hcl
Labels: backport-skip

#2530 Fix GCP deployment manager formatting
  .github/workflows/test-gcp-dm.yml
  deploy/deployment-manager/deploy_service_account.sh
Labels: backport-v8.x
