Repository elastic/cloudbeat, pull requests merged in 2024-12, with the labels that each got.

#2784 Fix SNS topics fetch panics on errors
  internal/resources/providers/awslib/sns/provider.go
  internal/resources/providers/awslib/sns/provider_test.go
Labels: backport-v8.x, backport-v8.17.0

#2800 [updatecli] main - Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.awscli-2.22.7.pkg
  bin/.gh-2.63.0.pkg
  bin/.golangci-lint-1.62.2.pkg
  bin/aws
  bin/aws_completer
  bin/gh
  bin/golangci-lint
Labels: backport-skip, automation, dependency

#2798 [updatecli] 8.17 - Update to elastic/beats@633e6f687076
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2797 [updatecli] 8.x - Update to elastic/beats@d2493055252b
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2799 [updatecli] main - Update to elastic/beats@ec2f4a8e70a3
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2801 [updatecli] 8.x - Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.awscli-2.22.7.pkg
  bin/.gh-2.63.0.pkg
  bin/.golangci-lint-1.62.2.pkg
  bin/aws
  bin/aws_completer
  bin/gh
  bin/golangci-lint
Labels: backport-skip, automation, dependency

#2654 [Asset Inventory][GCP] Populate `related.entity` field for resources implemented so far
  internal/inventory/asset.go
  internal/inventory/gcpfetcher/fetcher_assets.go
  internal/inventory/gcpfetcher/fetcher_assets_test.go
  internal/inventory/inventory.go
Labels: backport-v8.x

#2818 [updatecli] main - Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.awscli-2.22.12.pkg
  bin/.gh-2.63.2.pkg
  bin/.yq-4.44.6.pkg
  bin/aws
  bin/aws_completer
  bin/gh
  bin/yq
Labels: backport-skip, automation, dependency

#2817 [updatecli] 8.x - Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.awscli-2.22.12.pkg
  bin/.gh-2.63.2.pkg
  bin/.yq-4.44.6.pkg
  bin/aws
  bin/aws_completer
  bin/gh
  bin/yq
Labels: backport-skip, automation, dependency

#2824 Update serverless workflow to use correct stack version
  .github/workflows/weekly-serverless.yml
  tests/integrations_setup/configuration_fleet.py
  tests/integrations_setup/install_agentless_integrations.py
Labels: backport-v8.x

#2813 [updatecli] 8.17 - Update Golang version to 1.23.4
  .go-version
  bin/.go-1.23.4.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: backport-skip, automation, dependency, go

#2812 [updatecli] main - Update Golang version to 1.23.4
  .go-version
  bin/.go-1.23.4.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: backport-skip, automation, dependency, go

#2815 [updatecli] 8.17 - Update to elastic/beats@cd2d8ab340cc
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2811 [updatecli] 8.x - Update Golang version to 1.23.4
  .go-version
  bin/.go-1.23.4.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: backport-skip, automation, dependency, go

#2816 [updatecli] main - Update to elastic/beats@a64168707ade
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2814 [updatecli] 8.x - Update to elastic/beats@424e2b5e595e
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2819 [updatecli] main - Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2833 Overwrite notice to github.com/gocsaf/csaf/v3
  .buildkite/scripts/generate_notice.py
Labels: backport-v8.x

#2841 [updatecli] main - Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2837 [updatecli] 8.17 - Update to elastic/beats@9ea9d467d5a5
  cloudbeat.reference.yml
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2839 [updatecli] main - Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.awscli-2.22.17.pkg
  bin/.gcloud-503.0.0.pkg
  bin/.just-1.38.0.pkg
  bin/aws
  bin/aws_completer
  bin/bq
  bin/docker-credential-gcloud
  bin/gcloud
  bin/git-credential-gcloud.sh
  bin/gsutil
  bin/just
Labels: backport-skip, automation, dependency

#2838 [updatecli] 8.x - Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.awscli-2.22.17.pkg
  bin/.gcloud-503.0.0.pkg
  bin/.just-1.38.0.pkg
  bin/aws
  bin/aws_completer
  bin/bq
  bin/docker-credential-gcloud
  bin/gcloud
  bin/git-credential-gcloud.sh
  bin/gsutil
  bin/just
Labels: backport-skip, automation, dependency

#2836 [updatecli] 8.x - Update to elastic/beats@ce5ddb0a673a
  cloudbeat.reference.yml
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2835 [updatecli] main - Update to elastic/beats@93b018a83621
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2844 downgrade version
  .github/workflows/publish-cloudformation.yml
Labels: backport-v8.x

#2856 [updatecli] main - Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2854 [updatecli] main - Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.aws-iam-authenticator-0.6.29.pkg
  bin/.awscli-2.22.22.pkg
  bin/.elastic-package-0.108.0.pkg
  bin/.gcloud-504.0.1.pkg
  bin/.gh-2.64.0.pkg
  bin/.kind-0.26.0.pkg
  bin/aws
  bin/aws-iam-authenticator
  bin/aws_completer
  bin/bq
  bin/docker-credential-gcloud
  bin/elastic-package
  bin/gcloud
  bin/gh
  bin/git-credential-gcloud.sh
  bin/gsutil
  bin/kind
Labels: backport-skip, automation, dependency

#2855 [updatecli] 8.x - Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2852 [updatecli] main - Update to elastic/beats@2e776c7317a2
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2851 [updatecli] 8.17 - Update to elastic/beats@8b9a76e3db69
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2853 [updatecli] 8.x - Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.aws-iam-authenticator-0.6.29.pkg
  bin/.awscli-2.22.22.pkg
  bin/.elastic-package-0.108.0.pkg
  bin/.gcloud-504.0.1.pkg
  bin/.gh-2.64.0.pkg
  bin/.kind-0.26.0.pkg
  bin/aws
  bin/aws-iam-authenticator
  bin/aws_completer
  bin/bq
  bin/docker-credential-gcloud
  bin/elastic-package
  bin/gcloud
  bin/gh
  bin/git-credential-gcloud.sh
  bin/gsutil
  bin/kind
Labels: backport-skip, automation, dependency

#2850 [updatecli] 8.x - Update to elastic/beats@d6c7b21f4997
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2867 [updatecli] main - Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.awscli-2.22.26.pkg
  bin/aws
  bin/aws_completer
Labels: backport-skip, automation, dependency

#2869 [updatecli] 8.x - Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2865 [updatecli] 8.17 - Update to elastic/beats@e9a656591cf6
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2868 [updatecli] main - Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2866 [updatecli] 8.x - Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.awscli-2.22.26.pkg
  bin/aws
  bin/aws_completer
Labels: backport-skip, automation, dependency

#2864 [updatecli] main - Update to elastic/beats@95a32ed409ab
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2863 [updatecli] 8.x - Update to elastic/beats@614e06077a8b
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go
