Repository elastic/cloudbeat, pull requests merged in 2024-04, with the labels that each got.

#2071 [updatecli] Update to elastic/beats@f871b5c5f76b
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2077 Deprecate unused workflows
  .github/workflows/aws-ci.yml
  .github/workflows/azure-ci.yml
  .github/workflows/cloudbeat-ci.yml
  .github/workflows/cnvm-ci.yml
  .github/workflows/gcp-ci.yml
  .github/workflows/k8s-ci.yml
  .github/workflows/publish-test-results.yml
  .github/workflows/unit-test.yml
Labels: backport-skip

#2076 Bump github.com/moby/buildkit from 0.11.6 to 0.12.5
  go.mod
  go.sum
Labels: backport-skip

#2069 [Release] Update version to 8.13.2
  version/version.go
Labels: team:automation, release

#2084 Update the rerun flaky workflow to also monitor the Tests flow.
  .github/workflows/rerun-flaky-workflows.yml
Labels: backport-skip

#2086 update CNVM timeout
  .github/workflows/ci.yml
Labels: backport-skip

#2087 Update rerun workflow to send Slack notification if event name is not a pull request.
  .github/workflows/rerun-flaky-workflows.yml
Labels: backport-skip

#2085 use CloudAccountMetadata in GCP
  internal/flavors/benchmark/gcp.go
  internal/resources/fetching/fetcher.go
  internal/resources/fetching/fetchers/gcp/assets_fetcher.go
  internal/resources/fetching/fetchers/gcp/log_sink_fetcher.go
  internal/resources/fetching/fetchers/gcp/monitoring_fetcher.go
  internal/resources/fetching/fetchers/gcp/policies_fetcher.go
  internal/resources/fetching/fetchers/gcp/service_usage_fetcher.go
  internal/resources/providers/gcplib/inventory/provider.go
  internal/resources/providers/gcplib/inventory/provider_test.go
Labels: backport-skip

#2092 ci fix: use pr merge commit as base for lint and unittest
  .github/workflows/ci.yml
Labels: backport-skip

#2090 fix GCP fetchers tests
  internal/resources/fetching/fetchers/gcp/assets_fetcher_test.go
  internal/resources/fetching/fetchers/gcp/log_sink_fetcher_test.go
  internal/resources/fetching/fetchers/gcp/monitoring_fetcher_test.go
  internal/resources/fetching/fetchers/gcp/policies_fetcher_test.go
  internal/resources/fetching/fetchers/gcp/service_usage_fetcher_test.go
Labels: backport-skip

#2094 Disable integration tests for Azure 4.4.1
  security-policies/RULES.md
  tests/product/tests/data/azure/azure_database_service_test_cases.py
Labels: backport-skip

#2082 Re-enable some AWS and EKS sanity checks in integration tests
  tests/integration/tests/test_sanity_checks.py
Labels: backport-skip

#2088 [CIS GCP] Add owner label to a deployment manager deployments
  deploy/deployment-manager/deploy.sh
Labels: backport-skip

#2089 Update rerun workflow
  .github/workflows/rerun-flaky-workflows.yml
Labels: backport-skip

#2095 fix panic due to missing logger of aws IdentityProvider
  internal/flavors/asset_inventory.go
  internal/flavors/benchmark/strategy.go
  internal/flavors/benchmark/strategy_test.go
  internal/flavors/posture.go
Labels: backport-v8.13.0

#2105 docs: update docs versions 8.13.2
  version/version.go
Labels: team:automation, release, docs, in progress

#2113 Omit hermit action in merge code
  .github/workflows/ci.yml
Labels: backport-skip

#2116 fix lint step
  .github/workflows/ci.yml
Labels: backport-skip

#2109 Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.elastic-package-0.99.0.pkg
  bin/.gcloud-471.0.0.pkg
  bin/.gh-2.47.0.pkg
  bin/.golangci-lint-1.57.2.pkg
  bin/.just-1.25.2.pkg
  bin/.kind-0.22.0.pkg
  bin/.opa-0.63.0.pkg
  bin/.pre-commit-3.7.0.pkg
  bin/.shellcheck-0.10.0.pkg
  bin/.shfmt-3.8.0.pkg
  bin/.yq-4.43.1.pkg
  bin/bq
  bin/docker-credential-gcloud
  bin/elastic-package
  bin/gcloud
  bin/gh
  bin/git-credential-gcloud.sh
  bin/golangci-lint
  bin/gsutil
  bin/just
  bin/kind
  bin/opa
  bin/pre-commit
  bin/shellcheck
  bin/shfmt
  bin/yq
Labels: backport-skip

#2117 Update slack channel name
  .github/actions/slack-notification/README.md
  .github/actions/slack-notification/action.yml
Labels: backport-skip

#2124 Increase CNVM timeout
  .github/workflows/ci.yml
Labels: backport-skip

#2114 Revert "[CIS GCP] Add owner label to a deployment manager deployments"
  .github/workflows/test-gcp-dm.yml
  deploy/deployment-manager/deploy.sh
Labels: backport-skip

#2130 [pre-commit] use local (hermit) golangci-lint binary
  .pre-commit-config.yaml
Labels: backport-skip

#2123 Cloudformation access key
  .github/workflows/cloudformation-ci.yml
  deploy/aws/cloudbeat-aws.yml
  deploy/cloudformation/elastic-agent-direct-access-key-cspm-organization.yml
  deploy/cloudformation/elastic-agent-direct-access-key-cspm.yml
  scripts/publish_cft.sh
Labels: backport-skip

#2140 Bump cloudbeat version
  .mergify.yml
  deploy/azure/ARM-for-organization-account.dev.json
  deploy/azure/ARM-for-organization-account.json
  deploy/azure/ARM-for-single-account.dev.json
  deploy/azure/ARM-for-single-account.json
  version/version.go
Labels: backport-skip

#2132 ci: extract lint and unittests workflow
  .github/workflows/ci-pull_request.yml
  .github/workflows/ci.yml
Labels: backport-skip

#2126 Add correct host info for cloud provider virtual machines
  _meta/config/processors.yml.tmpl
  cloudbeat.yml
  cmd/root.go
  deploy/aws/cloudbeat-aws.yml
  deploy/azure/cloudbeat-azure.yml
  deploy/gcp/cloudbeat-gcp.yml
  deploy/kustomize/overlays/cloudbeat-aws/cloudbeat.yml
  internal/flavors/posture.go
  internal/resources/fetching/fetchers/azure/assets_fetcher.go
  internal/resources/fetching/fetchers/azure/assets_fetcher_test.go
  internal/resources/fetching/fetchers/gcp/assets_fetcher.go
  internal/resources/fetching/fetchers/gcp/assets_fetcher_test.go
Labels: backport-skip

#2138 Sanity check: CNVM resources must have a `host` section
  tests/integration/tests/test_sanity_checks.py
Labels: backport-skip

#2151 Fix host info for GCP Compute Instances
  internal/resources/fetching/fetchers/gcp/assets_fetcher.go
  internal/resources/fetching/fetchers/gcp/assets_fetcher_test.go
Labels: backport-skip

#2139 Add correct user info for select IAM resources
  internal/resources/fetching/fetchers/aws/iam_fetcher.go
  internal/resources/fetching/fetchers/aws/iam_fetcher_test.go
  internal/resources/fetching/fetchers/azure/assets_fetcher.go
  internal/resources/fetching/fetchers/azure/assets_fetcher_test.go
  internal/resources/fetching/fetchers/gcp/assets_fetcher.go
  internal/resources/fetching/fetchers/gcp/assets_fetcher_test.go
Labels: backport-skip

#2091 Add Lint ARM Templates step
  .github/workflows/arm-template-lint.yml
  deploy/azure/ARM-for-organization-account.dev.json
  deploy/azure/ARM-for-organization-account.json
  deploy/azure/ARM-for-single-account.dev.json
  deploy/azure/ARM-for-single-account.json
Labels: backport-skip

#2155 Update go to v1.22
  .go-version
  bin/.go-1.22.2.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
  go.mod
Labels: dependency, go

#2163 [updatecli] Update to elastic/beats@81f63103678f
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go
