Repository elastic/cloudbeat, pull requests merged in 2024-06, with the labels that each got.

#2223 extend standard retry with 429 http status code
  internal/flavors/asset_inventory.go
  internal/flavors/benchmark/aws.go
  internal/flavors/benchmark/aws_org.go
  internal/flavors/benchmark/eks.go
  internal/flavors/benchmark/eks_test.go
  internal/flavors/benchmark/strategy.go
  internal/flavors/benchmark/strategy_test.go
  internal/flavors/vulnerability.go
  internal/resources/providers/awslib/config.go
  internal/resources/providers/awslib/config_provider_test.go
  internal/resources/providers/awslib/mock_config_provider_api.go
  internal/vulnerability/worker.go
Labels: backport-skip

#2249 add cloudsecmachine email for CI
  .ci/updatecli/updatecli.d/update-beats.yml
  .ci/updatecli/updatecli.d/update-golang.yml
  .ci/updatecli/updatecli.d/update-hermit.yml
  .ci/updatecli/updatecli.d/update-mods.yml
Labels: backport-skip

#2245 Remove periodic-ci workflow
  .ci/scripts/build.sh
  .github/workflows/periodic-ci.yml
  dev-docs/Cloudbeat-Deployment.md
Labels: backport-skip

#2253 Disable CGO in cloudbeat binary
  magefile.go
Labels: backport-skip

#2252 Use upstream PSP type definition instead of elastic-agent-autodiscover one
  go.mod
  go.sum
  internal/resources/fetching/fetchers/k8s/kube_fetcher.go
  internal/resources/fetching/fetchers/k8s/kube_fetcher_test.go
  internal/resources/fetching/fetchers/k8s/kube_provider.go
Labels: backport-skip

#2234 fix bump workflow git errors
  scripts/bump_cloudbeat.sh
  scripts/bump_integration.sh
Labels: backport-skip

#2262 [Asset Inventory] Update index to match Index Template
  internal/inventory/inventory.go
  internal/inventory/inventory_test.go
Labels: backport-skip

#2264 [updatecli] Update Golang version to 1.22.4
  .go-version
  bin/.go-1.22.4.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: backport-skip, automation, dependency, go

#2265 [updatecli] Update Golang version to 1.22.4
  .go-version
  bin/.go-1.22.4.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: backport-skip, automation, dependency, go

#2259 feat: drop aws-sdk-go v1 dependency
  go.mod
  internal/resources/fetching/fetchers/aws/iam_fetcher_test.go
  internal/resources/providers/awslib/iam/policy.go
  internal/resources/providers/awslib/iam/policy_test.go
  internal/vulnerability/fetcher_test.go
  internal/vulnerability/replicator_test.go
  internal/vulnerability/verifier_test.go
  internal/vulnerability/worker_test.go
Labels: backport-skip

#2269 Asset Inventory Networking information improvements
  internal/inventory/asset.go
  internal/inventory/awsfetcher/fetcher_ec2_instance.go
  internal/inventory/awsfetcher/fetcher_ec2_instance_test.go
  internal/inventory/awsfetcher/fetcher_networking.go
  internal/inventory/inventory_test.go
Labels: backport-skip, aws

#2251 [updatecli] Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.gcloud-479.0.0.pkg
  bin/.gh-2.50.0.pkg
  bin/.golangci-lint-1.59.1.pkg
  bin/.just-1.28.0.pkg
  bin/.opa-0.65.0.pkg
  bin/.regal-0.23.0.pkg
  bin/bq
  bin/docker-credential-gcloud
  bin/gcloud
  bin/gh
  bin/git-credential-gcloud.sh
  bin/golangci-lint
  bin/gsutil
  bin/just
  bin/opa
  bin/regal
Labels: backport-skip, automation, dependency

#2274 [updatecli] Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.gcloud-480.0.0.pkg
  bin/.gh-2.51.0.pkg
  bin/.just-1.29.1.pkg
  bin/.regal-0.23.1.pkg
  bin/.yq-4.44.2.pkg
  bin/bq
  bin/docker-credential-gcloud
  bin/gcloud
  bin/gh
  bin/git-credential-gcloud.sh
  bin/gsutil
  bin/just
  bin/regal
  bin/yq
Labels: backport-skip, automation, dependency

#2271 Add AWS Lambda fetcher to Asset Inventory
  go.mod
  go.sum
  internal/inventory/asset.go
  internal/inventory/awsfetcher/awsfetchers.go
  internal/inventory/awsfetcher/fetcher_lambda.go
  internal/inventory/awsfetcher/fetcher_lambda_test.go
  internal/inventory/awsfetcher/mock_lambda_describe_func.go
  internal/inventory/awsfetcher/mock_lambda_provider.go
  internal/resources/fetching/fetcher.go
  internal/resources/providers/awslib/lambda/alias.go
  internal/resources/providers/awslib/lambda/event_source_mapping.go
  internal/resources/providers/awslib/lambda/function.go
  internal/resources/providers/awslib/lambda/lambda.go
  internal/resources/providers/awslib/lambda/layer.go
  internal/resources/providers/awslib/lambda/mock_client.go
  internal/resources/providers/awslib/lambda/mock_lambda.go
  internal/resources/providers/awslib/lambda/provider.go
  internal/resources/providers/awslib/lambda/provider_test.go
Labels: backport-skip

#2280 refactor: replace custom atomic types with stdlib atomic
  internal/resources/fetching/cycle/cache_test.go
  internal/resources/providers/azurelib/governance/management_group_test.go
Labels: backport-skip

#2278 Fix networking fetcher type case
  internal/inventory/awsfetcher/fetcher_networking.go
Labels: backport-skip

#2266 add new wf
  .ci/scripts/create_env_config.py
  .ci/scripts/get_expired_envs.sh
  .github/workflows/destroy-environment.yml
  .github/workflows/destroy-expired-environment.yml
  .github/workflows/test-environment.yml
  .github/workflows/weekly-serverless.yml
  dev-docs/Cloud-Env-Testing.md
Labels: backport-skip

#2281 Remove Export from cf direct keys
  deploy/cloudformation/elastic-agent-direct-access-key-cspm-organization.yml
  deploy/cloudformation/elastic-agent-direct-access-key-cspm.yml
Labels: backport-v8.15.0

#2287 [updatecli] Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.gcloud-481.0.0.pkg
  bin/bq
  bin/docker-credential-gcloud
  bin/gcloud
  bin/git-credential-gcloud.sh
  bin/gsutil
Labels: backport-skip, automation, dependency

#2288 Revert "Bump andrcuns/allure-publish-action from 2.6.0 to 2.7.0 in /.github/workflows"
  .github/workflows/ci.yml
  .github/workflows/eks-ci.yml
Labels: backport-skip

#2290 Label cloud resources
  .github/workflows/test-environment.yml
  .github/workflows/test-gcp-dm.yml
  deploy/azure/install_agent_az_cli.sh
  deploy/deployment-manager/deploy.sh
Labels: backport-skip
