Repository elastic/cloudbeat, pull requests merged in 2024-11, with the labels that each got.

#2667 [CI] Avoid Trivy DB image pull quota issues
  internal/vulnerability/runner.go
Labels: backport-v8.x

#2576 [Asset Inventory][Azure] Add storage assets
  internal/inventory/ASSETS.md
  internal/inventory/asset.go
  internal/inventory/azurefetcher/azurefetchers.go
  internal/inventory/azurefetcher/fetcher_account.go
  internal/inventory/azurefetcher/fetcher_account_test.go
  internal/inventory/azurefetcher/fetcher_storage.go
  internal/inventory/azurefetcher/fetcher_storage_test.go
  internal/inventory/azurefetcher/mock_account_provider.go
  internal/inventory/azurefetcher/mock_account_provider_func.go
  internal/inventory/azurefetcher/mock_storage_provider.go
  internal/inventory/azurefetcher/mock_storage_provider_func.go
  internal/resources/providers/azurelib/inventory/mock_storage_account_provider_api.go
  internal/resources/providers/azurelib/inventory/storage_provider.go
  internal/resources/providers/azurelib/inventory/storage_provider_test.go
  internal/resources/providers/azurelib/mock_provider_api.go
  tests/product/tests/data/azure_asset_inventory/test_cases.py
Labels: backport-v8.x

#2566 [updatecli] Update golang mod dependencies
  go.mod
  go.sum
Labels: automation, dependency, go, backport-v8.x

#2597 [updatecli] Update to elastic/beats@249d0dc59f82
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2643 [updatecli] Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.awscli-2.19.1.pkg
  bin/.gcloud-499.0.0.pkg
  bin/.gh-2.60.1.pkg
  bin/.opa-0.70.0.pkg
  bin/aws
  bin/aws_completer
  bin/bq
  bin/docker-credential-gcloud
  bin/gcloud
  bin/gh
  bin/git-credential-gcloud.sh
  bin/gsutil
  bin/opa
Labels: automation, dependency, backport-v8.x

#2678 Update stack deployment template
  deploy/test-environments/variables.tf
Labels: Team:Cloud Security, backport-v8.x

#2626 [updatecli] Update to elastic/beats@00d7161a1d70
  go.mod
  go.sum
  internal/resources/providers/awslib/cached_region_selector.go
Labels: backport-skip, automation, dependency, go

#2651 cnvm: include full ec2 instance id in findings fields
  internal/resources/providers/awslib/ec2/ec2_instance.go
Labels: backport-v8.x

#2700 [updatecli] 8.x - Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2701 [updatecli] Update golang mod dependencies
  go.mod
  go.sum
Labels: automation, dependency, go, backport-v8.x

#2707 Remove context.TODO from production code
  internal/flavors/assetinventory/strategy_aws.go
  internal/flavors/benchmark/aws.go
  internal/flavors/benchmark/aws_org.go
  internal/flavors/benchmark/eks.go
  internal/flavors/vulnerability.go
  internal/inventory/awsfetcher/awsfetchers.go
  internal/resources/fetching/preset/aws_org_preset.go
  internal/resources/fetching/preset/aws_org_preset_test.go
  internal/resources/fetching/preset/aws_preset.go
  internal/resources/fetching/preset/eks_preset.go
  internal/resources/fetching/preset/mock_aws_factory.go
  internal/resources/providers/aws_cis/logging/logging.go
  internal/resources/providers/aws_cis/monitoring/monitoring.go
  internal/resources/providers/awslib/cloudtrail/cloudtrail.go
  internal/resources/providers/awslib/cloudwatch/cloudwatch.go
  internal/resources/providers/awslib/cloudwatch/logs/logs.go
  internal/resources/providers/awslib/configservice/configservice.go
  internal/resources/providers/awslib/ec2/ec2.go
  internal/resources/providers/awslib/ecr/ecr.go
  internal/resources/providers/awslib/elb/elb.go
  internal/resources/providers/awslib/elb_v2/elb_v2.go
  internal/resources/providers/awslib/iam/iam.go
  internal/resources/providers/awslib/kms/kms.go
  internal/resources/providers/awslib/lambda/lambda.go
  internal/resources/providers/awslib/mock_cross_region_factory.go
  internal/resources/providers/awslib/multi_region.go
  internal/resources/providers/awslib/multi_region_test.go
  internal/resources/providers/awslib/rds/provider.go
  internal/resources/providers/awslib/s3/provider.go
  internal/resources/providers/awslib/securityhub/provider.go
  internal/resources/providers/awslib/sns/sns.go
  internal/vulnerability/runner.go
  internal/vulnerability/runner_test.go
  internal/vulnerability/worker.go
  internal/vulnerability/worker_test.go
Labels: backport-v8.x

#2704 [updatecli] Update to elastic/beats@bfaa70fa9ae8
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2705 [updatecli] Update hermit and pre-commit dependencies
  .golangci.yaml
  .pre-commit-config.yaml
  bin/.awscli-2.19.4.pkg
  bin/.gcloud-500.0.0.pkg
  bin/.gh-2.61.0.pkg
  bin/.golangci-lint-1.62.0.pkg
  bin/.kind-0.25.0.pkg
  bin/aws
  bin/aws_completer
  bin/bq
  bin/docker-credential-gcloud
  bin/gcloud
  bin/gh
  bin/git-credential-gcloud.sh
  bin/golangci-lint
  bin/gsutil
  bin/kind
  internal/flavors/benchmark/aws_org_test.go
  internal/flavors/benchmark/aws_test.go
  internal/flavors/benchmark/azure.go
  internal/flavors/benchmark/azure_test.go
  internal/flavors/benchmark/eks_test.go
  internal/flavors/benchmark/gcp_test.go
  internal/flavors/benchmark/k8s_test.go
  internal/launcher/launcher_test.go
  internal/resources/fetching/fetchers/azure/assets_enricher_keyvault_test.go
  internal/resources/fetching/fetchers/azure/assets_enricher_storage_account_test.go
  internal/resources/fetching/fetchers/azure/insights_batch_fetcher_test.go
  internal/resources/fetching/fetchers/azure/locations_network_watcher_batch_fetcher_test.go
  internal/resources/fetching/fetchers/azure/security_fetcher_test.go
  internal/resources/fetching/fetchers/k8s/process_fetcher_test.go
  internal/resources/providers/awslib/kms/provider_test.go
  internal/resources/providers/awslib/s3/provider_test.go
  internal/resources/providers/azurelib/inventory/app_service_provider_test.go
  internal/resources/providers/azurelib/inventory/keyvault_provider_test.go
  internal/resources/providers/azurelib/inventory/resource_graph_provider_test.go
  internal/resources/providers/azurelib/inventory/security_provider_test.go
  internal/resources/providers/azurelib/inventory/sql_server_provider_test.go
  internal/resources/providers/azurelib/inventory/storage_provider_test.go
  internal/resources/utils/strings/strings_test.go
  internal/transformer/events_creator_test.go
Labels: automation, dependency, backport-v8.x

#2711 Override github.com/xi2/xz license
  .buildkite/scripts/generate_notice.py
  NOTICE.txt
Labels: backport-v8.x

#2691 Improve 8.x Dependency Updates
  .ci/updatecli/updatecli.d/update-beats.yml
  .ci/updatecli/updatecli.d/update-golang.yml
  .ci/updatecli/updatecli.d/update-hermit.yml
  .ci/updatecli/updatecli.d/update-mods.yml
  .github/dependabot.yml
  .github/workflows/updatecli.yml
Labels: backport-v8.x

#2625 [Asset Inventory][Azure] Add Acitive Directory fetcher to fetch Service Principals
  go.mod
  go.sum
  internal/flavors/assetinventory/strategy.go
  internal/flavors/assetinventory/strategy_test.go
  internal/inventory/ASSETS.md
  internal/inventory/asset.go
  internal/inventory/azurefetcher/azurefetchers.go
  internal/inventory/azurefetcher/fetcher_activedirectory.go
  internal/inventory/azurefetcher/fetcher_activedirectory_test.go
  internal/inventory/azurefetcher/mock_activedirectory_provider.go
  internal/resources/providers/msgraph/mock_provider_api.go
  internal/resources/providers/msgraph/provider.go
Labels: backport-v8.x

#2725 [updatecli] main - Update Golang version to 1.23.3
  .go-version
  bin/.go-1.23.3.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: backport-skip, automation, dependency, go

#2729 [updatecli] 8.16 - Update to elastic/beats@96968c93d761
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2728 [updatecli] main - Update to elastic/beats@ce4a17b3a960
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2724 [updatecli] 8.x - Update Golang version to 1.23.3
  .go-version
  bin/.go-1.23.3.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: backport-skip, automation, dependency, go

#2726 [updatecli] 8.16 - Update Golang version to 1.23.3
  .go-version
  bin/.go-1.23.3.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: backport-skip, automation, dependency, go

#2731 [updatecli] main - Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.awscli-2.20.0.pkg
  bin/.elastic-package-0.107.0.pkg
  bin/.gcloud-501.0.0.pkg
  bin/.regal-0.29.0.pkg
  bin/aws
  bin/aws_completer
  bin/bq
  bin/docker-credential-gcloud
  bin/elastic-package
  bin/gcloud
  bin/git-credential-gcloud.sh
  bin/gsutil
  bin/regal
Labels: backport-skip, automation, dependency

#2727 [updatecli] 8.x - Update to elastic/beats@79c57012c231
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2732 [updatecli] main - Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2733 [updatecli] 8.x - Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2738 [updatecli] 8.16 - Update to elastic/beats@f17e0828f1de
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2740 [updatecli] main - Update to elastic/beats@3e9ab5250791
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2741 [updatecli] 8.x - Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.awscli-2.21.3.pkg
  bin/.gh-2.62.0.pkg
  bin/.regal-0.29.2.pkg
  bin/.yq-4.44.5.pkg
  bin/aws
  bin/aws_completer
  bin/gh
  bin/regal
  bin/yq
Labels: backport-skip, automation, dependency

#2742 [updatecli] main - Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.awscli-2.21.3.pkg
  bin/.gh-2.62.0.pkg
  bin/.regal-0.29.2.pkg
  bin/.yq-4.44.5.pkg
  bin/aws
  bin/aws_completer
  bin/gh
  bin/regal
  bin/yq
Labels: backport-skip, automation, dependency

#2739 [updatecli] 8.x - Update to elastic/beats@04272dd134a9
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2744 [updatecli] main - Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2747 iam/user.go: Improve logging
  internal/resources/providers/awslib/iam/user.go
Labels: backport-skip

#2491 Refactor CDR and CIS workflows
  .ci/scripts/set_cloud_env_params.sh
  .github/actions/cdr/action.yml
  .github/actions/cis/action.yml
  .github/actions/elk-stack/action.yml
  .github/workflows/cdr-infra.yml
  .github/workflows/cloudformation-ci.yml
  .github/workflows/test-environment.yml
  .github/workflows/test-gcp-dm.yml
  .github/workflows/upgrade-environment.yml
  deploy/test-environments/README.md
  deploy/test-environments/cdr/main.tf
  deploy/test-environments/cdr/output.tf
  deploy/test-environments/cdr/terraform.tf
  deploy/test-environments/cdr/variables.tf
  deploy/test-environments/cis/main.tf
  deploy/test-environments/cis/output.tf
  deploy/test-environments/cis/terraform.tf
  deploy/test-environments/cis/variables.tf
  deploy/test-environments/delete_env.sh
  deploy/test-environments/elk-stack/main.tf
  deploy/test-environments/elk-stack/output.tf
  deploy/test-environments/elk-stack/terraform.tf
  deploy/test-environments/elk-stack/variables.tf
  deploy/test-environments/main.tf
  deploy/test-environments/manage_infrastructure.sh
  deploy/test-environments/output.tf
  deploy/test-environments/remote_setup.sh
  deploy/test-environments/set_cloud_env_params.sh
  deploy/test-environments/upload_state.sh
  tests/commonlib/agents_map.py
  tests/fleet_api/agent_policy_api.py
  tests/fleet_api/common_api.py
  tests/fleet_api/package_policy_api.py
  tests/integrations_setup/install_azure_asset_inventory_integration.py
Labels: backport-v8.x

#2749 Agentless GCP CSPM Sanity
  .github/workflows/test-environment.yml
  tests/commonlib/agents_map.py
  tests/integration/tests/test_sanity_checks.py
  tests/integrations_setup/install_agentless_integrations.py
Labels: backport-skip

#2763 [updatecli] main - Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.aws-iam-authenticator-0.6.28.pkg
  bin/.awscli-2.22.4.pkg
  bin/.elastic-package-0.107.2.pkg
  bin/.gcloud-502.0.0.pkg
  bin/.just-1.37.0.pkg
  bin/aws
  bin/aws-iam-authenticator
  bin/aws_completer
  bin/bq
  bin/docker-credential-gcloud
  bin/elastic-package
  bin/gcloud
  bin/git-credential-gcloud.sh
  bin/gsutil
  bin/just
Labels: backport-skip, automation, dependency

#2762 [updatecli] 8.x - Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.aws-iam-authenticator-0.6.28.pkg
  bin/.awscli-2.22.4.pkg
  bin/.elastic-package-0.107.2.pkg
  bin/.gcloud-502.0.0.pkg
  bin/.just-1.37.0.pkg
  bin/aws
  bin/aws-iam-authenticator
  bin/aws_completer
  bin/bq
  bin/docker-credential-gcloud
  bin/elastic-package
  bin/gcloud
  bin/git-credential-gcloud.sh
  bin/gsutil
  bin/just
Labels: backport-skip, automation, dependency

#2758 Add WIZ integration to the CDR flow
  .github/actions/cdr/action.yml
  .github/workflows/test-environment.yml
  deploy/test-environments/cdr/main.tf
  deploy/test-environments/cdr/output.tf
  deploy/test-environments/cdr/variables.tf
  deploy/test-environments/upload_state.sh
  tests/integrations_setup/README.md
  tests/integrations_setup/configuration_fleet.py
  tests/integrations_setup/data/wiz-pkg.json
  tests/integrations_setup/install_wiz_integration.py
Labels: backport-v8.x

#2760 [updatecli] main - Update to elastic/beats@6d1c81ecae3e
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2493 [Cloud Security] [Agentless] Add the creation of an agentless agent via Agentless API in the GHA Create Environment (new)
  .github/workflows/test-environment.yml
  tests/integrations_setup/install_agentless_integrations.py
  tests/integrations_setup/package_policy.py
Labels: backport-skip, Team:Cloud Security, automation

#2771 Fix ESS deployments created with Serverless
  .github/workflows/test-environment.yml
Labels: Team:Cloud Security, backport-v8.x

#2761 [updatecli] 8.x - Update to elastic/beats@f5df794c531a
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2765 [updatecli] main - Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2764 [updatecli] 8.x - Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2748 Add slack notifications to BK pipeline
  .buildkite/README.md
  .buildkite/pipeline.yml
  .buildkite/scripts/notify.sh
Labels: backport-v8.x

#2778 Fix handling of Fleet API response
  tests/fleet_api/agent_policy_api.py
  tests/fleet_api/base_call_api.py
  tests/fleet_api/common_api.py
  tests/fleet_api/package_policy_api.py
Labels: backport-v8.x

#2757 [CI] Update bump version workflow to work for x.x branches
  .github/workflows/bump-version.yml
  .github/workflows/sync-internal-cloudbeat-version.yml
  scripts/bump_cloudbeat.sh
  scripts/sync_internal_cloudbeat_version.sh
Labels: backport-v8.x
