Repository elastic/cloudbeat, pull requests merged in 2024-05, with the labels that each got.

#2141 Bump hermit cloudbeat version
  bin/hermit.hcl
Labels: backport-skip

#2166 [Release] Update version to 8.13.4
  version/version.go
Labels: team:automation, release

#2174 [updatecli] Update to elastic/beats@ff424ea42bbd
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2177 [updatecli] Update hermit and pre-commit dependencies
  .golangci.yaml
  .pre-commit-config.yaml
  bin/.gcloud-474.0.0.pkg
  bin/.gh-2.49.0.pkg
  bin/.golangci-lint-1.58.0.pkg
  bin/.opa-0.64.1.pkg
  bin/.regal-0.21.3.pkg
  bin/bq
  bin/docker-credential-gcloud
  bin/gcloud
  bin/gh
  bin/git-credential-gcloud.sh
  bin/golangci-lint
  bin/gsutil
  bin/opa
  bin/regal
  security-policies/.regal/config.yaml
  security-policies/bundle/compliance/cis_gcp/rules/cis_1_8/rule.rego
  security-policies/bundle/compliance/cis_gcp/rules/cis_1_8/test.rego
  security-policies/bundle/compliance/policy/aws_iam/data_adapter.rego
  security-policies/bundle/compliance/policy/gcp/data_adapter.rego
  security-policies/bundle/compliance/policy/gcp/iam/ensure_admin_without_multiple_roles.rego
  security-policies/bundle/compliance/policy/gcp/iam/ensure_user_not_editor_or_owner.rego
Labels: backport-skip, automation, dependency

#2181 Add debug line to buildkite package to verify what in the build folder
  .buildkite/scripts/package.sh
Labels: backport-skip

#2183 Make mage package verbose
  .buildkite/scripts/package.sh
Labels: backport-skip

#2055 add rate limit to asset inventory
  go.mod
  internal/flavors/benchmark/gcp.go
  internal/resources/providers/gcplib/inventory/grpc_rate_limiter.go
  internal/resources/providers/gcplib/inventory/grpc_rate_limiter_test.go
  internal/resources/providers/gcplib/inventory/map_cache.go
  internal/resources/providers/gcplib/inventory/map_cache_test.go
  internal/resources/providers/gcplib/inventory/provider.go
  internal/resources/providers/gcplib/inventory/provider_test.go
Labels: gcp, backport-v8.14.0

#2189 Rollback beats version
  go.mod
  go.sum
Labels: backport-skip

#2191 Disable EKS CI - config 1
  .github/workflows/eks-ci.yml
Labels: backport-skip

#2185 Fix ARM deployment issue for serverless deployment in create environment workflow
  .github/workflows/test-environment.yml
Labels: backport-skip

#2083 Backward Compatibility Standalone agent integration test
  .ci/scripts/get_versions.py
  .ci/scripts/run_agent.sh
  .github/actions/init-integration/action.yml
  .github/workflows/test-agent-compatibility.yml
  tests/test_environments/agents/elastic-agent-standalone.yml
Labels: backport-skip

#2186 [Release] Update version to 8.13.5
  version/version.go
Labels: team:automation, release

#2195 Bum go minor (from 1.22.0 to 1.22.3)
  bin/.go-1.22.3.pkg
  bin/go
  bin/gofmt
  go.mod
Labels: backport-skip

#2196 pre-commit: Fix cfn-lint version
  .pre-commit-config.yaml
Labels: backport-skip

#2199 [updatecli] Update Golang version to 1.22.3
  .go-version
  bin/.go-1.22.3.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
  go.mod
Labels: backport-skip, automation, dependency, go

#2198 [updatecli] Update Golang version to 1.22.3
  .go-version
  docs/version.asciidoc
Labels: backport-skip, automation, dependency, go

#2202 [updatecli] Update hermit and pre-commit dependencies
  bin/.elastic-package-0.100.0.pkg
  bin/.gcloud-475.0.0.pkg
  bin/.gh-2.49.1.pkg
  bin/.golangci-lint-1.58.1.pkg
  bin/.pre-commit-3.7.1.pkg
  bin/.yq-4.44.1.pkg
  bin/bq
  bin/docker-credential-gcloud
  bin/elastic-package
  bin/gcloud
  bin/gh
  bin/git-credential-gcloud.sh
  bin/golangci-lint
  bin/gsutil
  bin/pre-commit
  bin/yq
Labels: backport-skip, automation, dependency

#2201 [updatecli] Update to elastic/beats@c77302852ef9
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2203 Revert "[updatecli] Update to elastic/beats@c77302852ef9"
  go.mod
  go.sum
Labels: backport-skip

#2204 Publish cloudformation when version changes
  .github/workflows/publish-cloudformation.yml
Labels: backport-skip

#2205 Bring broken bk version + environemnt logging
  .buildkite/scripts/package.sh
  go.mod
  go.sum
Labels: backport-skip

#2206 Revert "Bring broken bk version + environemnt logging"
  .buildkite/scripts/package.sh
  go.mod
  go.sum
Labels: backport-skip

#2194 Add asset inventory AWS RDS fetcher
  internal/inventory/asset.go
  internal/inventory/awsfetcher/awsfetchers.go
  internal/inventory/awsfetcher/fetcher_rds.go
  internal/inventory/awsfetcher/fetcher_rds_test.go
  internal/inventory/awsfetcher/mock_rds_provider.go
Labels: backport-skip

#2207 Set buildkite linux image
  .buildkite/pipeline.yml
  .buildkite/scripts/package.sh
Labels: backport-skip

#2211 Update helm charts deployment
  tests/test_environments/k8s-cloudbeat-tests/charts/_kibana-8.4.0.tgz
Labels: backport-skip

#2210 bump beats
  .github/workflows/packaging.yml
  go.mod
  go.sum
Labels: backport-skip

#2118 add GCP credentials deployment
  .github/workflows/test-gcp-dm.yml
  deploy/deployment-manager/common.sh
  deploy/deployment-manager/compute_engine.py
  deploy/deployment-manager/compute_engine.py.schema
  deploy/deployment-manager/deploy.sh
  deploy/deployment-manager/deploy_service_account.sh
  deploy/deployment-manager/service_account.py
  deploy/deployment-manager/service_account.py.schema
  deploy/test-environments/delete_gcp_env.sh
  tests/fleet_api/utils.py
  tests/integrations_setup/configuration_fleet.py
  tests/integrations_setup/install_cspm_gcp_integration.py
Labels: backport-skip

#2215 [updatecli] Update to elastic/beats@0fd63999c524
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2222 Revert "Bump requests from 2.31.0 to 2.32.0 in /tests"
  tests/poetry.lock
  tests/pyproject.toml
Labels: backport-skip

#2168 Clean trivy cache before each cycle
  internal/vulnerability/runner.go
  internal/vulnerability/worker.go
Labels: backport-skip

#2216 [updatecli] Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.gcloud-476.0.0.pkg
  bin/.gh-2.49.2.pkg
  bin/.golangci-lint-1.58.2.pkg
  bin/.just-1.26.0.pkg
  bin/.kind-0.23.0.pkg
  bin/bq
  bin/docker-credential-gcloud
  bin/gcloud
  bin/gh
  bin/git-credential-gcloud.sh
  bin/golangci-lint
  bin/gsutil
  bin/just
  bin/kind
  tests/fleet_api/agent_policy_api.py
  tests/fleet_api/common_api.py
Labels: backport-skip, automation, dependency

#2228 rerun-flaky-workflows: Use env vars
  .github/workflows/rerun-flaky-workflows.yml
Labels: backport-skip

#2225 fix GCP credentials key extraction
  deploy/deployment-manager/deploy_service_account.sh
Labels: backport-skip

#2219 Integration of basic functional test suite developed with FTR into the Create Environment workflow
  .ci/scripts/set_cloud_env_params.sh
  .github/actions/kibana-ftr/README.md
  .github/actions/kibana-ftr/action.yml
  .github/workflows/test-environment.yml
  dev-docs/Cloud-Env-Testing.md
Labels: backport-skip

#2224 github-actions(updatecli): use GitHub secrets without vault access
  .ci/updatecli/updatecli.d/update-beats.yml
  .ci/updatecli/updatecli.d/update-golang.yml
  .ci/updatecli/updatecli.d/update-hermit.yml
  .ci/updatecli/updatecli.d/update-mods.yml
  .github/workflows/updatecli.yml
Labels: backport-skip

#2239 Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.gcloud-478.0.0.pkg
  bin/.golangci-lint-1.59.0.pkg
  bin/.just-1.27.0.pkg
  bin/bq
  bin/docker-credential-gcloud
  bin/gcloud
  bin/git-credential-gcloud.sh
  bin/golangci-lint
  bin/gsutil
  bin/just
Labels: backport-skip

#2240 regal: Disable new rules by default
  .pre-commit-config.yaml
  bin/.regal-0.22.0.pkg
  bin/regal
  security-policies/.regal/config.yaml
Labels: backport-skip, technical debt

#2241 Implement AWS VPC fetcher with sub-resources
  internal/inventory/asset.go
  internal/inventory/awsfetcher/awsfetchers.go
  internal/inventory/awsfetcher/fetcher_networking.go
  internal/inventory/awsfetcher/mock_describe_func.go
  internal/inventory/awsfetcher/mock_networking_provider.go
  internal/resources/fetching/fetcher.go
  internal/resources/fetching/fetchers/aws/network_fetcher.go
  internal/resources/fetching/fetchers/aws/network_fetcher_test.go
  internal/resources/providers/awslib/ec2/ec2.go
  internal/resources/providers/awslib/ec2/internet_gateway.go
  internal/resources/providers/awslib/ec2/mock_client.go
  internal/resources/providers/awslib/ec2/mock_elastic_compute.go
  internal/resources/providers/awslib/ec2/nat_gateway.go
  internal/resources/providers/awslib/ec2/network_interface.go
  internal/resources/providers/awslib/ec2/provider.go
  internal/resources/providers/awslib/ec2/provider_test.go
  internal/resources/providers/awslib/ec2/subnet.go
  internal/resources/providers/awslib/ec2/transit_gateway.go
  internal/resources/providers/awslib/ec2/transit_gateway_attachment.go
  internal/resources/providers/awslib/ec2/vpc_peering.go
Labels: backport-skip
