Repository elastic/cloudbeat, pull requests merged in 2024-02, with the labels that each got.

#1887 Fix CIS Azure 9.4 rule
  security-policies/RULES.md
  security-policies/bundle/compliance/cis_azure/rules/cis_9_4/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_9_4/test.rego
  tests/product/tests/data/azure/azure_app_service_test_cases.py
Labels: backport-skip

#1682 add workflow for version bumps
  .github/workflows/bump-version.yml
  scripts/bump_cloudbeat.sh
  scripts/bump_integration.sh
Labels: backport-skip

#1573 GCP CI - flaky tests fix
  .ci/scripts/disable_dynamic_mapping.sh
  .github/workflows/azure-ci.yml
  .github/workflows/gcp-ci.yml
  tests/integration/tests/test_sanity_checks.py
Labels: backport-skip

#1868 Add azure-ci to post-merge
  .github/workflows/azure-ci.yml
Labels: backport-skip

#1902 [updatecli] Update hermit and pre-commit dependencies
  bin/.elastic-package-0.96.1.pkg
  bin/.gcloud-462.0.1.pkg
  bin/.gh-2.43.1.pkg
  bin/.kind-0.21.0.pkg
  bin/bq
  bin/docker-credential-gcloud
  bin/elastic-package
  bin/gcloud
  bin/gh
  bin/git-credential-gcloud.sh
  bin/gsutil
  bin/kind
Labels: backport-skip, automation, dependency

#1895 move `dev-tools/packaging` to `scripts/packaging`
  .github/workflows/cloudbeat-ci.yml
  .github/workflows/eks-ci.yml
  .github/workflows/k8s-ci.yml
  .pre-commit-config.yaml
  dev-docs/Cloudbeat-Deployment.md
  scripts/packaging/docker/elastic-agent/Dockerfile
  scripts/packaging/docker/elastic-agent/build.sh
  scripts/packaging/packages.yml
Labels: backport-skip

#1896 removed unused files
  licenses/license.go
  test-logs/.gitkeep
  tests/ci_test_env/.env
  tests/ci_test_env/docker-compose.yml
Labels: backport-skip

#1904 chore: update containerd version
  go.mod
  go.sum
Labels: backport-skip

#1894 Publishing log with event.action
  internal/flavors/publisher.go
  internal/flavors/publisher_test.go
  internal/resources/utils/testhelper/helper.go
Labels: backport-skip

#1901 [updatecli] Update to elastic/beats@5e431f32119e
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#1865 CIS Azure rules 9.1, 9.3, and 9.10
  go.mod
  go.sum
  internal/resources/fetching/fetchers/azure/assets_enricher.go
  internal/resources/fetching/fetchers/azure/assets_enricher_app_service.go
  internal/resources/fetching/fetchers/azure/assets_fetcher_test.go
  internal/resources/providers/azurelib/inventory/app_service_provider.go
  internal/resources/providers/azurelib/inventory/app_service_provider_test.go
  internal/resources/providers/azurelib/inventory/asset.go
  internal/resources/providers/azurelib/inventory/mock_app_service_provider_api.go
  internal/resources/providers/azurelib/mock_provider_api.go
  internal/resources/providers/azurelib/provider.go
  security-policies/README.md
  security-policies/RULES.md
  security-policies/bundle/compliance/cis_azure/rules/cis_9_1/data.yaml
  security-policies/bundle/compliance/cis_azure/rules/cis_9_1/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_9_1/test.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_9_10/data.yaml
  security-policies/bundle/compliance/cis_azure/rules/cis_9_10/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_9_10/test.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_9_3/data.yaml
  security-policies/bundle/compliance/cis_azure/rules/cis_9_3/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_9_3/test.rego
  tests/product/tests/data/azure/azure_app_service_test_cases.py
Labels: backport-skip

#1908 add cleanup step for packaging
  .github/workflows/packaging.yml
Labels: backport-skip

#1906 [Release] Update version to 8.12.2
  version/version.go
Labels: team:automation, release

#1910 Publisher event.Count log field
  internal/flavors/publisher.go
Labels: backport-skip

#1912 [Terraform] Update Serverless reset-creds address
  deploy/cloud/modules/serverless/main.tf
Labels: backport-skip

#1924 Upgrade golangci-lint
  .github/workflows/unit-test.yml
  .pre-commit-config.yaml
  bin/.golangci-lint-1.56.1.pkg
  bin/golangci-lint
  internal/flavors/benchmark/strategy_test.go
  internal/launcher/listener_test.go
  internal/pipeline/pipeline_test.go
  internal/resources/fetching/cycle/cache_test.go
  internal/resources/fetching/fetchers/aws/ecr_fetcher_test.go
  internal/resources/fetching/fetchers/azure/assets_enricher_storage_account.go
  internal/resources/fetching/fetchers/azure/assets_fetcher_test.go
  internal/resources/fetching/fetchers/azure/batch_fetcher_test.go
  internal/resources/fetching/fetchers/gcp/assets_fetcher_test.go
  internal/resources/fetching/fetchers/k8s/glob_matching.go
  internal/resources/fetching/manager/manager_test.go
  internal/resources/fetching/preset/aws_org_preset_test.go
  internal/resources/providers/awslib/account_provider_test.go
  internal/resources/providers/awslib/cached_region_selector_test.go
  internal/resources/providers/awslib/multi_region_test.go
  internal/resources/providers/azurelib/auth/credentials_test.go
  internal/resources/providers/azurelib/governance/management_group.go
  internal/resources/providers/azurelib/governance/management_group_test.go
  internal/resources/providers/azurelib/inventory/mysql_provider_test.go
  internal/resources/providers/azurelib/inventory/postgresql_provider_test.go
  internal/resources/providers/azurelib/inventory/resource_graph_provider_test.go
  internal/resources/providers/azurelib/inventory/security_provider.go
  internal/resources/providers/azurelib/inventory/sql_server_provider_test.go
  internal/resources/providers/azurelib/inventory/subscriptions_provider_test.go
  internal/resources/providers/gcplib/inventory/provider_test.go
  internal/transformer/events_creator_test.go
  internal/uniqueness/leaderelection.go
  internal/vulnerability/fetcher_test.go
Labels: backport-skip

#1891 [Sanity Tests] [Telemetry] Enable package policy id check (#1885)
  tests/integration/tests/test_sanity_telemetry.py
Labels: backport-skip, Testing, Team:Cloud Security

#1857 CIS Azure 5.1.5
  internal/resources/fetching/fetchers/azure/assets_enricher_keyvault.go
  internal/resources/fetching/fetchers/azure/assets_enricher_keyvault_test.go
  internal/resources/fetching/fetchers/azure/assets_fetcher_test.go
  internal/resources/providers/azurelib/inventory/asset.go
  internal/resources/providers/azurelib/inventory/keyvault_provider.go
  internal/resources/providers/azurelib/inventory/keyvault_provider_test.go
  internal/resources/providers/azurelib/inventory/mock_key_vault_provider_api.go
  internal/resources/providers/azurelib/mock_provider_api.go
  internal/resources/providers/azurelib/provider.go
  security-policies/README.md
  security-policies/RULES.md
  security-policies/bundle/compliance/cis_azure/rules/cis_5_1_5/data.yaml
  security-policies/bundle/compliance/cis_azure/rules/cis_5_1_5/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_5_1_5/test.rego
  tests/product/tests/data/azure/azure_key_vault_test_cases.py
Labels: backport-skip

#1920 [updatecli] Update to elastic/beats@d3cac73cfca8
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#1928 Remove GitHub's dependency-review
  .github/workflows/unit-test.yml
Labels: backport-v8.12.0

#1938 workflow bump fixes
  .github/workflows/bump-version.yml
  scripts/bump_cloudbeat.sh
  scripts/bump_integration.sh
Labels: backport-skip

#1953 checkout main for running integration bump script
  .github/workflows/bump-version.yml
Labels: backport-skip

#1914 Cloud Watch Comparison Algorithm
  internal/resources/providers/aws_cis/monitoring/filter_pattern_parser.go
  internal/resources/providers/aws_cis/monitoring/filter_pattern_parser_test.go
  internal/resources/providers/aws_cis/monitoring/monitoring.go
  internal/resources/providers/aws_cis/monitoring/monitoring_test.go
  security-policies/bundle/compliance/cis_aws/rules/cis_4_1/rule.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_1/test.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_10/rule.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_10/test.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_11/rule.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_11/test.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_12/rule.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_12/test.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_13/rule.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_13/test.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_14/rule.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_14/test.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_15/rule.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_15/test.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_2/rule.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_2/test.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_3/rule.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_3/test.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_4/rule.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_4/test.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_5/rule.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_5/test.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_6/rule.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_6/test.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_7/rule.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_7/test.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_8/rule.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_8/test.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_9/rule.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_9/test.rego
  security-policies/bundle/compliance/policy/aws_cloudtrail/pattern.rego
  security-policies/bundle/compliance/policy/aws_cloudtrail/pattern_test.rego
Labels: backport-v8.13.0

#1956 Release cloudbeat version
  deploy/azure/ARM-for-organization-account.json
  deploy/azure/ARM-for-single-account.json
Labels: backport-skip

#1954 Bump cloudbeat version
  .mergify.yml
  deploy/azure/ARM-for-organization-account.dev.json
  deploy/azure/ARM-for-organization-account.json
  deploy/azure/ARM-for-single-account.dev.json
  deploy/azure/ARM-for-single-account.json
  version/version.go
Labels: backport-skip

#1961 [updatecli] Update to elastic/beats@3924ac062523
  cloudbeat.reference.yml
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#1955 Bump hermit cloudbeat version
  bin/hermit.hcl
Labels: backport-skip

#1959 Fix rule CIS Azure rule 4.1.2
  internal/resources/fetching/fetchers/azure/assets_enricher_sql_server.go
  internal/resources/fetching/fetchers/azure/assets_enricher_sql_server_test.go
  internal/resources/fetching/fetchers/azure/assets_fetcher_test.go
  internal/resources/providers/azurelib/inventory/asset.go
  internal/resources/providers/azurelib/inventory/mock_sql_provider_api.go
  internal/resources/providers/azurelib/inventory/sql_server_provider.go
  internal/resources/providers/azurelib/inventory/sql_server_provider_test.go
  internal/resources/providers/azurelib/mock_provider_api.go
  security-policies/bundle/compliance/cis_azure/rules/cis_4_1_2/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_1_2/test.rego
Labels: backport-skip

#1967 Fix EKS ci
  .github/workflows/eks-ci.yml
  tests/test_environments/k8s-cloudbeat-tests/templates/cloudbeat-eks-pytest.yaml
  tests/test_environments/k8s-cloudbeat-tests/templates/tests/cloudbeat-test-pod.yml
Labels: backport-skip

#1977 Fix confliciting fields and bugs on the rules
  internal/resources/providers/aws_cis/monitoring/filter_pattern_parser.go
  security-policies/bundle/compliance/cis_aws/rules/cis_4_15/rule.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_15/test.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_4/rule.rego
  security-policies/bundle/compliance/cis_aws/rules/cis_4_4/test.rego
  security-policies/bundle/compliance/policy/aws_cloudtrail/pattern.rego
Labels: backport-v8.13.0

#1969 [Release] Update version to 8.12.3
  version/version.go
Labels: team:automation, release
