Repository elastic/cloudbeat, pull requests merged in 2024-01, with the labels that each got.

#1762 fix opa test coverage cmd
  .github/workflows/test-opa-coverage.yml
Labels: backport-skip

#1761 remove direct dependency go-git
  go.mod
  magefile.go
Labels: backport-skip

#1744 Revert "CloudFormation: Fix missing tags in cloud-security account"
  deploy/cloudformation/elastic-agent-ec2-cnvm.yml
  deploy/cloudformation/elastic-agent-ec2-cspm.yml
Labels: backport-skip

#1695 Implementing Azure CI rule tests
  .github/workflows/azure-ci.yml
  deploy/azure/cloudbeat-azure.yml
  tests/configuration.py
  tests/product/tests/data/azure/__init__.py
  tests/product/tests/data/azure/azure_app_service_test_cases.py
  tests/product/tests/data/azure/azure_database_service_test_cases.py
  tests/product/tests/data/azure/azure_identity_access_management_test_cases.py
  tests/product/tests/data/azure/azure_key_vault_test_cases.py
  tests/product/tests/data/azure/azure_logging_and_monitoring_test_cases.py
  tests/product/tests/data/azure/azure_networking_test_cases.py
  tests/product/tests/data/azure/azure_storage_account_test_cases.py
  tests/product/tests/data/azure/azure_virtual_machine_test_cases.py
  tests/product/tests/data/azure_test_case.py
  tests/product/tests/test_azure_app_service_rules.py
  tests/product/tests/test_azure_database_service_rules.py
  tests/product/tests/test_azure_identity_access_management_rules.py
  tests/product/tests/test_azure_key_vault_rules.py
  tests/product/tests/test_azure_logging_and_monitoring_rules.py
  tests/product/tests/test_azure_networking_rules.py
  tests/product/tests/test_azure_storage_account_rules.py
  tests/product/tests/test_azure_virtual_machine_rules.py
Labels: backport-skip

#1769 Adding workflow dispatch to Azure CI due to Azure CI retrigger bugs
  .github/workflows/azure-ci.yml
Labels: backport-skip

#1759 Use Cloud Trail ARN when get trail status and event selectors
  resources/providers/awslib/cloudtrail/provider.go
Labels: backport-skip

#1685 Add rerun workflow
  .github/workflows/rerun-flaky-workflows.yml
Labels: backport-skip

#1770 Weekly env lower case
  .github/workflows/test-environment.yml
  .github/workflows/weekly-serverless.yml
Labels: backport-skip

#1773 Add permissions for rerun action
  .github/workflows/rerun-flaky-workflows.yml
Labels: backport-skip

#1772 CIS Azure 4.1.1
  resources/fetching/fetchers/azure/assets_enricher_sql_server.go
  resources/fetching/fetchers/azure/assets_enricher_sql_server_test.go
  resources/fetching/fetchers/azure/assets_fetcher_test.go
  resources/providers/azurelib/inventory/asset.go
  resources/providers/azurelib/inventory/mock_provider_api.go
  resources/providers/azurelib/inventory/provider.go
  resources/providers/azurelib/inventory/sql_server.go
  resources/providers/azurelib/inventory/sql_server_test.go
  resources/providers/azurelib/mock_provider_api.go
  resources/providers/azurelib/provider.go
  security-policies/README.md
  security-policies/RULES.md
  security-policies/bundle/compliance/cis_azure/rules/cis_4_1_1/data.yaml
  security-policies/bundle/compliance/cis_azure/rules/cis_4_1_1/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_1_1/test.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_1_3/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_1_3/test.rego
Labels: backport-skip

#1774 [Rerun workflow] update username
  .github/workflows/rerun-flaky-workflows.yml
Labels: backport-skip

#1778 [Slack Notification] Update errors handling in workflows
  .github/workflows/destroy-environment.yml
  .github/workflows/rerun-flaky-workflows.yml
  .github/workflows/test-environment.yml
Labels: backport-skip

#1780 Skip K8s CI
  .github/workflows/k8s-ci.yml
Labels: backport-skip

#1779 [Create Environment] Update cleanup step statement
  .github/workflows/k8s-ci.yml
  .github/workflows/test-environment.yml
Labels: backport-skip

#1765 trim coverage score
  .github/workflows/test-opa-coverage.yml
Labels: backport-skip

#1777 CIS Azure 4.1.5
  resources/fetching/fetchers/azure/assets_enricher_sql_server.go
  resources/fetching/fetchers/azure/assets_enricher_sql_server_test.go
  resources/fetching/fetchers/azure/assets_fetcher_test.go
  resources/providers/azurelib/inventory/asset.go
  resources/providers/azurelib/inventory/mock_provider_api.go
  resources/providers/azurelib/inventory/provider.go
  resources/providers/azurelib/inventory/sql_server.go
  resources/providers/azurelib/inventory/sql_server_test.go
  resources/providers/azurelib/mock_provider_api.go
  resources/providers/azurelib/provider.go
  security-policies/RULES.md
  security-policies/bundle/compliance/cis_azure/rules/cis_4_1_5/data.yaml
  security-policies/bundle/compliance/cis_azure/rules/cis_4_1_5/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_1_5/test.rego
Labels: backport-skip

#1785 [updatecli] Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.just-1.22.0.pkg
  bin/.regal-0.15.0.pkg
  bin/just
  bin/regal
Labels: backport-skip, automation, dependency

#1776 Make Storage Account Enricher best-effort
  resources/fetching/fetchers/azure/assets_enricher_storage_account.go
  resources/fetching/fetchers/azure/assets_enricher_storage_account_test.go
Labels: backport-skip

#1786 CIS Azure 4.1.6
  security-policies/README.md
  security-policies/RULES.md
  security-policies/bundle/compliance/cis_azure/rules/cis_4_1_6/data.yaml
  security-policies/bundle/compliance/cis_azure/rules/cis_4_1_6/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_1_6/test.rego
Labels: backport-skip

#1787 [updatecli] Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#1788 Remove duplicate schedule from dependabot.yml
  .github/dependabot.yml
Labels: backport-skip

#1782 Refactor inventory provider into multiple providers
  resources/providers/azurelib/governance/management_group.go
  resources/providers/azurelib/governance/management_group_test.go
  resources/providers/azurelib/inventory/mock_provider_api.go
  resources/providers/azurelib/inventory/mock_resource_graph_provider_api.go
  resources/providers/azurelib/inventory/mock_sql_provider_api.go
  resources/providers/azurelib/inventory/mock_storage_account_provider_api.go
  resources/providers/azurelib/inventory/provider.go
  resources/providers/azurelib/inventory/resource_graph_provider.go
  resources/providers/azurelib/inventory/resource_graph_provider_test.go
  resources/providers/azurelib/inventory/sql_server_provider.go
  resources/providers/azurelib/inventory/sql_server_provider_test.go
  resources/providers/azurelib/inventory/storage.go
  resources/providers/azurelib/inventory/storage_provider.go
  resources/providers/azurelib/inventory/storage_provider_test.go
  resources/providers/azurelib/inventory/storage_test.go
  resources/providers/azurelib/provider.go
Labels: backport-skip

#1798 add cnvm id logs
  vulnerability/replicator.go
  vulnerability/scanner.go
  vulnerability/verifier.go
  vulnerability/verifier_test.go
  vulnerability/worker_test.go
Labels: backport-skip

#1796 CIS PostgreSQL Configuration Rules (from 4.3.2 to 4.3.6)
  go.mod
  go.sum
  resources/fetching/fetcher.go
  resources/fetching/fetchers/azure/assets_enricher.go
  resources/fetching/fetchers/azure/assets_enricher_postgresql.go
  resources/fetching/fetchers/azure/assets_enricher_postgresql_test.go
  resources/fetching/fetchers/azure/assets_enricher_sql_server.go
  resources/fetching/fetchers/azure/assets_enricher_sql_server_test.go
  resources/fetching/fetchers/azure/assets_enricher_test.go
  resources/fetching/fetchers/azure/assets_fetcher.go
  resources/fetching/fetchers/azure/assets_fetcher_test.go
  resources/providers/azurelib/inventory/asset.go
  resources/providers/azurelib/inventory/mock_postgresql_provider_api.go
  resources/providers/azurelib/inventory/postgresql_provider.go
  resources/providers/azurelib/inventory/postgresql_provider_test.go
  resources/providers/azurelib/inventory/sql_server_provider.go
  resources/providers/azurelib/mock_provider_api.go
  resources/providers/azurelib/provider.go
  resources/utils/ptrs/pointers.go
  security-policies/README.md
  security-policies/RULES.md
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_1/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_2/data.yaml
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_2/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_2/test.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_3/data.yaml
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_3/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_3/test.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_4/data.yaml
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_4/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_4/test.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_5/data.yaml
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_5/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_5/test.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_6/data.yaml
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_6/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_6/test.rego
  security-policies/bundle/compliance/cis_azure/test_data.rego
  security-policies/bundle/compliance/policy/azure/data_adapter.rego
Labels: backport-skip

#1736 [updatecli] Update to elastic/beats@4ed62e67b8a1
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#1804 [Release] Update version to 8.11.5
  version/version.go
Labels: team:automation, release

#1806 update aws-sdk-go/service/ebs
  .github/workflows/cnvm-ci.yml
  go.mod
  go.sum
Labels: backport-skip

#1807 CIS Azure 4.3.7
  resources/fetching/fetchers/azure/assets_enricher_postgresql.go
  resources/fetching/fetchers/azure/assets_enricher_postgresql_test.go
  resources/fetching/fetchers/azure/assets_fetcher_test.go
  resources/providers/azurelib/inventory/asset.go
  resources/providers/azurelib/inventory/mock_postgresql_provider_api.go
  resources/providers/azurelib/inventory/postgresql_provider.go
  resources/providers/azurelib/inventory/postgresql_provider_test.go
  resources/providers/azurelib/mock_provider_api.go
  security-policies/README.md
  security-policies/RULES.md
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_7/data.yaml
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_7/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_7/test.rego
Labels: backport-skip

#1783 Changes to Azure CI workflow
  .github/workflows/azure-ci.yml
  tests/product/tests/data/azure/azure_app_service_test_cases.py
  tests/product/tests/data/azure/azure_database_service_test_cases.py
  tests/product/tests/data/azure/azure_identity_access_management_test_cases.py
  tests/product/tests/data/azure/azure_key_vault_test_cases.py
  tests/product/tests/data/azure/azure_logging_and_monitoring_test_cases.py
  tests/product/tests/data/azure/azure_networking_test_cases.py
  tests/product/tests/data/azure/azure_storage_account_test_cases.py
  tests/product/tests/data/azure/azure_virtual_machine_test_cases.py
  tests/pyproject.toml
Labels: backport-skip

#1820 [updatecli] Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#1815 [updatecli] Update Golang version to 1.21.6
  .go-version
  bin/.go-1.21.6.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: backport-skip, automation, dependency, go

#1816 [updatecli] Update Golang version to 1.21.6
  .go-version
  bin/.go-1.21.6.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: backport-skip, automation, dependency, go

#1810 shellcheck: Include everything, exclude failures
  .pre-commit-config.yaml
Labels: backport-skip, technical debt

#1809 CIS Azure 4.2.1
  resources/fetching/fetchers/azure/assets_enricher_sql_server.go
  resources/fetching/fetchers/azure/assets_enricher_sql_server_test.go
  resources/fetching/fetchers/azure/assets_fetcher_test.go
  resources/providers/azurelib/inventory/asset.go
  resources/providers/azurelib/inventory/mock_sql_provider_api.go
  resources/providers/azurelib/inventory/sql_server_provider.go
  resources/providers/azurelib/inventory/sql_server_provider_test.go
  resources/providers/azurelib/mock_provider_api.go
  security-policies/RULES.md
  security-policies/bundle/compliance/cis_azure/rules/cis_4_2_1/data.yaml
  security-policies/bundle/compliance/cis_azure/rules/cis_4_2_1/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_2_1/test.rego
Labels: backport-skip

#1763 add gcp deployment manager ci test
  .github/workflows/test-gcp-dm.yml
  deploy/deployment-manager/deploy.sh
  deploy/test-environments/delete_env.sh
  deploy/test-environments/delete_gcp_env.sh
Labels: backport-skip, gcp

#1821 shellcheck: Make some easy fixes
  .pre-commit-config.yaml
  scripts/make/autopep8_all.sh
  scripts/make/aws_creds_env.sh
  scripts/remote_edit_config.sh
Labels: backport-skip, technical debt

#1825 Activate Azure CI
  .github/workflows/azure-ci.yml
  security-policies/bundle/compliance/cis_azure/rules/cis_5_2_5/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_5_2_5/test.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_5_2_6/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_5_2_6/test.rego
  tests/product/tests/data/azure/azure_app_service_test_cases.py
  tests/product/tests/data/azure/azure_database_service_test_cases.py
  tests/product/tests/data/azure/azure_identity_access_management_test_cases.py
  tests/product/tests/data/azure/azure_logging_and_monitoring_test_cases.py
  tests/product/tests/data/azure/azure_networking_test_cases.py
  tests/product/tests/data/azure/azure_storage_account_test_cases.py
  tests/product/tests/data/azure/azure_virtual_machine_test_cases.py
Labels: backport-skip

#1838 [updatecli] Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.gcloud-460.0.0.pkg
  bin/.gh-2.42.1.pkg
  bin/bq
  bin/docker-credential-gcloud
  bin/gcloud
  bin/gh
  bin/git-credential-gcloud.sh
  bin/gsutil
Labels: backport-skip, automation, dependency

#1842 [Cloud Security] Select the Environment Url for Create Environment
  .github/workflows/destroy-environment.yml
  .github/workflows/test-environment.yml
  .github/workflows/test-gcp-dm.yml
  .github/workflows/upgrade-environment.yml
  .github/workflows/weekly-enviroment.yml
  deploy/cloud/main.tf
  deploy/cloud/modules/ec/variables.tf
  deploy/cloud/variables.tf
  deploy/test-environments/README.md
  deploy/test-environments/delete_env.sh
  deploy/test-environments/main.tf
  deploy/test-environments/variables.tf
  deploy/weekly-environment/main.tf
  dev-docs/Cloud-Env-Testing.md
Labels: Team:Cloud Security

#1830 Refactor extensions to use full asset instead of properties only
  resources/fetching/fetchers/azure/assets_enricher.go
  resources/fetching/fetchers/azure/assets_enricher_mysql.go
  resources/fetching/fetchers/azure/assets_enricher_mysql_test.go
  resources/fetching/fetchers/azure/assets_enricher_postgresql.go
  resources/fetching/fetchers/azure/assets_enricher_postgresql_test.go
  resources/fetching/fetchers/azure/assets_enricher_sql_server.go
  resources/fetching/fetchers/azure/assets_enricher_sql_server_test.go
  resources/providers/azurelib/inventory/mysql_provider.go
  resources/providers/azurelib/inventory/mysql_provider_test.go
  resources/providers/azurelib/inventory/postgresql_provider.go
  resources/providers/azurelib/inventory/postgresql_provider_test.go
  security-policies/bundle/compliance/cis_azure/rules/cis_4_1_1/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_1_1/test.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_1_3/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_1_3/test.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_1_5/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_1_5/test.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_1_6/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_1_6/test.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_2_1/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_2_1/test.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_2/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_2/test.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_3/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_3/test.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_4/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_4/test.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_5/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_5/test.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_6/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_6/test.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_7/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_7/test.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_4_2/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_4_2/test.rego
Labels: backport-skip

#1822 Update elastic/beats and ignore CVE-2023-49922 in dependency-review-a…
  .github/workflows/unit-test.yml
  go.mod
  go.sum
Labels: backport-skip

#1793 Update trivy
  go.mod
  go.sum
  vulnerability/mock_runner_interface.go
  vulnerability/scanner.go
  vulnerability/worker_test.go
Labels: backport-skip

#1844 CIS 6.6 Fail case location has no Network Watcher
  flavors/benchmark/azure_test.go
  go.mod
  go.sum
  resources/fetching/fetchers/azure/assets_fetcher.go
  resources/fetching/fetchers/azure/locations_network_watcher_batch_fetcher.go
  resources/fetching/fetchers/azure/locations_network_watcher_batch_fetcher_test.go
  resources/fetching/preset/azure_preset.go
  resources/providers/azurelib/inventory/asset.go
  resources/providers/azurelib/inventory/mock_subscription_provider_api.go
  resources/providers/azurelib/inventory/subscriptions_provider_test.go
  resources/providers/azurelib/inventory/susbcriptions_provider.go
  resources/providers/azurelib/mock_provider_api.go
  resources/providers/azurelib/provider.go
  security-policies/bundle/compliance/cis_azure/rules/cis_6_6/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_6_6/test.rego
  tests/product/tests/data/azure/azure_networking_test_cases.py
Labels: backport-skip

#1853 Add license override for trivy-policies
  .buildkite/scripts/generate_notice.py
Labels: backport-skip

#1855 Add flag to skip SSL verification and docs on how to run agains local ES
  tests/README.md
  tests/commonlib/elastic_wrapper.py
  tests/configuration.py
  tests/conftest.py
Labels: backport-skip

#1858 pre-commit: Enable end-of-line-fixer
  .github/workflows/cnvm-ci.yml
  .pre-commit-config.yaml
  bin/README.hermit.md
  deploy/azure/ARM-for-organization-account.dev.json
  deploy/azure/ARM-for-single-account.dev.json
  deploy/azure/generate_dev_template.py
  deploy/cloud/data/agent_policy_cnvm_aws.json
  deploy/cloud/data/agent_policy_cspm_aws.json
  deploy/cloud/data/agent_policy_cspm_gcp.json
  deploy/cloud/data/agent_policy_d4c.json
  deploy/cloud/data/package_policy_cnvm_aws.json
  deploy/cloud/data/package_policy_cspm_aws.json
  deploy/cloud/data/package_policy_d4c.json
  deploy/cloud/data/package_policy_eks.json
  deploy/cloud/data/package_policy_vanilla.json
  deploy/cloud/modules/api/modules/vanilla/main.tf
  deploy/cloud/modules/ec/main.tf
  deploy/cloud/modules/ec/variables.tf
  deploy/cloud/modules/provision-eks-cluster/variables.tf
  deploy/cloudformation/.gitignore
  deploy/kustomize/overlays/cloudbeat-aws/aws.creds
  deploy/kustomize/overlays/cloudbeat-aws/kustomization.yml
  deploy/kustomize/overlays/cloudbeat-aws/patches/patch-elastic-creds.yml
  deploy/test-environments/README.md
  deploy/test-environments/fleet_api/README.md
  deploy/test-environments/fleet_api/src/data/cspm-linux.j2
  deploy/test-environments/output.tf
  deploy/vulnerability/README.md
  docs/fields.asciidoc
  justfile
  tests/deploy/values/ci-aws-services.yml
Labels: backport-skip, technical debt

#1801 CIS Azure 5.1.4
  .mockery.yaml
  flavors/benchmark/azure.go
  resources/fetching/fetchers/azure/assets_enricher_storage_account.go
  resources/fetching/fetchers/azure/assets_enricher_storage_account_test.go
  resources/fetching/fetchers/azure/assets_fetcher_test.go
  resources/providers/azurelib/inventory/asset.go
  resources/providers/azurelib/inventory/mock_storage_account_provider_api.go
  resources/providers/azurelib/inventory/storage_provider.go
  resources/providers/azurelib/inventory/storage_provider_test.go
  resources/providers/azurelib/mock_provider_api.go
  security-policies/RULES.md
  security-policies/bundle/compliance/cis_azure/rules/cis_5_1_4/data.yaml
  security-policies/bundle/compliance/cis_azure/rules/cis_5_1_4/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_5_1_4/test.rego
Labels: backport-skip

#1860 Add dev doc for deploying Fleet enrolled Elastic Agent with custom binaries
  dev-docs/Cloudbeat-Deployment.md
Labels: backport-skip

#1831 k8s fix process name matching
  resources/fetching/fetchers/k8s/process_fetcher.go
  resources/fetching/fetchers/k8s/process_fetcher_test.go
  resources/fetching/preset/k8s_preset.go
Labels: backport-skip

#1734 Agentless CSPM Azure sanity tests
  .github/workflows/test-environment.yml
  deploy/test-environments/fleet_api/src/configuration_fleet.py
  deploy/test-environments/fleet_api/src/install_agentless_integrations.py
  tests/commonlib/agents_map.py
  tests/integration/tests/test_sanity_checks.py
Labels: backport-skip

#1864 Update dependencies of Create Environment action
  .github/workflows/test-environment.yml
Labels: backport-skip

#1867 Enable post-merge k8s ci
  .github/workflows/k8s-ci.yml
Labels: backport-skip

#1873 Revert upload artifact version from v4 to v3
  .github/dependabot.yml
  .github/workflows/eks-ci.yml
  .github/workflows/k8s-ci.yml
  .github/workflows/periodic-ci.yml
Labels: backport-skip

#1866 Skip fleet API calls on integration tests
  tests/conftest.py
  tests/integration/tests/test_sanity_checks.py
Labels: backport-skip

#1875 [updatecli] Update to elastic/beats@cf731e633992
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#1876 Revert download artifacts from v4 to v3
  .github/dependabot.yml
  .github/workflows/eks-ci.yml
  .github/workflows/periodic-ci.yml
  .github/workflows/unit-test.yml
Labels: backport-skip

#1859 Update ci docker images
  .github/workflows/cloudbeat-ci.yml
  .github/workflows/eks-ci.yml
  .github/workflows/k8s-ci.yml
  tests/test_environments/sa-agent-pytest.yml
Labels: backport-skip

#1879 Update dependabot pattern to ignore github actions update
  .github/dependabot.yml
Labels: backport-skip

#1880 Add IT for CIS Azure 6.1, 6.2, 6.3, 6.4
  tests/product/tests/data/azure/azure_networking_test_cases.py
Labels: backport-skip

#1861 Add Integration Tests Coverage Metric
  .pre-commit-config.yaml
  security-policies/RULES.md
  security-policies/dev/common.py
  security-policies/dev/update_rule_status.py
  security-policies/poetry.lock
  security-policies/pyproject.toml
  tests/README.md
  tests/product/tests/data/aws/aws_ec2_test_cases.py
  tests/product/tests/data/aws/aws_iam_test_cases.py
  tests/product/tests/data/aws/aws_logging_test_cases.py
  tests/product/tests/data/aws/aws_monitoring_test_cases.py
  tests/product/tests/data/aws/aws_rds_test_cases.py
  tests/product/tests/data/aws/aws_s3_test_cases.py
  tests/product/tests/data/aws/aws_vpc_test_cases.py
  tests/product/tests/data/aws/managed_services_test_cases.py
  tests/product/tests/data/azure/azure_app_service_test_cases.py
  tests/product/tests/data/azure/azure_database_service_test_cases.py
  tests/product/tests/data/azure/azure_identity_access_management_test_cases.py
  tests/product/tests/data/azure/azure_key_vault_test_cases.py
  tests/product/tests/data/azure/azure_logging_and_monitoring_test_cases.py
  tests/product/tests/data/azure/azure_networking_test_cases.py
  tests/product/tests/data/azure/azure_storage_account_test_cases.py
  tests/product/tests/data/azure/azure_virtual_machine_test_cases.py
  tests/product/tests/test_aws_ec2_rules.py
  tests/product/tests/test_aws_iam_management_rules.py
  tests/product/tests/test_aws_logging_rules.py
  tests/product/tests/test_aws_monitoring_rules.py
  tests/product/tests/test_aws_rds_rules.py
  tests/product/tests/test_aws_s3_service_rules.py
  tests/product/tests/test_aws_vpc_rules.py
  tests/product/tests/test_azure_app_service_rules.py
  tests/product/tests/test_azure_database_service_rules.py
  tests/product/tests/test_azure_identity_access_management_rules.py
  tests/product/tests/test_azure_key_vault_rules.py
  tests/product/tests/test_azure_logging_and_monitoring_rules.py
  tests/product/tests/test_azure_networking_rules.py
  tests/product/tests/test_azure_storage_account_rules.py
  tests/product/tests/test_azure_virtual_machine_rules.py
  tests/product/tests/test_eks_managed_services_rules.py
Labels: backport-skip

#1827 Add a wrapper allowing safe evidence collection
  security-policies/bundle/compliance/lib/common/common.rego
  security-policies/bundle/compliance/lib/common/test.rego
Labels: backport-skip

#1886 CSI IT Database Rules
  security-policies/RULES.md
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_5/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_5/test.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_4_3_6/rule.rego
  security-policies/bundle/compliance/cis_azure/test_data.rego
  tests/product/tests/data/azure/azure_database_service_test_cases.py
Labels: backport-skip

#1883 [CIS Azure] 2.1.18
  flavors/benchmark/azure_test.go
  go.mod
  go.sum
  resources/fetching/fetcher.go
  resources/fetching/fetchers/azure/assets_enrincher_virtual_machine.go
  resources/fetching/fetchers/azure/assets_enrincher_virtual_machine_test.go
  resources/fetching/fetchers/azure/assets_fetcher.go
  resources/fetching/fetchers/azure/security_fetcher.go
  resources/fetching/fetchers/azure/security_fetcher_test.go
  resources/fetching/preset/azure_preset.go
  resources/providers/azurelib/inventory/asset.go
  resources/providers/azurelib/inventory/keyvault_provider.go
  resources/providers/azurelib/inventory/mock_security_contacts_client.go
  resources/providers/azurelib/inventory/mock_security_contacts_provider_api.go
  resources/providers/azurelib/inventory/security_provider.go
  resources/providers/azurelib/inventory/security_provider_test.go
  resources/providers/azurelib/mock_provider_api.go
  resources/providers/azurelib/provider.go
  resources/utils/maps/maps.go
  security-policies/README.md
  security-policies/RULES.md
  security-policies/bundle/compliance/cis_azure/rules/cis_2_1_18/data.yaml
  security-policies/bundle/compliance/cis_azure/rules/cis_2_1_18/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_2_1_18/test.rego
  security-policies/bundle/compliance/cis_azure/test_data.rego
  security-policies/bundle/compliance/policy/azure/data_adapter.rego
Labels: backport-skip
