Repository elastic/cloudbeat, pull requests merged in 2024-03, with the labels that each got.

#1986 [updatecli] Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#1972 fix 5.1.4 and add integration test
  security-policies/RULES.md
  security-policies/bundle/compliance/cis_azure/rules/cis_5_1_4/rule.rego
  security-policies/bundle/compliance/cis_azure/rules/cis_5_1_4/test.rego
  tests/product/tests/data/azure/azure_storage_account_test_cases.py
Labels: CIS Azure, backport-v8.13.0

#1994 [updatecli] Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#1975 Add missing role definitions to Azure ARM
  deploy/azure/ARM-for-organization-account.dev.json
  deploy/azure/ARM-for-organization-account.json
  deploy/azure/ARM-for-single-account.dev.json
  deploy/azure/ARM-for-single-account.json
Labels: backport-skip

#1980 Fix upgrade flow
  .github/workflows/upgrade-environment.yml
  tests/integration/tests/test_sanity_checks.py
  tests/integrations_setup/upgrade_agents.py
Labels: backport-skip

#1983 [updatecli] Update to elastic/beats@a5454dba2b5e
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2013 Process fetcher improve error logs
  internal/resources/fetching/fetchers/k8s/process_fetcher.go
Labels: backport-v8.13.0

#2023 [updatecli] Update to elastic/beats@7b24d45f66f9
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2022 [updatecli] Update Golang version to 1.21.8
  .go-version
  bin/.go-1.21.8.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: backport-skip, automation, dependency, go

#2021 [updatecli] Update Golang version to 1.21.8
  .go-version
  bin/.go-1.21.8.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: backport-skip, automation, dependency, go

#2009 Fetch AWS Management Account resources only when explicitly selected
  deploy/cloudformation/ec2-types.yml
  deploy/cloudformation/elastic-agent-ec2-cnvm.yml
  deploy/cloudformation/elastic-agent-ec2-cspm-organization.yml
  deploy/cloudformation/elastic-agent-ec2-cspm.yml
  internal/flavors/benchmark/aws_org.go
  internal/flavors/benchmark/aws_org_test.go
  internal/flavors/benchmark/strategy.go
  internal/resources/providers/awslib/iam/iam.go
  internal/resources/providers/awslib/iam/mock_client.go
  internal/resources/providers/awslib/iam/mock_role_getter.go
  internal/resources/providers/awslib/iam/role.go
Labels: backport-skip

#2027 Fix Single Account Azure ARM template
  deploy/azure/ARM-for-organization-account.dev.json
  deploy/azure/ARM-for-organization-account.json
  deploy/azure/ARM-for-single-account.dev.json
  deploy/azure/ARM-for-single-account.json
Labels: backport-v8.13.0

#2031 Add permissions for Azure CIS 9.1 rule
  deploy/azure/ARM-for-single-account.dev.json
  deploy/azure/ARM-for-single-account.json
Labels: backport-v8.13.0

#2028 Fix Organizational Azure ARM template
  deploy/azure/ARM-for-organization-account.dev.json
  deploy/azure/ARM-for-organization-account.json
Labels: backport-v8.13.0

#2035 skip aws managed keys
  internal/resources/providers/awslib/kms/provider.go
  internal/resources/providers/awslib/kms/provider_test.go
Labels: backport-skip

#2043 add aws provider name to org scan
  internal/flavors/benchmark/aws_org.go
Labels: backport-v8.13.0

#2040 [updatecli] Update to elastic/beats@201933e627bb
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2044 Update dev docs
  dev-docs/Cloud-Env-Upgrade.md
Labels: backport-skip

#2049 Fix delete GCP script
  deploy/test-environments/delete_env.sh
  deploy/test-environments/delete_gcp_env.sh
Labels: backport-skip

#2045 [Asset Inventory POC] Fetch S3 buckets
  internal/inventory/asset.go
  internal/inventory/aws/fetcher_ec2_instance.go
  internal/inventory/aws/fetcher_ec2_instance_test.go
  internal/inventory/aws/fetcher_s3_bucket.go
  internal/inventory/aws/fetcher_s3_bucket_test.go
  internal/inventory/aws/fetchers.go
  internal/inventory/aws/mock_ec2_instances_provider.go
  internal/inventory/aws/mock_s3_bucket_provider.go
  internal/inventory/inventory.go
  internal/inventory/inventory_test.go
  internal/resources/providers/awslib/s3/provider.go
  internal/resources/providers/awslib/s3/provider_test.go
  internal/resources/providers/awslib/s3/s3.go
Labels: backport-skip

#2052 [Asset Inventory Poc] Fech IAM Users, Roles and Policies
  internal/flavors/asset_inventory.go
  internal/inventory/asset.go
  internal/inventory/awsfetcher/awsfetchers.go
  internal/inventory/awsfetcher/awsfetchers_test.go
  internal/inventory/awsfetcher/fetcher_ec2_instance.go
  internal/inventory/awsfetcher/fetcher_ec2_instance_test.go
  internal/inventory/awsfetcher/fetcher_iam_policy.go
  internal/inventory/awsfetcher/fetcher_iam_policy_test.go
  internal/inventory/awsfetcher/fetcher_iam_role.go
  internal/inventory/awsfetcher/fetcher_iam_role_test.go
  internal/inventory/awsfetcher/fetcher_iam_user.go
  internal/inventory/awsfetcher/fetcher_iam_user_test.go
  internal/inventory/awsfetcher/fetcher_s3_bucket.go
  internal/inventory/awsfetcher/fetcher_s3_bucket_test.go
  internal/inventory/awsfetcher/mock_ec2_instances_provider.go
  internal/inventory/awsfetcher/mock_iam_policy_provider.go
  internal/inventory/awsfetcher/mock_iam_role_provider.go
  internal/inventory/awsfetcher/mock_iam_user_provider.go
  internal/inventory/awsfetcher/mock_s3_bucket_provider.go
  internal/resources/providers/awslib/iam/iam.go
  internal/resources/providers/awslib/iam/mock_client.go
  internal/resources/providers/awslib/iam/role.go
Labels: backport-skip

#2057 [updatecli] Update to elastic/beats@1ecc9c8dbb61
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2041 [updatecli] Update to elastic/beats@06a11e7cec0f
  cloudbeat.reference.yml
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2012 add rule templates sync workflow
  .github/workflows/sync-rule-templates.yml
  scripts/common.sh
  scripts/sync_rule_templates.sh
Labels: backport-skip

#2000 GA Workflows to Actions
  .github/actions/aws-ci/action.yml
  .github/actions/azure-ci/action.yml
  .github/actions/cnvm-ci/action.yml
  .github/actions/docker-images/action.yml
  .github/actions/gcp-ci/action.yml
  .github/actions/hermit/action.yml
  .github/actions/init-integration/action.yml
  .github/actions/k8s-ci/action.yml
  .github/workflows/aws-ci.yml
  .github/workflows/azure-ci.yml
  .github/workflows/ci.yml
  .github/workflows/cloudbeat-ci.yml
  .github/workflows/cnvm-ci.yml
  .github/workflows/eks-ci.yml
  .github/workflows/gcp-ci.yml
  .github/workflows/k8s-ci.yml
  .github/workflows/unit-test.yml
  bin/hermit.hcl
  scripts/packaging/docker/elastic-agent/Dockerfile
  scripts/packaging/docker/elastic-agent/env.sh
  tests/test_environments/k8s-cloudbeat-tests/templates/standalone-agent.yml
  tests/test_environments/sa-agent-pytest.yml
Labels: backport-skip

#2067 Make ci pull_request_target
  .github/workflows/ci.yml
Labels: backport-skip

#2063 Cleanup redundant data after migrating vanilla K8s tests
  .github/workflows/eks-ci.yml
  .github/workflows/k8s-ci.yml
  tests/commonlib/io_utils.py
  tests/commonlib/utils.py
  tests/product/tests/conftest.py
  tests/product/tests/data/eks/__init__.py
  tests/product/tests/data/eks/eks_file_system_test_cases.py
  tests/product/tests/data/eks/eks_k8s_object_test_cases.py
  tests/product/tests/data/eks/eks_process_test_cases.py
  tests/product/tests/data/file_system/file_system_test_cases.py
  tests/product/tests/data/k8s_object/__init__.py
  tests/product/tests/data/k8s_object/k8s_object_rules.py
  tests/product/tests/data/k8s_object/k8s_object_test_cases.py
  tests/product/tests/data/process/__init__.py
  tests/product/tests/data/process/process_test_cases.py
  tests/product/tests/test_eks_file_system_rules.py
  tests/product/tests/test_eks_k8s_objects_rules.py
  tests/product/tests/test_eks_process_kubelet_rules.py
  tests/product/tests/test_file_system_rules.py
  tests/product/tests/test_k8s_objects_rules.py
  tests/product/tests/test_process_api_server_rules.py
  tests/product/tests/test_process_controller_manager_rules.py
  tests/product/tests/test_process_etcd_rules.py
  tests/product/tests/test_process_kubelet_rules.py
  tests/product/tests/test_process_scheduler_rules.py
  tests/pyproject.toml
Labels: backport-skip

#2068 fix ci results comment
  .github/workflows/ci.yml
Labels: backport-skip

#2070 [Create Environment] Add new tag and fix delete env script
  deploy/test-environments/delete_env.sh
  deploy/test-environments/main.tf
Labels: backport-skip

#1964 minor improvements to version bump workflow
  scripts/bump_cloudbeat.sh
  scripts/bump_integration.sh
Labels: backport-skip
