Repository elastic/cloudbeat, pull requests merged in 2024-07, with the labels that each got.

#2301 [updatecli] Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.aws-iam-authenticator-0.6.21.pkg
  bin/.gcloud-482.0.0.pkg
  bin/.gh-2.52.0.pkg
  bin/.opa-0.66.0.pkg
  bin/aws-iam-authenticator
  bin/bq
  bin/docker-credential-gcloud
  bin/gcloud
  bin/gh
  bin/git-credential-gcloud.sh
  bin/gsutil
  bin/opa
Labels: backport-skip, automation, dependency

#2295 Implement new identifier format for asset inventory
  internal/inventory/asset.go
  internal/inventory/awsfetcher/fetcher_ec2_instance.go
  internal/inventory/awsfetcher/fetcher_ec2_instance_test.go
  internal/inventory/awsfetcher/fetcher_elb.go
  internal/inventory/awsfetcher/fetcher_elb_test.go
  internal/inventory/awsfetcher/fetcher_iam_policy.go
  internal/inventory/awsfetcher/fetcher_iam_policy_test.go
  internal/inventory/awsfetcher/fetcher_iam_role.go
  internal/inventory/awsfetcher/fetcher_iam_role_test.go
  internal/inventory/awsfetcher/fetcher_iam_user.go
  internal/inventory/awsfetcher/fetcher_iam_user_test.go
  internal/inventory/awsfetcher/fetcher_lambda.go
  internal/inventory/awsfetcher/fetcher_lambda_test.go
  internal/inventory/awsfetcher/fetcher_networking.go
  internal/inventory/awsfetcher/fetcher_rds.go
  internal/inventory/awsfetcher/fetcher_rds_test.go
  internal/inventory/awsfetcher/fetcher_s3_bucket.go
  internal/inventory/awsfetcher/fetcher_s3_bucket_test.go
  internal/inventory/awsfetcher/fetcher_sns.go
  internal/inventory/awsfetcher/fetcher_sns_test.go
  internal/inventory/inventory.go
  internal/inventory/inventory_test.go
  internal/resources/providers/awslib/iam/iam.go
  internal/resources/providers/awslib/iam/user.go
Labels: backport-skip

#2291 Add support for namespace suffixes
  internal/config/config.go
  internal/flavors/benchmark/builder/builder.go
  internal/transformer/events_creator.go
  internal/transformer/events_creator_test.go
  internal/vulnerability/events_creator.go
  internal/vulnerability/worker.go
Labels: backport-skip

#2302 Bump cloudbeat version
  .mergify.yml
  deploy/azure/ARM-for-organization-account.dev.json
  deploy/azure/ARM-for-organization-account.json
  deploy/azure/ARM-for-single-account.dev.json
  deploy/azure/ARM-for-single-account.json
  version/version.go
Labels: backport-skip

#2303 Release cloudbeat version
  deploy/azure/ARM-for-organization-account.json
  deploy/azure/ARM-for-single-account.json
Labels: backport-skip

#2304 Fix `scripts/bump_integration.sh` for direct-keys
  scripts/bump_integration.sh
Labels: backport-skip

#2314 [updatecli] Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.elastic-package-0.101.2.pkg
  bin/.gcloud-483.0.0.pkg
  bin/.just-1.30.1.pkg
  bin/bq
  bin/docker-credential-gcloud
  bin/elastic-package
  bin/gcloud
  bin/git-credential-gcloud.sh
  bin/gsutil
  bin/just
Labels: backport-skip, automation, dependency

#2312 [updatecli] Update Golang version to 1.22.5
  .go-version
  bin/.go-1.22.5.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: backport-skip, automation, dependency, go

#2326 [updatecli] Update Golang version to 1.22.5
  .go-version
  bin/.go-1.22.5.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: backport-skip, automation, dependency, go

#2330 [8.14](backport #2270) Bump github.com/Azure/azure-sdk-for-go/sdk/azidentity from 1.5.2 to 1.6.0
  go.mod
  go.sum
Labels: backport

#2345 [updatecli] Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.gcloud-484.0.0.pkg
  bin/.gh-2.53.0.pkg
  bin/.just-1.32.0.pkg
  bin/.regal-0.24.0.pkg
  bin/bq
  bin/docker-credential-gcloud
  bin/gcloud
  bin/gh
  bin/git-credential-gcloud.sh
  bin/gsutil
  bin/just
  bin/regal
Labels: backport-skip, automation, dependency

#2338 Fix Azure package installation script
  tests/integrations_setup/README.md
  tests/integrations_setup/install_cspm_azure_integration.py
Labels: backport-skip

#2347 Fix Azure ARM Template: missing resources
  .github/workflows/arm-template-lint.yml
  deploy/azure/ARM-for-single-account.dev.json
  deploy/azure/ARM-for-single-account.json
Labels: backport-v8.15.0

#2356 Upgrade helm to v3.14.2
  .github/workflows/ci.yml
  deploy/k8s/fleet-managed-agent.yml
  deploy/k8s/standalone-agent.yml
  deploy/kustomize/base/role.yml
  deploy/kustomize/overlays/cloudbeat-vanilla-agent/manifests.yaml
  go.mod
  go.sum
  internal/resources/fetching/fetchers/k8s/kube_fetcher.go
  internal/resources/fetching/fetchers/k8s/kube_fetcher_test.go
  internal/resources/fetching/fetchers/k8s/kube_provider.go
  security-policies/RULES.md
  tests/commonlib/kubernetes.py
  tests/product/tests/data/eks/eks_k8s_object_test_cases.py
  tests/product/tests/data/k8s/k8s_object_cases.py
  tests/test_environments/k8s-cloudbeat-tests/templates/cloudbeat-eks-pytest.yaml
  tests/test_environments/k8s-cloudbeat-tests/templates/standalone-agent.yml
  tests/test_environments/k8s-objects-all-cases.yml
  tests/test_environments/mock-pod.yml
  tests/test_environments/sa-agent-pytest.yml
Labels: backport-v8.15.0

#2367 [updatecli] Update hermit and pre-commit dependencies
  bin/.gcloud-485.0.0.pkg
  bin/.opa-0.67.0.pkg
  bin/.pre-commit-3.8.0.pkg
  bin/bq
  bin/docker-credential-gcloud
  bin/gcloud
  bin/git-credential-gcloud.sh
  bin/gsutil
  bin/opa
  bin/pre-commit
Labels: backport-skip, automation, dependency

#2354 Create ASSETS.md with pre-commit scripts to maintain it
  .mockery.yaml
  .pre-commit-config.yaml
  internal/inventory/ASSETS.md
  internal/inventory/asset.go
  internal/inventory/awsfetcher/fetcher_ec2_instance.go
  internal/inventory/awsfetcher/fetcher_ec2_instance_test.go
  internal/inventory/awsfetcher/fetcher_elb.go
  internal/inventory/awsfetcher/fetcher_elb_test.go
  internal/inventory/awsfetcher/fetcher_iam_policy.go
  internal/inventory/awsfetcher/fetcher_iam_policy_test.go
  internal/inventory/awsfetcher/fetcher_iam_role.go
  internal/inventory/awsfetcher/fetcher_iam_role_test.go
  internal/inventory/awsfetcher/fetcher_iam_user.go
  internal/inventory/awsfetcher/fetcher_iam_user_test.go
  internal/inventory/awsfetcher/fetcher_lambda.go
  internal/inventory/awsfetcher/fetcher_lambda_test.go
  internal/inventory/awsfetcher/fetcher_networking.go
  internal/inventory/awsfetcher/fetcher_rds.go
  internal/inventory/awsfetcher/fetcher_rds_test.go
  internal/inventory/awsfetcher/fetcher_s3_bucket_test.go
  internal/inventory/awsfetcher/fetcher_sns.go
  internal/inventory/awsfetcher/fetcher_sns_test.go
  internal/inventory/cloud_assets.xlsx
  internal/inventory/inventory_test.go
  scripts/update_assets_md/go.mod
  scripts/update_assets_md/go.sum
  scripts/update_assets_md/main.go
  tools/tools.go
Labels: backport-skip

#2365 [updatecli] Update to elastic/beats@e177fc500b53
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2350 Integrate sanity UI tests with the upgrade workflow
  .github/workflows/upgrade-environment.yml
  deploy/cloud/modules/ec/variables.tf
  dev-docs/Cloud-Env-Upgrade.md
Labels: backport-skip

#2366 [updatecli] Update to elastic/beats@971af57dfba0
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2370 Update go-git version to latest
  go.mod
  go.sum
Labels: backport-v8.15.0

#2333 Silence PodSecurityPolicy deprecation warnings (and more)
  go.mod
  go.sum
  internal/dataprovider/providers/k8s/client_provider.go
  internal/processor/add_cluster_id/add_cluster_id.go
Labels: backport-skip

#2372 Bump docker cli dependeny
  go.mod
  go.sum
Labels: backport-v8.15.0
