Repository elastic/cloudbeat, pull requests merged in 2024-10, with the labels that each got.

#2564 [updatecli] Update to elastic/beats@775d26d94a5a
  go.mod
  go.sum
  internal/resources/providers/awslib/cached_region_selector.go
Labels: backport-skip, automation, dependency, go

#2565 [updatecli] Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.gcloud-495.0.0.pkg
  bin/.gh-2.58.0.pkg
  bin/.just-1.36.0.pkg
  bin/.opa-0.69.0.pkg
  bin/.pre-commit-4.0.0.pkg
  bin/bq
  bin/docker-credential-gcloud
  bin/gcloud
  bin/gh
  bin/git-credential-gcloud.sh
  bin/gsutil
  bin/just
  bin/opa
  bin/pre-commit
Labels: automation, dependency, backport-v8.x, breaking-dependecy-update

#2581 [updatecli] Update Golang version to 1.23.2
  .go-version
  bin/.go-1.23.2.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: automation, dependency, go, backport-v8.x

#2580 feat: replace x/exp with stdlib functions
  go.mod
  internal/resources/fetching/fetchers/azure/assets_fetcher.go
  internal/resources/fetching/fetchers/azure/assets_fetcher_test.go
  internal/resources/fetching/fetchers/azure/batch_fetcher.go
  internal/resources/fetching/fetchers/azure/batch_fetcher_test.go
  internal/vulnerability/events_creator.go
  scripts/update_assets_md/go.mod
  scripts/update_assets_md/go.sum
  scripts/update_assets_md/main.go
  tools/tools.go
Labels: backport-v8.x

#2588 Increase LeaseDuration to create stickiness
  internal/uniqueness/leaderelection_const.go
Labels: backport-v8.x

#2500 mergify: replace queue action for queue_rules
  .mergify.yml
Labels: backport-v8.x

#2594 Update version compatibility handling
  .github/workflows/weekly-serverless.yml
  deploy/azure/install_agent_az_cli.sh
Labels: Team:Cloud Security, automation, backport-v8.x

#2600 Skip Azure PostgreSQL tests
  security-policies/RULES.md
  tests/product/tests/data/azure/azure_database_service_test_cases.py
Labels: backport-v8.x

#2601 Update k8s integration tests timeout
  tests/integration/tests/test_cloudbeat_integration.py
Labels: backport-skip

#2562 fix gh artifacts upload for docker images
  .github/actions/docker-images/action.yml
Labels: backport-v8.15.0, backport-v8.x

#2606 Revert "fix gh artifacts upload for docker images"
  .github/actions/docker-images/action.yml
Labels: backport-skip

#2598 [updatecli] Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.elastic-package-0.106.0.pkg
  bin/.gcloud-497.0.0.pkg
  bin/.gh-2.59.0.pkg
  bin/.pre-commit-4.0.1.pkg
  bin/.regal-0.28.0.pkg
  bin/.shfmt-3.10.0.pkg
  bin/bq
  bin/docker-credential-gcloud
  bin/elastic-package
  bin/gcloud
  bin/gh
  bin/git-credential-gcloud.sh
  bin/gsutil
  bin/pre-commit
  bin/regal
  bin/shfmt
Labels: automation, dependency, backport-v8.x

#2628 Increase azure fetcher timeout
  internal/flavors/benchmark/azure.go
  internal/flavors/benchmark/azure_test.go
Labels: backport-v8.15.0, backport-v8.x

#2631 Add backport-v8.16.0 label to main apart from 8.x
  .mergify.yml
Labels: backport-skip

#2633 [Asset Inventory][AWS][CI] Update AWS Asset Inventory variable names
  tests/integrations_setup/install_aws_asset_inventory_integration.py
Labels: backport-v8.x, backport-v8.16.0

#2636 [Asset Inventory][Azure][CI] Update Azure variable names
  tests/integrations_setup/install_azure_asset_inventory_integration.py
Labels: backport-v8.x, backport-v8.16.0

#2591 [Asset Inventory][AWS & Azure] Support organization account deployment type
  .github/workflows/ci-pull_request.yml
  .github/workflows/publish-cloudformation.yml
  deploy/asset-inventory-arm/.gitignore
  deploy/asset-inventory-arm/ARM-for-organization-account.dev.json
  deploy/asset-inventory-arm/ARM-for-organization-account.json
  deploy/asset-inventory-arm/ARM-for-single-account.dev.json
  deploy/asset-inventory-arm/ARM-for-single-account.json
  deploy/asset-inventory-arm/README.md
  deploy/asset-inventory-arm/generate_dev_template.py
  deploy/asset-inventory-arm/install-agent-dev.sh
  deploy/asset-inventory-arm/install-agent.sh
  deploy/asset-inventory-arm/install_agent_az_cli.sh
  deploy/asset-inventory-cloudformation/.gitignore
  deploy/asset-inventory-cloudformation/README.md
  deploy/asset-inventory-cloudformation/config.go
  deploy/asset-inventory-cloudformation/ec2-types.yml
  deploy/asset-inventory-cloudformation/elastic-agent-ec2-organization.yml
  deploy/asset-inventory-cloudformation/elastic-agent-ec2.yml
  deploy/asset-inventory-cloudformation/gomain.go
  internal/flavors/assetinventory/strategy.go
  internal/flavors/assetinventory/strategy_aws.go
  justfile
  scripts/bump_integration.sh
  scripts/publish_cft.sh
Labels: backport-v8.x

#2648 Fix GCP Labeling in test environment workflow
  .github/workflows/test-environment.yml
Labels: backport-v8.x

#2642 Disable deployment of Asset Inventory for versions below 8.16
  .github/workflows/ci.yml
  .github/workflows/test-environment.yml
  .github/workflows/upgrade-environment.yml
Labels: backport-skip

#2649 azure: add integration tests cases
  internal/inventory/gcpfetcher/fetcher_assets.go
  tests/product/tests/data/gcp_asset_inventory/test_cases.py
Labels: backport-v8.x
