Repository elastic/cloudbeat, pull requests merged in 2024-08, with the labels that each got.

#2378 eks ci - enable config 1
  .github/workflows/eks-ci.yml
  tests/test_environments/aws/eks_config/test-eks-config-1-node-2-10-kubelet-args.conf
  tests/test_environments/k8s-cloudbeat-tests/values.yaml
Labels: backport-skip

#2382 Update upload artifacts action
  .github/actions/docker-images/action.yml
  tests/test_environments/k8s-cloudbeat-tests/values.yaml
Labels: backport-skip

#2384 Skip integration test
  tests/integration/tests/test_cloudbeat_integration.py
Labels: backport-skip

#2379 Add `related.entities` to asset inventory
  internal/inventory/asset.go
  internal/inventory/inventory.go
  internal/inventory/inventory_test.go
Labels: backport-skip

#2393 [updatecli] Update to elastic/beats@81bc303d0b8f
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2395 [updatecli] Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.elastic-package-0.102.0.pkg
  bin/.gcloud-486.0.0.pkg
  bin/.gh-2.54.0.pkg
  bin/.just-1.34.0.pkg
  bin/bq
  bin/docker-credential-gcloud
  bin/elastic-package
  bin/gcloud
  bin/gh
  bin/git-credential-gcloud.sh
  bin/gsutil
  bin/just
Labels: backport-skip, automation, dependency

#2396 [updatecli] Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2381 Update EKS test environment configuration
  tests/test_environments/aws/eks_config/test-eks-config-1-node-2-10-kubelet-args.conf
  tests/test_environments/k8s-cloudbeat-tests/values.yaml
  tests/test_environments/values/ci-eks-config-1.yml
Labels: backport-skip

#2380 Consistently use pointers in EC2 provider
  internal/inventory/awsfetcher/fetcher_networking.go
  internal/resources/providers/awslib/ec2/provider.go
Labels: bug, backport-skip

#2398 Rename from `related.entities` to `related.entity`
  internal/inventory/inventory.go
  internal/inventory/inventory_test.go
Labels: backport-skip

#2399 Bump trivy to v0.54.1 and fix breaking changes
  go.mod
  go.sum
  internal/flavors/vulnerability.go
  internal/vulnerability/runner.go
  internal/vulnerability/scanner.go
Labels: backport-skip

#2421 Revert "Bump trivy to v0.54.1 and fix breaking changes"
  go.mod
  go.sum
  internal/flavors/vulnerability.go
  internal/vulnerability/runner.go
  internal/vulnerability/scanner.go
Labels: backport-skip

#2427 Bump Trivy to v0.54.1
  .buildkite/scripts/generate_notice.py
  .github/workflows/ci.yml
  go.mod
  go.sum
  internal/flavors/vulnerability.go
  internal/vulnerability/runner.go
  internal/vulnerability/scanner.go
Labels: backport-skip

#2414 [updatecli] Update Golang version to 1.22.6
  .go-version
  bin/.go-1.22.6.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: backport-skip, automation, dependency, go

#2413 [updatecli] Update Golang version to 1.22.6
  .go-version
  bin/.go-1.22.6.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: backport-skip, automation, dependency, go

#2430 Bump beats
  go.mod
  go.sum
Labels: backport-skip

#2418 [updatecli] Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.gcloud-487.0.0.pkg
  bin/.opa-0.67.1.pkg
  bin/.yq-4.44.3.pkg
  bin/bq
  bin/docker-credential-gcloud
  bin/gcloud
  bin/git-credential-gcloud.sh
  bin/gsutil
  bin/opa
  bin/yq
Labels: backport-skip, automation, dependency

#2431 Temporarily disable long running tests
  .github/workflows/ci.yml
Labels: backport-skip

#2419 [updatecli] Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2425 Add infra scripts to provision resources for CDR
  deploy/cloud/modules/aws/cloudtrail/main.tf
  deploy/cloud/modules/aws/cloudtrail/outputs.tf
  deploy/cloud/modules/aws/cloudtrail/variables.tf
  deploy/test-environments/main.tf
  deploy/test-environments/output.tf
  deploy/test-environments/variables.tf
  tests/fleet_api/package_policy_api.py
  tests/fleet_api/utils.py
  tests/integrations_setup/configuration_fleet.py
  tests/integrations_setup/data/cloudtrail-pkg.json
  tests/integrations_setup/install_cloudtrail_integration.py
Labels: backport-skip

#2432 Set dependencies update interval to monthly
  .github/dependabot.yml
Labels: backport-skip

#2429 Bump snyk monitored branch on releases
  .github/workflows/bump-version.yml
  scripts/bump_cloudbeat.sh
Labels: backport-skip

#2439 fix terraform output values
  deploy/test-environments/output.tf
Labels: backport-skip

#2440 [updatecli] Update to elastic/beats@07fb76e4475a
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2445 [updatecli] Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2442 [updatecli] Update hermit and pre-commit dependencies
  .github/workflows/ci-pull_request.yml
  .pre-commit-config.yaml
  bin/.aws-iam-authenticator-0.6.23.pkg
  bin/.gcloud-488.0.0.pkg
  bin/.golangci-lint-1.60.1.pkg
  bin/.kind-0.24.0.pkg
  bin/.regal-0.25.0.pkg
  bin/.shfmt-3.9.0.pkg
  bin/aws-iam-authenticator
  bin/bq
  bin/docker-credential-gcloud
  bin/gcloud
  bin/git-credential-gcloud.sh
  bin/golangci-lint
  bin/gsutil
  bin/kind
  bin/regal
  bin/shfmt
  internal/resources/fetching/fetchers/k8s/process_fetcher_test.go
  internal/resources/providers/awslib/kms/provider.go
Labels: backport-skip, automation, dependency

#2428 Revert CF version check
  deploy/cloudformation/elastic-agent-ec2-cnvm.yml
  deploy/cloudformation/elastic-agent-ec2-cspm-organization.yml
  deploy/cloudformation/elastic-agent-ec2-cspm.yml
Labels: backport-skip

#2448 GA: disable cache restore
  .github/actions/hermit/action.yml
Labels: backport-v8.15.0

#2423 Add Azure Resource Graph assets to Asset Inventory
  internal/inventory/ASSETS.md
  internal/inventory/asset.go
  internal/inventory/azurefetcher/azurefetchers.go
  internal/inventory/azurefetcher/fetcher_resource_graph.go
  internal/inventory/azurefetcher/fetcher_resource_graph_test.go
  internal/inventory/azurefetcher/mock_resource_graph_provider.go
  internal/inventory/cloud_assets.xlsx
  internal/resources/providers/azurelib/inventory/asset.go
Labels: backport-skip

#2405 Update VM labels in environment creation workflow
  .github/workflows/test-environment.yml
Labels: backport-skip

#2455 [updatecli] Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2454 [updatecli] Update hermit and pre-commit dependencies
  bin/.aws-iam-authenticator-0.6.25.pkg
  bin/.gcloud-489.0.0.pkg
  bin/.gh-2.55.0.pkg
  bin/.golangci-lint-1.60.3.pkg
  bin/aws-iam-authenticator
  bin/bq
  bin/docker-credential-gcloud
  bin/gcloud
  bin/gh
  bin/git-credential-gcloud.sh
  bin/golangci-lint
  bin/gsutil
Labels: backport-skip, automation, dependency

#2452 [updatecli] Update to elastic/beats@af33fad4d50b
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2458 Move az and gcp login to above tf on create env
  .github/workflows/test-environment.yml
Labels: backport-skip

#2451 Add GCP infra scripts to provision resources for CDR
  deploy/cloud/modules/gcp/vm/main.tf
  deploy/cloud/modules/gcp/vm/outputs.tf
  deploy/cloud/modules/gcp/vm/terraform.tf
  deploy/cloud/modules/gcp/vm/variables.tf
  deploy/test-environments/main.tf
  deploy/test-environments/output.tf
  deploy/test-environments/terraform.tf
  deploy/test-environments/variables.tf
  tests/integrations_setup/configuration_fleet.py
  tests/integrations_setup/data/gcp-audit-logs-pkg.json
  tests/integrations_setup/install_gcp_audit_logs_integration.py
Labels: backport-skip

#2400 Fetch org name only for organization-account
  internal/resources/providers/gcplib/inventory/provider.go
  internal/resources/providers/gcplib/inventory/provider_test.go
Labels: backport-skip

#2461 Add missing client to posture flavor
  internal/flavors/posture.go
  internal/flavors/vulnerability.go
Labels: backport-skip
