Repository elastic/cloudbeat, pull requests merged in 2025-07, with the labels that each got.

#3433 [Cloud Security] Fix agentless configuration for Serverless CreateEnvironment GH Actions
  .github/actions/cis-agentless/action.yml
  .github/workflows/test-environment.yml
  tests/integrations_setup/install_agentless_integrations.py
Labels: Team:Cloud Security, automation

#3453 Remove cloudbeat-root from single-account cspm
  deploy/cloudformation/elastic-agent-ec2-cspm.yml
Labels: backport-v9.1.0, backport-v8.19.0

#3465 Switch from mitchellh/mapstructure to go-viper/mapstructure
  .golangci.yaml
  NOTICE.txt
  go.mod
  go.sum
  internal/dataprovider/providers/common/data_provider.go
  internal/evaluator/opa.go
  internal/inventory/asset.go
  internal/inventory/azurefetcher/fetcher_resource_graph.go
  internal/inventory/gcpfetcher/fetcher_assets.go
  internal/resources/fetching/fetchers/azure/assets_enrincher_virtual_machine.go
  internal/resources/fetching/fetchers/k8s/process_fetcher_test.go
Labels: backport-skip

#3481 [aws]: switch to all region selector for kms provider
  internal/resources/providers/awslib/kms/kms.go
  internal/resources/providers/awslib/kms/provider.go
Labels: backport-active-all
