Repository elastic/cloudbeat, pull requests merged in 2025-03, with the labels that each got.

#3066 [updatecli] 8.x - Update to elastic/beats@160cce6c0535
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#3067 [updatecli] main - Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.awscli-2.24.14.pkg
  bin/.gcloud-512.0.0.pkg
  bin/.regal-0.31.1.pkg
  bin/aws
  bin/aws_completer
  bin/bq
  bin/docker-credential-gcloud
  bin/gcloud
  bin/git-credential-gcloud.sh
  bin/gsutil
  bin/regal
Labels: backport-skip, automation, dependency

#3069 [updatecli] 8.x - Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#3070 [updatecli] main - Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#3068 [updatecli] 8.x - Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.awscli-2.24.14.pkg
  bin/.gcloud-512.0.0.pkg
  bin/.regal-0.31.1.pkg
  bin/aws
  bin/aws_completer
  bin/bq
  bin/docker-credential-gcloud
  bin/gcloud
  bin/git-credential-gcloud.sh
  bin/gsutil
  bin/regal
Labels: backport-skip, automation, dependency

#2960 cloud connectors role chaining
  internal/config/config.go
  internal/config/config_test.go
  internal/flavors/benchmark/aws.go
  internal/flavors/benchmark/aws_org.go
  internal/flavors/benchmark/aws_test.go
  internal/resources/providers/awslib/config.go
  scripts/packaging/docker/elastic-agent/Dockerfile
Labels: backport-skip

#3088 Bump the version used for test environments.
  bin/hermit.hcl
Labels: backport-skip, automation

#2953 POC - Adding CIS and CDR integrations to an existing deployment
  .github/workflows/install-integrations.yml
  .github/workflows/test-environment.yml
  dev-docs/Cloud-Env-Testing.md
Labels: Team:Cloud Security, backport-v8.x

#3098 Fix EKS cluster deployment
  deploy/test-environments/modules/aws/eks/oidc.tf
Labels: backport-v8.x

#3107 ci: pin actions to specific commits
  .github/actions/aws-asset-inventory-ci/action.yml
  .github/actions/aws-ci/action.yml
  .github/actions/azure-asset-inventory-ci/action.yml
  .github/actions/azure-ci/action.yml
  .github/actions/cnvm-ci/action.yml
  .github/actions/docker-images/action.yml
  .github/actions/gcp-asset-inventory-ci/action.yml
  .github/actions/gcp-ci/action.yml
  .github/actions/hermit/action.yml
  .github/actions/init-integration/action.yml
  .github/actions/k8s-ci/action.yml
  .github/actions/kibana-ftr/action.yml
  .github/actions/slack-notification/action.yml
  .github/workflows/arm-template-lint.yml
  .github/workflows/bump-version.yml
  .github/workflows/ci-pull_request.yml
  .github/workflows/ci.yml
  .github/workflows/cloudformation-ci.yml
  .github/workflows/destroy-environment.yml
  .github/workflows/destroy-expired-environment.yml
  .github/workflows/eks-ci.yml
  .github/workflows/packaging.yml
  .github/workflows/publish-cloudformation.yml
  .github/workflows/rerun-flaky-workflows.yml
  .github/workflows/sync-internal-cloudbeat-version.yml
  .github/workflows/sync-rule-templates.yml
  .github/workflows/test-agent-compatibility.yml
  .github/workflows/test-ech-agentless.yml
  .github/workflows/test-environment.yml
  .github/workflows/test-gcp-dm.yml
  .github/workflows/test-opa-coverage.yml
  .github/workflows/test-opa-policies.yml
  .github/workflows/unit-test.yml
  .github/workflows/updatecli.yml
  .github/workflows/upgrade-environment.yml
  .github/workflows/weekly-serverless.yml
Labels: backport-active-all

#3090 cnvm: Delete snapshots after scanning them
  internal/flavors/vulnerability.go
  internal/resources/providers/awslib/config.go
  internal/resources/providers/awslib/ec2/provider.go
  internal/vulnerability/cleaner.go
  internal/vulnerability/cleaner_test.go
  internal/vulnerability/events_creator.go
  internal/vulnerability/mock_replicator_provider.go
  internal/vulnerability/mock_snapshot_cleaner.go
  internal/vulnerability/mock_snapshot_creator_deleter.go
  internal/vulnerability/mock_snapshot_describer.go
  internal/vulnerability/mock_worker_provider.go
  internal/vulnerability/replicator.go
  internal/vulnerability/replicator_test.go
  internal/vulnerability/runner.go
  internal/vulnerability/runner_test.go
  internal/vulnerability/scanner.go
  internal/vulnerability/scanner_test.go
  internal/vulnerability/snapshot.go
  internal/vulnerability/snapshot_test.go
  internal/vulnerability/verifier.go
  internal/vulnerability/verifier_test.go
  internal/vulnerability/worker.go
  internal/vulnerability/worker_test.go
Labels: backport-active-all

#3135 Add flaky test template
  .github/ISSUE_TEMPLATE/flaky-test.yml
Labels: backport-skip

#3138 Update flaky-test.yml descriptions
  .github/ISSUE_TEMPLATE/flaky-test.yml
Labels: backport-skip

#3142 [Asset Inventory][Azure] Do not add --install-servers flag for versions < 9.0
  deploy/asset-inventory-arm/install-agent.sh
Labels: Team:Cloud Security, backport-v8.x

#3143 cnvm: Delete old snapshots on startup
  internal/resources/providers/awslib/ec2/ebs_snapshot.go
  internal/resources/providers/awslib/ec2/provider.go
  internal/vulnerability/mock_snapshot_creator_deleter.go
  internal/vulnerability/snapshot.go
  internal/vulnerability/snapshot_test.go
  internal/vulnerability/worker.go
  internal/vulnerability/worker_test.go
Labels: backport-v8.x

#3147 Update EKS cluster version
  deploy/test-environments/modules/aws/eks/eks-cluster.tf
  deploy/test-environments/modules/aws/eks/oidc.tf
Labels: backport-v8.x
