Repository elastic/cloudbeat, pull requests merged in 2025-06, with the labels that each got.

#3240 use relevant evidence fields for cis_gcp 2.13
  security-policies/bundle/compliance/cis_gcp/rules/cis_2_13/rule.rego
  security-policies/bundle/compliance/lib/common/common.rego
Labels: backport-v8.19.0

#3249 use relevant evidence fields for cis_gcp 2.2
  security-policies/bundle/compliance/cis_gcp/rules/cis_2_2/rule.rego
Labels: backport-v8.19.0

#3333 [Cloud Security] Align asset inventory cloud formation S3 object name with CSPM naming convention
  scripts/publish_cft.sh
Labels: backport-skip

#3346 Manually bump to latest trivy
  go.mod
  go.sum
  internal/flavors/assetinventory/strategy_test.go
  internal/vulnerability/runner.go
  internal/vulnerability/scanner_test.go
Labels: backport-v8.19.0

#3358 [updatecli] main - Update Golang version to 1.24.4
  .go-version
  bin/.go-1.24.4.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: backport-skip, automation, dependency, go

#3298 [updatecli] main - Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.aws-iam-authenticator-0.7.2.pkg
  bin/.awscli-2.27.33.pkg
  bin/.elastic-package-0.111.0.pkg
  bin/.gcloud-526.0.0.pkg
  bin/.gh-2.74.1.pkg
  bin/.golangci-lint-2.1.6.pkg
  bin/.jq-1.8.0.pkg
  bin/.just-1.40.0.pkg
  bin/.kind-0.29.0.pkg
  bin/.opa-1.5.1.pkg
  bin/.pre-commit-4.2.0.pkg
  bin/.regal-0.34.1.pkg
  bin/.shfmt-3.11.0.pkg
  bin/.yq-4.45.4.pkg
  bin/aws
  bin/aws-iam-authenticator
  bin/aws_completer
  bin/bq
  bin/docker-credential-gcloud
  bin/elastic-package
  bin/gcloud
  bin/gh
  bin/git-credential-gcloud.sh
  bin/golangci-lint
  bin/gsutil
  bin/jq
  bin/just
  bin/kind
  bin/opa
  bin/pre-commit
  bin/regal
  bin/shfmt
  bin/yq
  deploy/asset-inventory-cloudformation/elastic-agent-direct-access-key-organization.yml
  deploy/asset-inventory-cloudformation/elastic-agent-ec2-organization.yml
  deploy/cloudformation/cloud-connectors-remote-role-organization.yml
  deploy/cloudformation/elastic-agent-direct-access-key-cspm-organization.yml
  deploy/cloudformation/elastic-agent-ec2-cspm-organization.yml
  security-policies/bundle/compliance/policy/gcp/kms/ensure_key_rotation.rego
  security-policies/dev/README.md
Labels: backport-skip, automation, dependency

#3365 [updatecli] main - Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#3373 Skip flaky test case
  tests/integration/tests/test_standalone_agent_integration.py
Labels: backport-v9.0.0, backport-v8.18.0, backport-v8.19.0

#3415 Fix bump-workflow boolean inputs
  .github/workflows/bump-version.yml
Labels: backport-skip
