Repository elastic/cloudbeat, pull requests merged in 2025-01, with the labels that each got.

#2877 golangci-lint: Add more linters
  .golangci.yaml
  bin/.golangci-lint-1.63.3.pkg
  bin/golangci-lint
  internal/inventory/azurefetcher/fetcher_storage.go
  internal/launcher/launcher.go
  internal/launcher/launcher_test.go
  internal/processor/add_cluster_id/errors.go
  internal/resources/providers/awslib/current_region_selecot_test.go
  internal/resources/providers/awslib/current_region_selector.go
  internal/resources/providers/awslib/mock_current_cloud_region.go
  internal/resources/utils/user/user.go
Labels: technical debt, backport-v8.x

#2886 Upgrade to poetry 2.0
  .pre-commit-config.yaml
  scripts/sync_rule_templates.sh
  security-policies/poetry.lock
  security-policies/pyproject.toml
  tests/poetry.lock
  tests/pyproject.toml
Labels: backport-v8.x

#2884 [updatecli] main - Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.awscli-2.22.28.pkg
  bin/.golangci-lint-1.63.4.pkg
  bin/aws
  bin/aws_completer
  bin/golangci-lint
Labels: backport-skip, automation, dependency

#2885 [updatecli] 8.x - Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2881 [updatecli] main - Update to elastic/beats@e3e23320e5d7
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2883 [updatecli] 8.x - Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.awscli-2.22.28.pkg
  bin/.golangci-lint-1.63.4.pkg
  bin/aws
  bin/aws_completer
  bin/golangci-lint
Labels: backport-skip, automation, dependency

#2882 [updatecli] 8.x - Update to elastic/beats@a93092894645
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2889 Install poetry export
  tests/Dockerfile
  tests/pyproject.toml
Labels: backport-v8.x, backport-v8.17.0

#2892 Install poetry export on hermit init env
  .github/actions/hermit/action.yml
Labels: backport-v8.x

#2897 Fix 8.17 backport label
  .mergify.yml
Labels: backport-skip

#2880 [updatecli] 8.17 - Update to elastic/beats@5fd5e6553225
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2902 [Asset Inventory] Run fetchers periodically
  internal/flavors/assetinventory/strategy.go
  internal/inventory/inventory.go
  internal/inventory/inventory_test.go
Labels: backport-v8.x

#2911 [updatecli] 8.17 - Update to elastic/beats@424070e87d83
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2912 [updatecli] 8.x - Update to elastic/beats@1861acf98ede
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2916 [updatecli] main - Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2915 [updatecli] 8.x - Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2879 Refactor asset inventory
  internal/inventory/ASSETS.md
  internal/inventory/asset.go
  internal/inventory/awsfetcher/fetcher_ec2_instance.go
  internal/inventory/awsfetcher/fetcher_ec2_instance_test.go
  internal/inventory/awsfetcher/fetcher_elb.go
  internal/inventory/awsfetcher/fetcher_elb_test.go
  internal/inventory/awsfetcher/fetcher_iam_policy.go
  internal/inventory/awsfetcher/fetcher_iam_policy_test.go
  internal/inventory/awsfetcher/fetcher_iam_role.go
  internal/inventory/awsfetcher/fetcher_iam_role_test.go
  internal/inventory/awsfetcher/fetcher_iam_user.go
  internal/inventory/awsfetcher/fetcher_iam_user_test.go
  internal/inventory/awsfetcher/fetcher_lambda.go
  internal/inventory/awsfetcher/fetcher_lambda_test.go
  internal/inventory/awsfetcher/fetcher_networking.go
  internal/inventory/awsfetcher/fetcher_rds.go
  internal/inventory/awsfetcher/fetcher_rds_test.go
  internal/inventory/awsfetcher/fetcher_s3_bucket.go
  internal/inventory/awsfetcher/fetcher_s3_bucket_test.go
  internal/inventory/awsfetcher/fetcher_sns.go
  internal/inventory/awsfetcher/fetcher_sns_test.go
  internal/inventory/azurefetcher/fetcher_account.go
  internal/inventory/azurefetcher/fetcher_account_test.go
  internal/inventory/azurefetcher/fetcher_activedirectory.go
  internal/inventory/azurefetcher/fetcher_activedirectory_test.go
  internal/inventory/azurefetcher/fetcher_resource_graph.go
  internal/inventory/azurefetcher/fetcher_resource_graph_test.go
  internal/inventory/azurefetcher/fetcher_storage.go
  internal/inventory/azurefetcher/fetcher_storage_test.go
  internal/inventory/cloud_assets.xlsx
  internal/inventory/gcpfetcher/fetcher_assets.go
  internal/inventory/gcpfetcher/fetcher_assets_test.go
  internal/inventory/inventory.go
  internal/inventory/inventory_test.go
  scripts/update_assets_md/main.go
  tests/commonlib/io_utils.py
  tests/commonlib/utils.py
  tests/product/tests/data/asset_inventory_test_case.py
  tests/product/tests/data/aws_asset_inventory/test_cases.py
  tests/product/tests/data/azure_asset_inventory/test_cases.py
  tests/product/tests/data/gcp_asset_inventory/test_cases.py
  tests/product/tests/test_aws_asset_inventory.py
  tests/product/tests/test_azure_asset_inventory.py
  tests/product/tests/test_gcp_asset_inventory.py
Labels: backport-v8.x

#2913 [updatecli] 8.x - Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.awscli-2.22.33.pkg
  bin/.gcloud-505.0.0.pkg
  bin/.gh-2.65.0.pkg
  bin/.yq-4.45.1.pkg
  bin/aws
  bin/aws_completer
  bin/bq
  bin/docker-credential-gcloud
  bin/gcloud
  bin/gh
  bin/git-credential-gcloud.sh
  bin/gsutil
  bin/yq
Labels: backport-skip, automation, dependency

#2920 Add support for VERSION_QUALIFIER DRA
  .buildkite/pipeline.yml
  .buildkite/scripts/package.sh
  .buildkite/scripts/publish.sh
  magefile.go
  version/settings.go
  version/version.go
Labels: backport-skip

#2914 [updatecli] main - Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.awscli-2.22.33.pkg
  bin/.gcloud-505.0.0.pkg
  bin/.gh-2.65.0.pkg
  bin/.yq-4.45.1.pkg
  bin/aws
  bin/aws_completer
  bin/bq
  bin/docker-credential-gcloud
  bin/gcloud
  bin/gh
  bin/git-credential-gcloud.sh
  bin/gsutil
  bin/yq
Labels: backport-skip, automation, dependency

#2922 Omit snapshot dra when VERSION_QUALIFIER is set
  .buildkite/pipeline.yml
Labels: backport-skip

#2941 Fix EKS ci
  .github/workflows/eks-ci.yml
Labels: backport-v8.x

#2942 [Release] Update version to 8.17.2
  version/version.go
Labels: release

#2934 github-actions: ubuntu-20.04 will be fully retired by April 1, 2025
  .github/workflows/ci.yml
  .github/workflows/cloudformation-ci.yml
  .github/workflows/destroy-environment.yml
  .github/workflows/eks-ci.yml
  .github/workflows/packaging.yml
  .github/workflows/publish-cloudformation.yml
  .github/workflows/test-environment.yml
  .github/workflows/unit-test.yml
  .github/workflows/upgrade-environment.yml
Labels: backport-v8.x

#2949 [updatecli] main - Update Golang version to 1.23.5
  .go-version
  bin/.go-1.23.5.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: backport-skip, automation, dependency, go

#2924 [updatecli] 8.x - Update Golang version to 1.23.5
  .go-version
  bin/.go-1.23.5.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: backport-skip, automation, dependency, go

#2926 [updatecli] 8.17 - Update Golang version to 1.23.5
  .go-version
  bin/.go-1.23.5.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: backport-skip, automation, dependency, go

#2919 Add ECH agentless and agent-based installation workflow
  .github/workflows/test-ech-agentless.yml
Labels: backport-v8.x

#2950 [buildkite]: get version qualifier from google bucket
  .buildkite/pipeline.yml
  .buildkite/scripts/package.sh
  .buildkite/scripts/publish.sh
  .buildkite/scripts/qualifier.sh
Labels: backport-skip

#2958 [main] - Update to elastic/beats
  go.mod
  go.sum
Labels: backport-v8.x

#2938 [Asset Inventory][Azure] Add storage asset fetchers
  internal/inventory/ASSETS.md
  internal/inventory/asset.go
  internal/inventory/azurefetcher/fetcher_storage.go
  internal/inventory/azurefetcher/fetcher_storage_test.go
  internal/inventory/azurefetcher/mock_storage_provider.go
  internal/inventory/cloud_assets.xlsx
  internal/resources/providers/azurelib/inventory/asset.go
  internal/resources/providers/azurelib/inventory/mock_storage_account_provider_api.go
  internal/resources/providers/azurelib/inventory/storage_provider.go
  internal/resources/providers/azurelib/inventory/storage_provider_test.go
  internal/resources/providers/azurelib/mock_provider_api.go
  tests/product/tests/data/azure_asset_inventory/test_cases.py
  tests/product/tests/test_aws_asset_inventory.py
  tests/product/tests/test_azure_asset_inventory.py
  tests/product/tests/test_gcp_asset_inventory.py
  tests/pyproject.toml
Labels: backport-v8.x

#2929 [updatecli] 8.17 - Update to elastic/beats@05e15fcbbbba
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2931 [updatecli] main - Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.awscli-2.23.6.pkg
  bin/.gcloud-507.0.0.pkg
  bin/.just-1.39.0.pkg
  bin/.opa-1.0.1.pkg
  bin/.pre-commit-4.1.0.pkg
  bin/.regal-0.30.2.pkg
  bin/aws
  bin/aws_completer
  bin/bq
  bin/docker-credential-gcloud
  bin/gcloud
  bin/git-credential-gcloud.sh
  bin/gsutil
  bin/just
  bin/opa
  bin/pre-commit
  bin/regal
  security-policies/bundle/compliance/lib/common/common.rego
  security-policies/bundle/compliance/policy/aws_eks/ensure_private_access.rego
Labels: backport-skip, automation, dependency

#2933 [updatecli] 8.x - Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2930 [updatecli] 8.x - Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.awscli-2.23.6.pkg
  bin/.gcloud-507.0.0.pkg
  bin/.just-1.39.0.pkg
  bin/.opa-1.0.1.pkg
  bin/.pre-commit-4.1.0.pkg
  bin/.regal-0.30.2.pkg
  bin/aws
  bin/aws_completer
  bin/bq
  bin/docker-credential-gcloud
  bin/gcloud
  bin/git-credential-gcloud.sh
  bin/gsutil
  bin/just
  bin/opa
  bin/pre-commit
  bin/regal
  security-policies/bundle/compliance/lib/common/common.rego
  security-policies/bundle/compliance/policy/aws_eks/ensure_private_access.rego
Labels: backport-skip, automation, dependency

#2932 [updatecli] main - Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2963 [Bump workflow] Add condition for integration version bumping
  .github/workflows/bump-version.yml
Labels: backport-v8.x

#2965 Bump cloudbeat version
  .mergify.yml
  deploy/azure/ARM-for-organization-account.dev.json
  deploy/azure/ARM-for-organization-account.json
  deploy/azure/ARM-for-single-account.dev.json
  deploy/azure/ARM-for-single-account.json
  version/version.go
Labels: backport-skip

#2966 Release cloudbeat version
  deploy/azure/ARM-for-organization-account.json
  deploy/azure/ARM-for-single-account.json
Labels: backport-skip

#2969 [mergify] add 8.18 label to main
  .mergify.yml
Labels: backport-v8.x
