Repository elastic/cloudbeat, pull requests merged in 2025-04, with the labels that each got.

#3155 Update to golangci-lint v2
  .github/workflows/ci-pull_request.yml
  .golangci.yaml
  .pre-commit-config.yaml
  bin/.golangci-lint-2.0.2.pkg
  bin/golangci-lint
  internal/inventory/awsfetcher/fetcher_lambda.go
  internal/resources/fetching/fetchers/aws/ecr_fetcher_test.go
  internal/resources/fetching/fetchers/aws/elb_fetcher_test.go
  internal/resources/fetching/fetchers/aws/kms_fetcher.go
  internal/resources/fetching/fetchers/gcp/assets_fetcher_test.go
  internal/resources/fetching/fetchers/k8s/file_system_fetcher_test.go
  internal/resources/providers/awslib/elb_v2/provider_v2.go
  internal/resources/providers/gcplib/inventory/provider_test.go
  internal/uniqueness/leaderelection_test.go
  internal/vulnerability/worker_test.go
  magefile.go
Labels: backport-v8.x

#3174 Publish cloudformation from 8.x branch
  .github/workflows/publish-cloudformation.yml
Labels: backport-v8.x

#3095 Add support for running ECH and Serverless test workflows on 8.x versions
  .github/workflows/test-e2e-flow.yml
  .github/workflows/test-ech-agentless.yml
  .github/workflows/test-runner.yml
  .github/workflows/weekly-serverless.yml
  dev-docs/Cloud-Env-Testing.md
Labels: automation, backport-v8.x

#3129 cspm cloud connectors: add cloudformation for the customer remote role
  deploy/cloudformation/cloud-connectors-remote-role-organization.yml
  deploy/cloudformation/cloud-connectors-remote-role.yml
  scripts/publish_cft.sh
Labels: backport-v8.x

#3177 Update deployment name
  .github/workflows/test-e2e-flow.yml
Labels: backport-skip, automation

#3180 Update README.md
  README.md
Labels: backport-skip

#3183 New way of backporting active branches
  .github/workflows/backport-active.yml
  .mergify.yml
Labels: backport-v8.x

#3179 use result.evaluation in event.outcome
  internal/transformer/events_creator.go
  internal/vulnerability/events_creator.go
Labels: backport-v8.x

#3203 mergify: support 8.19 and remove support 8.x
  .mergify.yml
Labels: backport-skip

#3211 CFT upload: use minor patch version
  scripts/publish_cft.sh
Labels: backport-v9.0.0, backport-v8.17.0, backport-v8.18.0, backport-v8.19.0

#3217 Update test runner workflow to support 8.19 branch
  .github/workflows/test-runner.yml
Labels: backport-skip

#3218 Update references from 8.x to 8.19 following branch deprecation
  .github/dependabot.yml
  .github/workflows/arm-template-lint.yml
  .github/workflows/ci-pull_request.yml
  .github/workflows/ci.yml
  .github/workflows/cloudformation-ci.yml
  .github/workflows/eks-ci.yml
  .github/workflows/packaging.yml
  .github/workflows/publish-cloudformation.yml
  .github/workflows/unit-test.yml
  .github/workflows/updatecli.yml
  dev-docs/Cloud-Env-Testing.md
Labels: backport-skip

#3231 Remove Azure Username and Password authentication because it's deprecated on 1.9.0
  internal/config/config.go
  internal/resources/providers/azurelib/auth/auth_provider.go
  internal/resources/providers/azurelib/auth/credentials.go
  internal/resources/providers/azurelib/auth/credentials_test.go
  internal/resources/providers/azurelib/auth/mock_azure_auth_provider_api.go
Labels: backport-v8.x, backport-v9.0.0, backport-v8.19.0

#3108 Update ci.yml
  .github/workflows/ci.yml
Labels: backport-active-all
