Repository elastic/cloudbeat, pull requests merged in 2025-09, with the labels that each got.

#3552 [updatecli] 9.1 - Update Golang version to 1.24.6
  .go-version
  bin/.go-1.24.6.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: backport-skip, automation, dependency, go

#3559 Add contextual-security team with manage access
  catalog-info.yaml
Labels: backport-skip

#3595 [updatecli] main - Update hermit and pre-commit dependencies
  bin/.awscli-2.30.2.pkg
  bin/aws
  bin/aws_completer
Labels: backport-skip, automation, dependency

#3613 GH actions: Improve caching
  .ci/scripts/gh-cache.sh
  .github/actions/hermit/action.yml
  .github/workflows/eks-ci.yml
Labels: automation, backport-v9.1.0, backport-v8.19.0

#3590 [updatecli] main - Update Golang version to 1.25.1
  .go-version
  bin/.go-1.25.1.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: backport-skip, automation, dependency, go
