Repository elastic/cloudbeat, pull requests merged in 2025-05, with the labels that each got.

#3189 [CSPM] Align rule fields with ECS schema
  internal/dataprovider/providers/rule_ecs/data_provider.go
  internal/dataprovider/providers/rule_ecs/data_provider_test.go
  internal/evaluator/evaluator.go
  internal/flavors/benchmark/builder/builder.go
  internal/transformer/events_creator.go
  internal/transformer/events_creator_test.go
Labels: backport-v8.19.0

#3274 [go] Bump golang to v1.23.9
  .go-version
  bin/.go-1.23.9.pkg
  bin/go
  bin/gofmt
  go.mod
Labels: backport-skip, go, dependencies

#3301 Bump the version used for test environments
  bin/hermit.hcl
Labels: automation

#3309 Disable cloudbeat version sync workflow
  .github/workflows/sync-internal-cloudbeat-version.yml
Labels: backport-active-all
