Repository elastic/cloudbeat, pull requests merged in 2025-02, with the labels that each got.

#2989 mergify: support backport-active-8, backport-active-9, backport-active-all
  .mergify.yml
Labels: backport-skip

#2986 [Go] Fix a flaky Kubernetes test setup
  internal/dataprovider/providers/k8s/cluster_name_provider_test.go
Labels: backport-v8.x

#2978 [updatecli] 9.0 - Update to elastic/beats@da630c6fab5a
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2979 [updatecli] main - Update to elastic/beats@d43b3b7ed9ce
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2980 [updatecli] 8.x - Update to elastic/beats@f7babd61a94e
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2983 [updatecli] 8.x - Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2984 [updatecli] main - Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2996 [updatecli] 9.0 - Update Golang version to 1.23.6
  .go-version
  bin/.go-1.23.6.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: backport-skip, automation, dependency, go

#2995 [updatecli] main - Update Golang version to 1.23.6
  .go-version
  bin/.go-1.23.6.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: backport-skip, automation, dependency, go

#2994 [updatecli] 8.x - Update Golang version to 1.23.6
  .go-version
  bin/.go-1.23.6.pkg
  bin/go
  bin/gofmt
  docs/version.asciidoc
Labels: backport-skip, automation, dependency, go

#2948 Enrich GCP asset types with ECS fields
  internal/inventory/asset.go
  internal/inventory/gcpfetcher/fetcher_assets.go
  internal/inventory/gcpfetcher/fetcher_assets_test.go
  internal/inventory/inventory.go
  internal/inventory/inventory_test.go
Labels: backport-v8.x

#3008 Fix skipped assets inventory CI
  .github/workflows/ci.yml
  tests/product/tests/data/azure_asset_inventory/test_cases.py
Labels: backport-v8.x

#2954 [Asset Inventory][Azure] Add missing resources and ECS fields required for GA
  .github/workflows/ci-pull_request.yml
  internal/flavors/assetinventory/strategy.go
  internal/inventory/ASSETS.md
  internal/inventory/asset.go
  internal/inventory/azurefetcher/azurefetchers.go
  internal/inventory/azurefetcher/fetcher_account.go
  internal/inventory/azurefetcher/fetcher_account_test.go
  internal/inventory/azurefetcher/fetcher_activedirectory.go
  internal/inventory/azurefetcher/fetcher_activedirectory_test.go
  internal/inventory/azurefetcher/fetcher_resource_graph.go
  internal/inventory/azurefetcher/fetcher_resource_graph_test.go
  internal/inventory/azurefetcher/fetcher_storage.go
  internal/inventory/azurefetcher/fetcher_storage_test.go
  internal/inventory/azurefetcher/mock_activedirectory_provider.go
  internal/inventory/cloud_assets.xlsx
  internal/resources/providers/azurelib/inventory/asset.go
  internal/resources/providers/azurelib/inventory/storage_provider_test.go
  internal/resources/providers/azurelib/inventory/subscriptions_provider_test.go
  internal/resources/providers/azurelib/inventory/susbcriptions_provider.go
  internal/resources/providers/msgraph/mock_provider_api.go
  internal/resources/providers/msgraph/provider.go
Labels: backport-v8.x

#3012 Update golangci-lint to 1.64.2
  .golangci.yaml
  bin/.golangci-lint-1.64.2.pkg
  bin/golangci-lint
  cmd/root.go
  deploy/asset-inventory-cloudformation/config.go
  deploy/cloudformation/config.go
  internal/flavors/assetinventory/strategy.go
  internal/flavors/benchmark/eks.go
  internal/inventory/azurefetcher/fetcher_activedirectory_test.go
  internal/launcher/launcher.go
  internal/launcher/launcher_test.go
  internal/resources/fetching/fetchers/aws/ecr_fetcher_test.go
  internal/resources/fetching/fetchers/aws/elb_fetcher_test.go
  internal/resources/fetching/fetchers/aws/monitoring_fetcher_test.go
  internal/resources/fetching/fetchers/azure/assets_fetcher.go
  internal/resources/fetching/fetchers/azure/batch_fetcher.go
  internal/resources/fetching/fetchers/azure/locations_network_watcher_batch_fetcher.go
  internal/resources/fetching/fetchers/azure/locations_network_watcher_batch_fetcher_test.go
  internal/resources/fetching/fetchers/azure/security_fetcher.go
  internal/resources/providers/awslib/cluster_name_provider.go
  internal/resources/providers/awslib/ec2/provider_test.go
  internal/resources/providers/awslib/securityhub/provider_test.go
  internal/resources/providers/azurelib/inventory/app_service_provider_test.go
  internal/vulnerability/cleaner_test.go
  internal/vulnerability/fetcher_test.go
Labels: technical debt, backport-v8.x

#3017 Ensure cloudbeat is installed with >= 9.x elastic-agent
  deploy/asset-inventory-arm/install-agent-dev.sh
  deploy/asset-inventory-arm/install-agent.sh
  deploy/asset-inventory-cloudformation/elastic-agent-ec2-organization.yml
  deploy/asset-inventory-cloudformation/elastic-agent-ec2.yml
  deploy/azure/install-agent-dev.sh
  deploy/azure/install-agent.sh
  deploy/cloudformation/elastic-agent-ec2-cnvm.yml
  deploy/cloudformation/elastic-agent-ec2-cspm-organization.yml
  deploy/cloudformation/elastic-agent-ec2-cspm.yml
  deploy/deployment-manager/compute_engine.py
  tests/integration/tests/test_sanity_checks.py
Labels: backport-v9.0.0

#2988 Fix Create Environment workflow issues
  .github/actions/cdr/action.yml
  .github/actions/cis-agent-based/action.yml
  deploy/test-environments/cis/output.tf
Labels: backport-v8.x

#3023 Update install-agent.sh script
  deploy/azure/install-agent-dev.sh
  deploy/azure/install-agent.sh
Labels: backport-v8.x

#3026 [updatecli] main - Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#3027 [updatecli] 8.x - Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#3025 [updatecli] 8.x - Update to elastic/beats@61caa19a696f
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#3032 Fix CloudFormation templates to support installation on both 8.x and 9.x versions
  deploy/asset-inventory-cloudformation/elastic-agent-ec2-organization.yml
  deploy/asset-inventory-cloudformation/elastic-agent-ec2.yml
  deploy/cloudformation/elastic-agent-ec2-cnvm.yml
  deploy/cloudformation/elastic-agent-ec2-cspm-organization.yml
  deploy/cloudformation/elastic-agent-ec2-cspm.yml
Labels: backport-v8.x, backport-v9.0.0, backport-v8.18.0

#3029 Add support for bundling Cloudbeat in Agent 9.x within CI workflows and installation scripts.
  .ci/scripts/run_agent.sh
  .github/workflows/test-environment.yml
  tests/fleet_api/utils.py
  tests/integrations_setup/configuration_fleet.py
  tests/integrations_setup/data/cspm-linux.j2
  tests/integrations_setup/install_aws_asset_inventory_integration.py
  tests/integrations_setup/install_az_activity_logs_integration.py
  tests/integrations_setup/install_azure_asset_inventory_integration.py
  tests/integrations_setup/install_cloudtrail_integration.py
  tests/integrations_setup/install_cnvm_integration.py
  tests/integrations_setup/install_cspm_azure_integration.py
  tests/integrations_setup/install_cspm_gcp_integration.py
  tests/integrations_setup/install_cspm_integration.py
  tests/integrations_setup/install_gcp_audit_logs_integration.py
  tests/integrations_setup/install_wiz_integration.py
Labels: backport-v8.x

#3044 Update GCP label in GCP Deployment Manager workflow
  .github/workflows/test-gcp-dm.yml
Labels: backport-v8.x, backport-v9.0.0, backport-v8.18.0

#3049 [Asset Inventory][Azure] Fix empty `entity.name` field for some resources
  internal/inventory/azurefetcher/common.go
  internal/inventory/azurefetcher/fetcher_account.go
  internal/inventory/azurefetcher/fetcher_activedirectory.go
  internal/inventory/azurefetcher/fetcher_resource_graph.go
  internal/inventory/azurefetcher/fetcher_storage.go
Labels: backport-v8.x, backport-v9.0.0, backport-v9.1.0

#3039 Update workflow to fix running UI sanity tests.
  .github/actions/elk-stack/action.yml
Labels: automation, backport-v8.x

#2981 [updatecli] main - Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.aws-iam-authenticator-0.6.30.pkg
  bin/.awscli-2.24.10.pkg
  bin/.elastic-package-0.109.1.pkg
  bin/.gcloud-511.0.0.pkg
  bin/.gh-2.67.0.pkg
  bin/.golangci-lint-1.64.5.pkg
  bin/.kind-0.27.0.pkg
  bin/.opa-1.1.0.pkg
  bin/.regal-0.31.0.pkg
  bin/aws
  bin/aws-iam-authenticator
  bin/aws_completer
  bin/bq
  bin/docker-credential-gcloud
  bin/elastic-package
  bin/gcloud
  bin/gh
  bin/git-credential-gcloud.sh
  bin/golangci-lint
  bin/gsutil
  bin/kind
  bin/opa
  bin/regal
  deploy/cloudformation/elastic-agent-ec2-cnvm.yml
  deploy/cloudformation/elastic-agent-ec2-cspm-organization.yml
  deploy/cloudformation/elastic-agent-ec2-cspm.yml
Labels: automation, dependency, backport-v9.0.0

#3052 [updatecli] main - Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#2982 [updatecli] 8.x - Update hermit and pre-commit dependencies
  .pre-commit-config.yaml
  bin/.aws-iam-authenticator-0.6.30.pkg
  bin/.awscli-2.24.10.pkg
  bin/.elastic-package-0.109.1.pkg
  bin/.gcloud-511.0.0.pkg
  bin/.gh-2.67.0.pkg
  bin/.golangci-lint-1.64.5.pkg
  bin/.kind-0.27.0.pkg
  bin/.opa-1.1.0.pkg
  bin/.regal-0.31.0.pkg
  bin/aws
  bin/aws-iam-authenticator
  bin/aws_completer
  bin/bq
  bin/docker-credential-gcloud
  bin/elastic-package
  bin/gcloud
  bin/gh
  bin/git-credential-gcloud.sh
  bin/golangci-lint
  bin/gsutil
  bin/kind
  bin/opa
  bin/regal
  deploy/cloudformation/elastic-agent-ec2-cnvm.yml
  deploy/cloudformation/elastic-agent-ec2-cspm-organization.yml
  deploy/cloudformation/elastic-agent-ec2-cspm.yml
Labels: backport-skip, automation, dependency

#3019 [Assets Inventory] Add network asset
  internal/inventory/asset.go
  internal/inventory/gcpfetcher/fetcher_assets.go
  internal/inventory/gcpfetcher/fetcher_assets_test.go
Labels: backport-v8.x

#2998 update snyk branch monitoring in bump-version workflow
  .github/workflows/bump-version.yml
  scripts/bump_cloudbeat.sh
Labels: backport-v8.x

#3030 Change updatdcli to run monthly
  .github/workflows/updatecli.yml
Labels: backport-v8.x

#3051 [updatecli] 8.x - Update golang mod dependencies
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go

#3050 [updatecli] 8.x - Update to elastic/beats@b5bf95171d62
  go.mod
  go.sum
Labels: backport-skip, automation, dependency, go
